import type { CategoryId, QuestCategory } from "@/types/learning";

export const questCategories: QuestCategory[] = [
  {
    id: "cafe",
    name: "Café",
    stageTitle: "Erste Bestellung",
    description: "Bestelle einfache Dinge auf Japanisch.",
    unlockLevel: 0,
    rewardXp: 50,
    collectedCardIds: ["coffee", "water", "bread", "drink", "eat"],
    unlocksNext: "reise",
    questions: [
      {
        id: "cafe-q1",
        type: "meaning-choice",
        categoryId: "cafe",
        prompt: "コーヒー",
        instruction: "Wähle die richtige Bedeutung.",
        choices: ["Kaffee", "Wasser", "Brot", "essen"],
        answer: "Kaffee",
        vocabId: "coffee",
        exampleJapanese: "コーヒーをください。",
        exampleKana: "コーヒーをください。",
        exampleGerman: "Einen Kaffee bitte.",
        shortTip: "「ください」は注文やお願いで使える基本表現です。",
        detailTip:
          "「コーヒーをください」は、カフェや店で使える丁寧なお願いです。カジュアルには「コーヒーください」と言うこともあります。",
      },
      {
        id: "cafe-q2",
        type: "japanese-choice",
        categoryId: "cafe",
        prompt: "trinken",
        instruction: "Wähle die passende Wortkarte.",
        choices: ["飲む", "食べる", "水", "パン"],
        answer: "飲む",
        vocabId: "drink",
        exampleJapanese: "水を飲みます。",
        exampleKana: "みずをのみます。",
        exampleGerman: "Ich trinke Wasser.",
      },
      {
        id: "cafe-q3",
        type: "fill-blank",
        categoryId: "cafe",
        prompt: "パンを____。",
        instruction: "Ergänze den Satz.",
        choices: ["食べます", "飲みます", "行きます", "好きです"],
        answer: "食べます",
        vocabId: "eat",
        exampleJapanese: "パンを食べます。",
        exampleKana: "パンをたべます。",
        exampleGerman: "Ich esse Brot.",
      },
      {
        id: "cafe-q4",
        type: "phrase-choice",
        categoryId: "cafe",
        prompt: "Wasser bitte.",
        instruction: "Wähle den natürlichen japanischen Satz.",
        choices: [
          "水をください。",
          "水を飲みます。",
          "パンをください。",
          "コーヒーを飲みます。",
        ],
        answer: "水をください。",
        vocabId: "water",
        answerKana: "みずをください。",
        answerRomaji: "mizu o kudasai",
        answerGerman: "Wasser bitte.",
        exampleJapanese: "水をください。",
        exampleKana: "みずをください。",
        exampleGerman: "Wasser bitte.",
        shortTip: "「〜をください」は注文やお願いで使えます。",
        detailTip:
          "「水をください」は、店やレストランで使える実用表現です。「ください」は丁寧なお願いです。「水を飲みます」は「Ich trinke Wasser.」なので、注文の意味にはなりません。",
      },
      {
        id: "cafe-challenge",
        type: "phrase-choice",
        categoryId: "cafe",
        label: "Abschluss-Challenge",
        isChallenge: true,
        prompt: "Kaffee und Brot bitte.",
        instruction: "Wähle den natürlichen japanischen Satz.",
        choices: [
          "コーヒーとパンをください。",
          "コーヒーを飲みます。パンを食べます。",
          "コーヒーを食べます。パンを飲みます。",
          "水と駅をください。",
        ],
        answer: "コーヒーとパンをください。",
        answerKana: "コーヒーとパンをください。",
        answerRomaji: "koohii to pan o kudasai",
        answerGerman: "Kaffee und Brot bitte.",
        exampleJapanese: "コーヒーとパンをください。",
        exampleKana: "コーヒーとパンをください。",
        exampleGerman: "Kaffee und Brot bitte.",
        shortTip: "「AとB」は「A und B」です。",
        detailTip:
          "「と」は名詞をつなぐ時に使います。例: コーヒーとパン = Kaffee und Brot。「〜をください」を付けると、注文表現になります。",
      },
    ],
  },
  {
    id: "reise",
    name: "Reise",
    stageTitle: "Ankunft in Japan",
    description: "Finde deinen Weg am Bahnhof und im Hotel.",
    unlockLevel: 1,
    rewardXp: 80,
    collectedCardIds: ["station", "hotel", "train", "toilet", "go"],
    unlocksNext: "schule",
    questions: [
      {
        id: "reise-q1",
        type: "meaning-choice",
        categoryId: "reise",
        prompt: "駅",
        instruction: "Wähle die richtige Bedeutung.",
        choices: ["Bahnhof", "Hotel", "Zug", "Toilette"],
        answer: "Bahnhof",
        vocabId: "station",
        exampleJapanese: "駅はどこですか。",
        exampleKana: "えきはどこですか。",
        exampleGerman: "Wo ist der Bahnhof?",
      },
      {
        id: "reise-q2",
        type: "japanese-choice",
        categoryId: "reise",
        prompt: "gehen",
        instruction: "Wähle die passende Wortkarte.",
        choices: ["行く", "駅", "ホテル", "電車"],
        answer: "行く",
        vocabId: "go",
        exampleJapanese: "駅に行きます。",
        exampleKana: "えきにいきます。",
        exampleGerman: "Ich gehe zum Bahnhof.",
      },
      {
        id: "reise-q3",
        type: "fill-blank",
        categoryId: "reise",
        prompt: "駅に____。",
        instruction: "Ergänze den Satz.",
        choices: ["行きます", "食べます", "飲みます", "好きです"],
        answer: "行きます",
        vocabId: "go",
        exampleJapanese: "駅に行きます。",
        exampleKana: "えきにいきます。",
        exampleGerman: "Ich gehe zum Bahnhof.",
      },
      {
        id: "reise-q4",
        type: "phrase-choice",
        categoryId: "reise",
        prompt: "Wo ist der Bahnhof?",
        instruction: "Wähle den natürlichen japanischen Satz.",
        choices: [
          "駅はどこですか。",
          "駅に行きます。",
          "ホテルはどこですか。",
          "電車に乗ります。",
        ],
        answer: "駅はどこですか。",
        vocabId: "station",
        answerKana: "えきはどこですか。",
        answerRomaji: "eki wa doko desu ka",
        answerGerman: "Wo ist der Bahnhof?",
        exampleJapanese: "駅はどこですか。",
        exampleKana: "えきはどこですか。",
        exampleGerman: "Wo ist der Bahnhof?",
        shortTip: "「〜はどこですか」は場所を尋ねる表現です。",
        detailTip:
          "「駅はどこですか」は道を尋ねるときの定番フレーズです。他の場所にも「〜はどこですか」の形が使えます。",
      },
      {
        id: "reise-challenge",
        type: "phrase-choice",
        categoryId: "reise",
        label: "Abschluss-Challenge",
        isChallenge: true,
        prompt: "Ich fahre mit dem Zug zum Bahnhof.",
        instruction: "Wähle den natürlichen japanischen Satz.",
        choices: [
          "電車で駅に行きます。",
          "駅で電車に乗ります。",
          "ホテルで電車に乗ります。",
          "駅とホテルに行きます。",
        ],
        answer: "電車で駅に行きます。",
        answerKana: "でんしゃでえきにいきます。",
        answerRomaji: "densha de eki ni ikimasu",
        answerGerman: "Ich fahre mit dem Zug zum Bahnhof.",
        exampleJapanese: "電車で駅に行きます。",
        exampleKana: "でんしゃでえきにいきます。",
        exampleGerman: "Ich fahre mit dem Zug zum Bahnhof.",
        shortTip: "「〜で」は手段を表します。",
        detailTip:
          "「電車で」は移動手段を表す「で」です。「電車で駅に行きます」は Ich fahre mit dem Zug zum Bahnhof. です。",
      },
    ],
  },
  {
    id: "schule",
    name: "Schule",
    stageTitle: "Lernen und Alltag",
    description: "Sprich über Schule, Sprache und den heutigen Tag.",
    unlockLevel: 2,
    rewardXp: 100,
    collectedCardIds: [
      "school",
      "teacher",
      "japaneseLanguage",
      "study",
      "today",
    ],
    unlocksNext: "freunde",
    questions: [
      {
        id: "schule-q1",
        type: "meaning-choice",
        categoryId: "schule",
        prompt: "学校",
        instruction: "Wähle die richtige Bedeutung.",
        choices: ["Schule", "Lehrer/Lehrerin", "Japanisch", "heute"],
        answer: "Schule",
        vocabId: "school",
        exampleJapanese: "学校に行きます。",
        exampleKana: "がっこうにいきます。",
        exampleGerman: "Ich gehe zur Schule.",
      },
      {
        id: "schule-q2",
        type: "japanese-choice",
        categoryId: "schule",
        prompt: "lernen",
        instruction: "Wähle die passende Wortkarte.",
        choices: ["勉強する", "学校", "先生", "日本語"],
        answer: "勉強する",
        vocabId: "study",
        exampleJapanese: "日本語を勉強します。",
        exampleKana: "にほんごをべんきょうします。",
        exampleGerman: "Ich lerne Japanisch.",
      },
      {
        id: "schule-q3",
        type: "fill-blank",
        categoryId: "schule",
        prompt: "日本語を____。",
        instruction: "Ergänze den Satz.",
        choices: ["勉強します", "食べます", "飲みます", "行きます"],
        answer: "勉強します",
        vocabId: "study",
        exampleJapanese: "日本語を勉強します。",
        exampleKana: "にほんごをべんきょうします。",
        exampleGerman: "Ich lerne Japanisch.",
      },
      {
        id: "schule-q4",
        type: "phrase-choice",
        categoryId: "schule",
        prompt: "Ich lerne heute Japanisch.",
        instruction: "Wähle den natürlichen japanischen Satz.",
        choices: [
          "今日、日本語を勉強します。",
          "今日、学校に行きます。",
          "先生と日本語を話します。",
          "日本語が好きです。",
        ],
        answer: "今日、日本語を勉強します。",
        vocabId: "japaneseLanguage",
        answerKana: "きょう、にほんごをべんきょうします。",
        answerRomaji: "kyou, nihongo o benkyou shimasu",
        answerGerman: "Ich lerne heute Japanisch.",
        exampleJapanese: "今日、日本語を勉強します。",
        exampleKana: "きょう、にほんごをべんきょうします。",
        exampleGerman: "Ich lerne heute Japanisch.",
        shortTip: "時を表す言葉は文の最初に置くと自然です。",
        detailTip:
          "「今日」は文頭に置かれることが多い時間表現です。「今日、日本語を勉強します」は Ich lerne heute Japanisch. です。",
      },
      {
        id: "schule-challenge",
        type: "phrase-choice",
        categoryId: "schule",
        label: "Abschluss-Challenge",
        isChallenge: true,
        prompt: "Heute gehe ich zur Schule und lerne Japanisch.",
        instruction: "Wähle den natürlichen japanischen Satz.",
        choices: [
          "今日、学校に行きます。日本語を勉強します。",
          "今日、先生に会います。",
          "学校で日本語を食べます。",
          "明日、日本語を勉強します。",
        ],
        answer: "今日、学校に行きます。日本語を勉強します。",
        answerKana: "きょう、がっこうにいきます。にほんごをべんきょうします。",
        answerRomaji:
          "kyou, gakkou ni ikimasu. nihongo o benkyou shimasu.",
        answerGerman: "Heute gehe ich zur Schule und lerne Japanisch.",
        exampleJapanese: "今日、学校に行きます。日本語を勉強します。",
        exampleKana: "きょう、がっこうにいきます。にほんごをべんきょうします。",
        exampleGerman: "Heute gehe ich zur Schule und lerne Japanisch.",
        shortTip: "2つの文をつなげるときは、単純に並べても大丈夫です。",
        detailTip:
          "「今日、学校に行きます。日本語を勉強します。」のように、短い文を並べるだけでも自然な日本語になります。",
      },
    ],
  },
  {
    id: "freunde",
    name: "Freunde",
    stageTitle: "Treffen und Pläne",
    description: "Sprich über Freunde und Pläne für morgen.",
    unlockLevel: 3,
    rewardXp: 110,
    collectedCardIds: ["friend", "meet", "talk", "tomorrow", "like"],
    unlocksNext: "review",
    questions: [
      {
        id: "freunde-q1",
        type: "meaning-choice",
        categoryId: "freunde",
        prompt: "友だち",
        instruction: "Wähle die richtige Bedeutung.",
        choices: ["Freund/Freundin", "treffen", "sprechen", "morgen"],
        answer: "Freund/Freundin",
        vocabId: "friend",
        exampleJapanese: "友だちに会います。",
        exampleKana: "ともだちにあいます。",
        exampleGerman: "Ich treffe einen Freund.",
      },
      {
        id: "freunde-q2",
        type: "japanese-choice",
        categoryId: "freunde",
        prompt: "treffen",
        instruction: "Wähle die passende Wortkarte.",
        choices: ["会う", "話す", "友だち", "明日"],
        answer: "会う",
        vocabId: "meet",
        exampleJapanese: "友だちに会います。",
        exampleKana: "ともだちにあいます。",
        exampleGerman: "Ich treffe einen Freund.",
      },
      {
        id: "freunde-q3",
        type: "fill-blank",
        categoryId: "freunde",
        prompt: "友だちと____。",
        instruction: "Ergänze den Satz.",
        choices: ["話します", "食べます", "飲みます", "行きます"],
        answer: "話します",
        vocabId: "talk",
        exampleJapanese: "友だちと話します。",
        exampleKana: "ともだちとはなします。",
        exampleGerman: "Ich spreche mit einem Freund.",
      },
      {
        id: "freunde-q4",
        type: "phrase-choice",
        categoryId: "freunde",
        prompt: "Morgen treffe ich einen Freund.",
        instruction: "Wähle den natürlichen japanischen Satz.",
        choices: [
          "明日、友だちに会います。",
          "今日、友だちに会います。",
          "明日、友だちと話します。",
          "友だちが好きです。",
        ],
        answer: "明日、友だちに会います。",
        vocabId: "tomorrow",
        answerKana: "あした、ともだちにあいます。",
        answerRomaji: "ashita, tomodachi ni aimasu",
        answerGerman: "Morgen treffe ich einen Freund.",
        exampleJapanese: "明日、友だちに会います。",
        exampleKana: "あした、ともだちにあいます。",
        exampleGerman: "Morgen treffe ich einen Freund.",
        shortTip: "「明日」は未来の予定を話すときに使います。",
        detailTip:
          "「明日、友だちに会います」は Morgen treffe ich einen Freund. です。「今日」との違いに注意しましょう。",
      },
      {
        id: "freunde-challenge",
        type: "phrase-choice",
        categoryId: "freunde",
        label: "Abschluss-Challenge",
        isChallenge: true,
        prompt: "Ich mag meinen Freund. Morgen treffe ich ihn.",
        instruction: "Wähle den natürlichen japanischen Satz.",
        choices: [
          "友だちが好きです。明日、会います。",
          "友だちが好きです。今日、話します。",
          "先生が好きです。明日、会います。",
          "友だちと話します。今日、会います。",
        ],
        answer: "友だちが好きです。明日、会います。",
        answerKana: "ともだちがすきです。あした、あいます。",
        answerRomaji: "tomodachi ga suki desu. ashita, aimasu.",
        answerGerman: "Ich mag meinen Freund. Morgen treffe ich ihn.",
        exampleJapanese: "友だちが好きです。明日、会います。",
        exampleKana: "ともだちがすきです。あした、あいます。",
        exampleGerman: "Ich mag meinen Freund. Morgen treffe ich ihn.",
        shortTip: "「好き」の対象には「が」を使います。",
        detailTip:
          "「友だちが好きです」の「が」は好きの対象を表します。「明日、会います」で未来の予定を伝えます。",
      },
    ],
  },
  {
    id: "review",
    name: "Abschluss-Review",
    stageTitle: "Alles zusammen",
    description: "Wiederhole Wörter aus allen Kategorien.",
    unlockLevel: 4,
    rewardXp: 150,
    collectedCardIds: [],
    isReview: true,
    questions: [
      {
        id: "review-q1",
        type: "meaning-choice",
        categoryId: "review",
        prompt: "水",
        instruction: "Wähle die richtige Bedeutung.",
        choices: ["Wasser", "Kaffee", "Brot", "Bahnhof"],
        answer: "Wasser",
        vocabId: "water",
        exampleJapanese: "水をください。",
        exampleKana: "みずをください。",
        exampleGerman: "Wasser bitte.",
      },
      {
        id: "review-q2",
        type: "japanese-choice",
        categoryId: "review",
        prompt: "Schule",
        instruction: "Wähle die passende Wortkarte.",
        choices: ["学校", "駅", "友だち", "パン"],
        answer: "学校",
        vocabId: "school",
        exampleJapanese: "学校に行きます。",
        exampleKana: "がっこうにいきます。",
        exampleGerman: "Ich gehe zur Schule.",
      },
      {
        id: "review-q3",
        type: "fill-blank",
        categoryId: "review",
        prompt: "友だちに____。",
        instruction: "Ergänze den Satz.",
        choices: ["会います", "食べます", "飲みます", "行きます"],
        answer: "会います",
        vocabId: "meet",
        exampleJapanese: "友だちに会います。",
        exampleKana: "ともだちにあいます。",
        exampleGerman: "Ich treffe einen Freund.",
      },
      {
        id: "review-q4",
        type: "phrase-choice",
        categoryId: "review",
        prompt: "Wasser bitte.",
        instruction: "Wähle den natürlichen japanischen Satz.",
        choices: [
          "水をください。",
          "水を飲みます。",
          "パンをください。",
          "コーヒーを飲みます。",
        ],
        answer: "水をください。",
        vocabId: "water",
        answerKana: "みずをください。",
        answerRomaji: "mizu o kudasai",
        answerGerman: "Wasser bitte.",
        exampleJapanese: "水をください。",
        exampleKana: "みずをください。",
        exampleGerman: "Wasser bitte.",
      },
      {
        id: "review-challenge",
        type: "phrase-choice",
        categoryId: "review",
        label: "Abschluss-Challenge",
        isChallenge: true,
        prompt: "Morgen gehe ich zur Schule und treffe einen Freund.",
        instruction: "Wähle den natürlichen japanischen Satz.",
        choices: [
          "明日、学校に行きます。友だちに会います。",
          "今日、学校に行きます。友だちに会います。",
          "明日、駅に行きます。先生に会います。",
          "明日、学校に行きます。パンを食べます。",
        ],
        answer: "明日、学校に行きます。友だちに会います。",
        answerKana: "あした、がっこうにいきます。ともだちにあいます。",
        answerRomaji:
          "ashita, gakkou ni ikimasu. tomodachi ni aimasu.",
        answerGerman: "Morgen gehe ich zur Schule und treffe einen Freund.",
        exampleJapanese: "明日、学校に行きます。友だちに会います。",
        exampleKana: "あした、がっこうにいきます。ともだちにあいます。",
        exampleGerman: "Morgen gehe ich zur Schule und treffe einen Freund.",
        shortTip: "このAbschluss-Reviewはすべてのカテゴリの単語を使います。",
        detailTip:
          "「明日、学校に行きます。友だちに会います。」は、Reise・Schule・Freundeの表現を組み合わせた文です。",
      },
    ],
  },
];

export function getQuestCategory(id: CategoryId): QuestCategory | undefined {
  return questCategories.find((category) => category.id === id);
}
