import type { CategoryId, QuestCategory } from "@/types/learning";

export const questCategories: QuestCategory[] = [
  {
    id: "cafe",
    name: "Café",
    stageTitle: "Erste Bestellung",
    description: "Bestelle einfache Dinge auf Japanisch.",
    unlockLevel: 0,
    rewardXp: 50,
    collectedCardIds: ["coffee", "water", "bread", "drink", "eat"],
    unlocksNext: "reise",
    questions: [
      {
        id: "cafe-q1",
        type: "meaning-choice",
        categoryId: "cafe",
        prompt: "コーヒー",
        instruction: "Wähle die richtige Bedeutung.",
        choices: ["Kaffee", "Wasser", "Brot", "essen"],
        answer: "Kaffee",
        vocabId: "coffee",
        exampleJapanese: "コーヒーをください。",
        exampleKana: "コーヒーをください。",
        exampleGerman: "Einen Kaffee bitte.",
        shortTip: "„コーヒーをください“ ist dein Standardsatz, um einen Kaffee zu bestellen.",
        detailTip:
          "Im Café sagst du einfach [Ding] + „をください“ – das ist die sichere Bestellform, egal was du willst. „コーヒーをください“ heißt „Einen Kaffee bitte“. Kurz und locker geht auch „コーヒーください“. Merk dir „ください“ als dein Zauberwort zum Bestellen.",
      },
      {
        id: "cafe-q2",
        type: "japanese-choice",
        categoryId: "cafe",
        prompt: "trinken",
        instruction: "Wähle die passende Wortkarte.",
        choices: ["飲む", "食べる", "水", "パン"],
        answer: "飲む",
        vocabId: "drink",
        exampleJapanese: "水を飲みます。",
        exampleKana: "みずをのみます。",
        exampleGerman: "Ich trinke Wasser.",
      },
      {
        id: "cafe-q3",
        type: "fill-blank",
        categoryId: "cafe",
        prompt: "パンを____。",
        instruction: "Ergänze den Satz.",
        choices: ["食べます", "飲みます", "行きます", "好きです"],
        answer: "食べます",
        vocabId: "eat",
        exampleJapanese: "パンを食べます。",
        exampleKana: "パンをたべます。",
        exampleGerman: "Ich esse Brot.",
      },
      {
        id: "cafe-q4",
        type: "phrase-choice",
        categoryId: "cafe",
        prompt: "Wasser bitte.",
        instruction: "Wähle den natürlichen japanischen Satz.",
        choices: [
          "水をください。",
          "水を飲みます。",
          "パンをください。",
          "コーヒーを飲みます。",
        ],
        answer: "水をください。",
        vocabId: "water",
        answerKana: "みずをください。",
        answerRomaji: "mizu o kudasai",
        answerGerman: "Wasser bitte.",
        exampleJapanese: "水をください。",
        exampleKana: "みずをください。",
        exampleGerman: "Wasser bitte.",
        shortTip: "„〜をください“ ist dein sicherer Standardsatz zum Bestellen.",
        detailTip:
          "Wenn du in Japan etwas bestellen willst, ist „〜をください“ die einfachste sichere Form. Setze einfach das Ding davor: 水をください = Wasser bitte. Das klingt höflich genug für Cafés und Läden. Nicht verwechseln: „水を飲みます“ heißt „Ich trinke Wasser“, nicht „Wasser bitte“.",
      },
      {
        id: "cafe-challenge",
        type: "phrase-choice",
        categoryId: "cafe",
        label: "Abschluss-Challenge",
        isChallenge: true,
        prompt: "Kaffee und Brot bitte.",
        instruction: "Wähle den natürlichen japanischen Satz.",
        choices: [
          "コーヒーとパンをください。",
          "コーヒーを飲みます。パンを食べます。",
          "コーヒーを食べます。パンを飲みます。",
          "水と駅をください。",
        ],
        answer: "コーヒーとパンをください。",
        answerKana: "コーヒーとパンをください。",
        answerRomaji: "koohii to pan o kudasai",
        answerGerman: "Kaffee und Brot bitte.",
        exampleJapanese: "コーヒーとパンをください。",
        exampleKana: "コーヒーとパンをください。",
        exampleGerman: "Kaffee und Brot bitte.",
        shortTip: "„A と B“ ist dein Werkzeug, um zwei Dinge auf einmal zu bestellen.",
        detailTip:
          "„と“ verbindet zwei Nomen wie das deutsche „und“: コーヒーとパン = Kaffee und Brot. Häng „〜をください“ dran, und du hast einen kompletten Bestellsatz: コーヒーとパンをください。 Das Muster funktioniert auch mit mehr als zwei Dingen. Ein Wort, doppelte Bestellung.",
      },
    ],
  },
  {
    id: "reise",
    name: "Reise",
    stageTitle: "Ankunft in Japan",
    description: "Frage nach Orten und bewege dich in Japan.",
    unlockLevel: 1,
    rewardXp: 80,
    collectedCardIds: [
      "station",
      "hotel",
      "train",
      "toilet",
      "go",
      "where",
      "excuseMe",
      "right",
      "left",
      "near",
      "far",
    ],
    unlocksNext: "schule",
    questions: [
      {
        id: "reise-q1",
        type: "meaning-choice",
        categoryId: "reise",
        prompt: "駅",
        instruction: "Wähle die richtige Bedeutung.",
        choices: ["Bahnhof", "Hotel", "Zug", "Toilette"],
        answer: "Bahnhof",
        vocabId: "station",
        exampleJapanese: "駅はどこですか。",
        exampleKana: "えきはどこですか。",
        exampleGerman: "Wo ist der Bahnhof?",
        shortTip: "„駅はどこですか“ ist deine Rettung, wenn du den Bahnhof suchst.",
        detailTip:
          "„駅“ heißt „Bahnhof“ und ist eines der wichtigsten Reisewörter überhaupt. Das Muster „〜はどこですか“ bedeutet „Wo ist …?“ und funktioniert für jeden Ort: ホテルはどこですか, トイレはどこですか. Vergiss das „は“ nicht – ohne „は“ klingt der Satz unvollständig. Mit diesem einen Muster findest du fast alles.",
      },
      {
        id: "reise-q2",
        type: "japanese-choice",
        categoryId: "reise",
        prompt: "Toilette",
        instruction: "Wähle die passende japanische Wortkarte.",
        choices: ["トイレ", "駅", "電車", "ホテル"],
        answer: "トイレ",
        vocabId: "toilet",
        exampleJapanese: "トイレはどこですか。",
        exampleKana: "トイレはどこですか。",
        exampleGerman: "Wo ist die Toilette?",
        shortTip: "„トイレはどこですか“ – vielleicht der nützlichste Satz auf jeder Reise.",
        detailTip:
          "„トイレ“ kommt aus dem Englischen „toilet“ und wird ähnlich ausgesprochen. Mit „トイレはどこですか“ fragst du höflich nach der Toilette – das gleiche Muster wie bei „駅はどこですか“. Für noch mehr Höflichkeit stellst du „すみません“ voran. Diesen Satz solltest du zuerst auswendig lernen.",
      },
      {
        id: "reise-q3",
        type: "fill-blank",
        categoryId: "reise",
        prompt: "ホテルに____。",
        instruction: "Ergänze den Satz.",
        choices: ["行きます", "食べます", "飲みます", "話します"],
        answer: "行きます",
        vocabId: "go",
        exampleJapanese: "ホテルに行きます。",
        exampleKana: "ホテルにいきます。",
        exampleGerman: "Ich gehe zum Hotel.",
        shortTip: "„〜に行きます“ zeigt, wohin du gehst oder fährst.",
        detailTip:
          "„に“ markiert das Ziel: ホテルに行きます = Ich gehe zum Hotel. Ein häufiger Fehler ist, hier „で“ statt „に“ zu benutzen – „で“ ist für das Verkehrsmittel reserviert, nicht das Ziel. Eselsbrücke: „に“ zeigt wie ein Pfeil auf den Ort, wo du hinwillst. Das Muster funktioniert für jedes Reiseziel.",
      },
      {
        id: "reise-q4",
        type: "particle-choice",
        categoryId: "reise",
        prompt: "電車____行きます。",
        instruction: "Wähle die passende Partikel.",
        choices: ["で", "に", "を", "は"],
        answer: "で",
        vocabId: "train",
        exampleJapanese: "電車で行きます。",
        exampleKana: "でんしゃでいきます。",
        exampleGerman: "Ich fahre mit dem Zug.",
        shortTip: "„で“ zeigt hier, womit du dich bewegst: Zug, Bus oder Auto.",
        detailTip:
          "In „電車で行きます“ bedeutet „電車で“ ungefähr „mit dem Zug“. Das Muster ist sehr nützlich: 乗り物 + で + 行きます. Du kannst es austauschen: バスで行きます = Ich fahre mit dem Bus. Wichtig: Für das Ziel benutzt du nicht „で“, sondern „に“, z. B. ホテルに行きます.",
      },
      {
        id: "reise-q5",
        type: "phrase-choice",
        categoryId: "reise",
        prompt: "Wo ist der Bahnhof?",
        instruction: "Wähle den natürlichen japanischen Satz.",
        choices: [
          "駅はどこですか。",
          "ホテルに行きます。",
          "電車で行きます。",
          "トイレをください。",
        ],
        answer: "駅はどこですか。",
        vocabId: "station",
        answerKana: "えきはどこですか。",
        answerRomaji: "eki wa doko desu ka",
        answerGerman: "Wo ist der Bahnhof?",
        exampleJapanese: "駅はどこですか。",
        exampleKana: "えきはどこですか。",
        exampleGerman: "Wo ist der Bahnhof?",
        shortTip: "„〜はどこですか“ ist dein Werkzeug, um nach jedem Ort zu fragen.",
        detailTip:
          "„どこ“ bedeutet „wo“, zusammen mit „ですか“ wird daraus eine höfliche Frage. Das Muster [Ort] + はどこですか funktioniert universell: 駅はどこですか, ホテルはどこですか. Das „は“ verbindet den Ort mit der Frage – lass es nicht weg. Wenn du dir nur einen Reisesatz merkst, dann diesen.",
      },
      {
        id: "reise-q6",
        type: "meaning-choice",
        categoryId: "reise",
        prompt: "右",
        instruction: "Wähle die richtige Bedeutung.",
        choices: ["rechts", "links", "nah", "weit"],
        answer: "rechts",
        vocabId: "right",
        exampleJapanese: "右です。",
        exampleKana: "みぎです。",
        exampleGerman: "Es ist rechts.",
        shortTip: "„右です“ ist deine kurze Antwort, wenn jemand nach dem Weg fragt.",
        detailTip:
          "„右“ bedeutet „rechts“. Mit „です“ dahinter wird daraus eine vollständige, höfliche Antwort: 右です = Es ist rechts. Das gleiche Muster gilt für „左です“ (links). Bei Wegbeschreibungen auf Reisen reicht oft schon dieses eine Wort plus „です“.",
      },
      {
        id: "reise-q7",
        type: "fill-blank",
        categoryId: "reise",
        prompt: "駅は____です。",
        instruction: "Ergänze: Der Bahnhof ist nah.",
        choices: ["近い", "遠い", "右", "左"],
        answer: "近い",
        vocabId: "near",
        exampleJapanese: "駅は近いです。",
        exampleKana: "えきはちかいです。",
        exampleGerman: "Der Bahnhof ist nah.",
        shortTip: "„近いです“ sagt: das ist nicht weit von hier.",
        detailTip:
          "„近い“ bedeutet „nah“, mit „です“ wird es zur höflichen Aussage: 駅は近いです = Der Bahnhof ist nah. Das Gegenteil ist „遠いです“ (weit entfernt) – lerne beide Wörter als Paar. Das Muster [Ort] + は近いです funktioniert für jeden Ort. Praktisch, um schnell einzuschätzen, ob sich ein Fußweg lohnt.",
      },
      {
        id: "reise-q8",
        type: "phrase-choice",
        categoryId: "reise",
        prompt: "Entschuldigung, wo ist die Toilette?",
        instruction: "Wähle den natürlichen japanischen Satz.",
        choices: [
          "すみません、トイレはどこですか。",
          "トイレを飲みます。",
          "駅に食べます。",
          "ホテルは右をください。",
        ],
        answer: "すみません、トイレはどこですか。",
        vocabId: "excuseMe",
        answerKana: "すみません、トイレはどこですか。",
        answerRomaji: "sumimasen, toire wa doko desu ka",
        answerGerman: "Entschuldigung, wo ist die Toilette?",
        exampleJapanese: "すみません、トイレはどこですか。",
        exampleKana: "すみません、トイレはどこですか。",
        exampleGerman: "Entschuldigung, wo ist die Toilette?",
        shortTip: "„すみません“ am Satzanfang macht jede Frage automatisch höflicher.",
        detailTip:
          "„すみません“ bedeutet „Entschuldigung“ und ist die perfekte Türöffner-Floskel, bevor du jemanden ansprichst. Vor einer Wegfrage klingt sie automatisch freundlicher: すみません、トイレはどこですか。 Du kannst „すみません“ auch allein benutzen, um Aufmerksamkeit zu bekommen. Ein Wort, unzählige Situationen.",
      },
      {
        id: "reise-q9",
        type: "phrase-choice",
        categoryId: "reise",
        prompt: "The hotel is far away.",
        instruction: "Wähle den natürlichen japanischen Satz.",
        choices: [
          "ホテルは遠いです。",
          "ホテルは近いです。",
          "ホテルに食べます。",
          "電車をください。",
        ],
        answer: "ホテルは遠いです。",
        vocabId: "far",
        answerKana: "ホテルはとおいです。",
        answerRomaji: "hoteru wa tooi desu",
        answerGerman: "Das Hotel ist weit entfernt.",
        exampleJapanese: "ホテルは遠いです。",
        exampleKana: "ホテルはとおいです。",
        exampleGerman: "Das Hotel ist weit entfernt.",
        shortTip: "„遠いです“ sagt: das ist ein ganzes Stück entfernt.",
        detailTip:
          "„遠い“ bedeutet „weit“ oder „entfernt“, mit „です“ höflich als Aussage: ホテルは遠いです = Das Hotel ist weit entfernt. Es ist das Gegenteil von „近い“ (nah) – lerne beide zusammen. Diese Info hilft dir zu entscheiden, ob du lieber ein Taxi nimmst. Ein einfaches Wort mit großer praktischer Wirkung.",
      },
      {
        id: "reise-challenge",
        type: "phrase-choice",
        categoryId: "reise",
        label: "Abschluss-Challenge",
        isChallenge: true,
        prompt: "Ich fahre mit dem Zug zum Hotel.",
        instruction: "Wähle den natürlichen japanischen Satz.",
        choices: [
          "電車でホテルに行きます。",
          "ホテルで電車に行きます。",
          "電車をホテルに行きます。",
          "トイレでホテルに行きます。",
        ],
        answer: "電車でホテルに行きます。",
        vocabId: "train",
        answerKana: "でんしゃでホテルにいきます。",
        answerRomaji: "densha de hoteru ni ikimasu",
        answerGerman: "Ich fahre mit dem Zug zum Hotel.",
        exampleJapanese: "電車でホテルに行きます。",
        exampleKana: "でんしゃでホテルにいきます。",
        exampleGerman: "Ich fahre mit dem Zug zum Hotel.",
        shortTip: "„電車で“ zeigt das Verkehrsmittel, „ホテルに“ zeigt das Ziel – zusammen ein kompletter Reisesatz.",
        detailTip:
          "„電車でホテルに行きます“ verbindet Mittel und Ziel in einem Satz: „で“ für womit (mit dem Zug), „に“ für wohin (zum Hotel). Das Muster [Verkehrsmittel] + で + [Ort] + に + 行きます kannst du immer wieder benutzen: バスで駅に行きます = Ich fahre mit dem Bus zum Bahnhof. Ein typischer Fehler ist, „で“ und „に“ zu vertauschen – dann klingt der Satz falsch. Merk dir: で = womit, に = wohin.",
      },
    ],
  },
  {
    id: "schule",
    name: "Schule",
    stageTitle: "Lernen und Alltag",
    description: "Sprich über Schule, Sprache und den heutigen Tag.",
    unlockLevel: 2,
    rewardXp: 100,
    collectedCardIds: [
      "school",
      "teacher",
      "japaneseLanguage",
      "study",
      "today",
    ],
    unlocksNext: "freunde",
    questions: [
      {
        id: "schule-q1",
        type: "meaning-choice",
        categoryId: "schule",
        prompt: "学校",
        instruction: "Wähle die richtige Bedeutung.",
        choices: ["Schule", "Lehrer/Lehrerin", "Japanisch", "heute"],
        answer: "Schule",
        vocabId: "school",
        exampleJapanese: "学校に行きます。",
        exampleKana: "がっこうにいきます。",
        exampleGerman: "Ich gehe zur Schule.",
      },
      {
        id: "schule-q2",
        type: "japanese-choice",
        categoryId: "schule",
        prompt: "lernen",
        instruction: "Wähle die passende Wortkarte.",
        choices: ["勉強する", "学校", "先生", "日本語"],
        answer: "勉強する",
        vocabId: "study",
        exampleJapanese: "日本語を勉強します。",
        exampleKana: "にほんごをべんきょうします。",
        exampleGerman: "Ich lerne Japanisch.",
      },
      {
        id: "schule-q3",
        type: "fill-blank",
        categoryId: "schule",
        prompt: "日本語を____。",
        instruction: "Ergänze den Satz.",
        choices: ["勉強します", "食べます", "飲みます", "行きます"],
        answer: "勉強します",
        vocabId: "study",
        exampleJapanese: "日本語を勉強します。",
        exampleKana: "にほんごをべんきょうします。",
        exampleGerman: "Ich lerne Japanisch.",
      },
      {
        id: "schule-q4",
        type: "phrase-choice",
        categoryId: "schule",
        prompt: "Ich lerne heute Japanisch.",
        instruction: "Wähle den natürlichen japanischen Satz.",
        choices: [
          "今日、日本語を勉強します。",
          "今日、学校に行きます。",
          "先生と日本語を話します。",
          "日本語が好きです。",
        ],
        answer: "今日、日本語を勉強します。",
        vocabId: "japaneseLanguage",
        answerKana: "きょう、にほんごをべんきょうします。",
        answerRomaji: "kyou, nihongo o benkyou shimasu",
        answerGerman: "Ich lerne heute Japanisch.",
        exampleJapanese: "今日、日本語を勉強します。",
        exampleKana: "きょう、にほんごをべんきょうします。",
        exampleGerman: "Ich lerne heute Japanisch.",
        shortTip: "Zeitwörter stehen oft am Satzanfang.",
        detailTip:
          "„今日“ steht meistens am Satzanfang. „今日、日本語を勉強します“ bedeutet „Ich lerne heute Japanisch“.",
      },
      {
        id: "schule-challenge",
        type: "phrase-choice",
        categoryId: "schule",
        label: "Abschluss-Challenge",
        isChallenge: true,
        prompt: "Heute gehe ich zur Schule und lerne Japanisch.",
        instruction: "Wähle den natürlichen japanischen Satz.",
        choices: [
          "今日、学校に行きます。日本語を勉強します。",
          "今日、先生に会います。",
          "学校で日本語を食べます。",
          "明日、日本語を勉強します。",
        ],
        answer: "今日、学校に行きます。日本語を勉強します。",
        answerKana: "きょう、がっこうにいきます。にほんごをべんきょうします。",
        answerRomaji:
          "kyou, gakkou ni ikimasu. nihongo o benkyou shimasu.",
        answerGerman: "Heute gehe ich zur Schule und lerne Japanisch.",
        exampleJapanese: "今日、学校に行きます。日本語を勉強します。",
        exampleKana: "きょう、がっこうにいきます。にほんごをべんきょうします。",
        exampleGerman: "Heute gehe ich zur Schule und lerne Japanisch.",
        shortTip: "Zwei kurze Sätze kann man einfach hintereinander sagen.",
        detailTip:
          "„今日、学校に行きます。日本語を勉強します。“ klingt natürlich, auch wenn man die Sätze einfach aneinanderreiht.",
      },
    ],
  },
  {
    id: "freunde",
    name: "Freunde",
    stageTitle: "Treffen und Pläne",
    description: "Sprich über Freunde und Pläne für morgen.",
    unlockLevel: 3,
    rewardXp: 110,
    collectedCardIds: ["friend", "meet", "talk", "tomorrow", "like"],
    unlocksNext: "review",
    questions: [
      {
        id: "freunde-q1",
        type: "meaning-choice",
        categoryId: "freunde",
        prompt: "友だち",
        instruction: "Wähle die richtige Bedeutung.",
        choices: ["Freund/Freundin", "treffen", "sprechen", "morgen"],
        answer: "Freund/Freundin",
        vocabId: "friend",
        exampleJapanese: "友だちに会います。",
        exampleKana: "ともだちにあいます。",
        exampleGerman: "Ich treffe einen Freund.",
      },
      {
        id: "freunde-q2",
        type: "japanese-choice",
        categoryId: "freunde",
        prompt: "treffen",
        instruction: "Wähle die passende Wortkarte.",
        choices: ["会う", "話す", "友だち", "明日"],
        answer: "会う",
        vocabId: "meet",
        exampleJapanese: "友だちに会います。",
        exampleKana: "ともだちにあいます。",
        exampleGerman: "Ich treffe einen Freund.",
      },
      {
        id: "freunde-q3",
        type: "fill-blank",
        categoryId: "freunde",
        prompt: "友だちと____。",
        instruction: "Ergänze den Satz.",
        choices: ["話します", "食べます", "飲みます", "行きます"],
        answer: "話します",
        vocabId: "talk",
        exampleJapanese: "友だちと話します。",
        exampleKana: "ともだちとはなします。",
        exampleGerman: "Ich spreche mit einem Freund.",
      },
      {
        id: "freunde-q4",
        type: "phrase-choice",
        categoryId: "freunde",
        prompt: "Morgen treffe ich einen Freund.",
        instruction: "Wähle den natürlichen japanischen Satz.",
        choices: [
          "明日、友だちに会います。",
          "今日、友だちに会います。",
          "明日、友だちと話します。",
          "友だちが好きです。",
        ],
        answer: "明日、友だちに会います。",
        vocabId: "tomorrow",
        answerKana: "あした、ともだちにあいます。",
        answerRomaji: "ashita, tomodachi ni aimasu",
        answerGerman: "Morgen treffe ich einen Freund.",
        exampleJapanese: "明日、友だちに会います。",
        exampleKana: "あした、ともだちにあいます。",
        exampleGerman: "Morgen treffe ich einen Freund.",
        shortTip: "„明日“ benutzt man für zukünftige Pläne.",
        detailTip:
          "„明日、友だちに会います“ bedeutet „Morgen treffe ich einen Freund“. Achte auf den Unterschied zu „今日“.",
      },
      {
        id: "freunde-challenge",
        type: "phrase-choice",
        categoryId: "freunde",
        label: "Abschluss-Challenge",
        isChallenge: true,
        prompt: "Ich mag meinen Freund. Morgen treffe ich ihn.",
        instruction: "Wähle den natürlichen japanischen Satz.",
        choices: [
          "友だちが好きです。明日、会います。",
          "友だちが好きです。今日、話します。",
          "先生が好きです。明日、会います。",
          "友だちと話します。今日、会います。",
        ],
        answer: "友だちが好きです。明日、会います。",
        answerKana: "ともだちがすきです。あした、あいます。",
        answerRomaji: "tomodachi ga suki desu. ashita, aimasu.",
        answerGerman: "Ich mag meinen Freund. Morgen treffe ich ihn.",
        exampleJapanese: "友だちが好きです。明日、会います。",
        exampleKana: "ともだちがすきです。あした、あいます。",
        exampleGerman: "Ich mag meinen Freund. Morgen treffe ich ihn.",
        shortTip: "Bei „好き“ benutzt man „が“ für das, was man mag.",
        detailTip:
          "„が“ in „友だちが好きです“ zeigt, wen man mag. „明日、会います“ beschreibt einen zukünftigen Plan.",
      },
    ],
  },
  {
    id: "review",
    name: "Abschluss-Review",
    stageTitle: "Alles zusammen",
    description: "Wiederhole Wörter aus allen Kategorien.",
    unlockLevel: 4,
    rewardXp: 150,
    collectedCardIds: [],
    isReview: true,
    questions: [
      {
        id: "review-q1",
        type: "meaning-choice",
        categoryId: "review",
        prompt: "水",
        instruction: "Wähle die richtige Bedeutung.",
        choices: ["Wasser", "Kaffee", "Brot", "Bahnhof"],
        answer: "Wasser",
        vocabId: "water",
        exampleJapanese: "水をください。",
        exampleKana: "みずをください。",
        exampleGerman: "Wasser bitte.",
      },
      {
        id: "review-q2",
        type: "japanese-choice",
        categoryId: "review",
        prompt: "Schule",
        instruction: "Wähle die passende Wortkarte.",
        choices: ["学校", "駅", "友だち", "パン"],
        answer: "学校",
        vocabId: "school",
        exampleJapanese: "学校に行きます。",
        exampleKana: "がっこうにいきます。",
        exampleGerman: "Ich gehe zur Schule.",
      },
      {
        id: "review-q3",
        type: "fill-blank",
        categoryId: "review",
        prompt: "友だちに____。",
        instruction: "Ergänze den Satz.",
        choices: ["会います", "食べます", "飲みます", "行きます"],
        answer: "会います",
        vocabId: "meet",
        exampleJapanese: "友だちに会います。",
        exampleKana: "ともだちにあいます。",
        exampleGerman: "Ich treffe einen Freund.",
      },
      {
        id: "review-q4",
        type: "phrase-choice",
        categoryId: "review",
        prompt: "Wasser bitte.",
        instruction: "Wähle den natürlichen japanischen Satz.",
        choices: [
          "水をください。",
          "水を飲みます。",
          "パンをください。",
          "コーヒーを飲みます。",
        ],
        answer: "水をください。",
        vocabId: "water",
        answerKana: "みずをください。",
        answerRomaji: "mizu o kudasai",
        answerGerman: "Wasser bitte.",
        exampleJapanese: "水をください。",
        exampleKana: "みずをください。",
        exampleGerman: "Wasser bitte.",
      },
      {
        id: "review-challenge",
        type: "phrase-choice",
        categoryId: "review",
        label: "Abschluss-Challenge",
        isChallenge: true,
        prompt: "Morgen gehe ich zur Schule und treffe einen Freund.",
        instruction: "Wähle den natürlichen japanischen Satz.",
        choices: [
          "明日、学校に行きます。友だちに会います。",
          "今日、学校に行きます。友だちに会います。",
          "明日、駅に行きます。先生に会います。",
          "明日、学校に行きます。パンを食べます。",
        ],
        answer: "明日、学校に行きます。友だちに会います。",
        answerKana: "あした、がっこうにいきます。ともだちにあいます。",
        answerRomaji:
          "ashita, gakkou ni ikimasu. tomodachi ni aimasu.",
        answerGerman: "Morgen gehe ich zur Schule und treffe einen Freund.",
        exampleJapanese: "明日、学校に行きます。友だちに会います。",
        exampleKana: "あした、がっこうにいきます。ともだちにあいます。",
        exampleGerman: "Morgen gehe ich zur Schule und treffe einen Freund.",
        shortTip: "Dieses Abschluss-Review kombiniert Wörter aus allen Kategorien.",
        detailTip:
          "„明日、学校に行きます。友だちに会います。“ verbindet Ausdrücke aus Reise, Schule und Freunde.",
      },
    ],
  },
];

export function getQuestCategory(id: CategoryId): QuestCategory | undefined {
  return questCategories.find((category) => category.id === id);
}
