import type { CategoryId, QuestCategory } from "@/types/learning";

export const questCategories: QuestCategory[] = [
  {
    id: "cafe",
    name: "Café",
    stageTitle: "Erste Bestellung",
    description: "Bestelle einfache Dinge auf Japanisch.",
    unlockLevel: 0,
    rewardXp: 50,
    collectedCardIds: ["coffee", "water", "bread", "drink", "eat"],
    unlocksNext: "reise",
    questions: [
      {
        id: "cafe-q1",
        type: "meaning-choice",
        categoryId: "cafe",
        prompt: "コーヒー",
        instruction: "Wähle die richtige Bedeutung.",
        choices: ["Kaffee", "Wasser", "Brot", "essen"],
        answer: "Kaffee",
        vocabId: "coffee",
        exampleJapanese: "コーヒーをください。",
        exampleKana: "コーヒーをください。",
        exampleGerman: "Einen Kaffee bitte.",
        shortTip: "„Kudasai“ ist ein Grundausdruck für Bestellungen und Bitten.",
        detailTip:
          "„コーヒーをください“ ist eine höfliche Bitte, die man im Café oder Geschäft benutzt. Im lockeren Ton sagt man auch einfach „コーヒーください“.",
      },
      {
        id: "cafe-q2",
        type: "japanese-choice",
        categoryId: "cafe",
        prompt: "trinken",
        instruction: "Wähle die passende Wortkarte.",
        choices: ["飲む", "食べる", "水", "パン"],
        answer: "飲む",
        vocabId: "drink",
        exampleJapanese: "水を飲みます。",
        exampleKana: "みずをのみます。",
        exampleGerman: "Ich trinke Wasser.",
      },
      {
        id: "cafe-q3",
        type: "fill-blank",
        categoryId: "cafe",
        prompt: "パンを____。",
        instruction: "Ergänze den Satz.",
        choices: ["食べます", "飲みます", "行きます", "好きです"],
        answer: "食べます",
        vocabId: "eat",
        exampleJapanese: "パンを食べます。",
        exampleKana: "パンをたべます。",
        exampleGerman: "Ich esse Brot.",
      },
      {
        id: "cafe-q4",
        type: "phrase-choice",
        categoryId: "cafe",
        prompt: "Wasser bitte.",
        instruction: "Wähle den natürlichen japanischen Satz.",
        choices: [
          "水をください。",
          "水を飲みます。",
          "パンをください。",
          "コーヒーを飲みます。",
        ],
        answer: "水をください。",
        vocabId: "water",
        answerKana: "みずをください。",
        answerRomaji: "mizu o kudasai",
        answerGerman: "Wasser bitte.",
        exampleJapanese: "水をください。",
        exampleKana: "みずをください。",
        exampleGerman: "Wasser bitte.",
        shortTip: "„〜をください“ benutzt man beim Bestellen oder Bitten.",
        detailTip:
          "„水をください“ ist ein nützlicher Ausdruck im Geschäft oder Restaurant. „ください“ ist eine höfliche Bitte. „水を飲みます“ bedeutet „Ich trinke Wasser“ und ist daher keine Bestellung.",
      },
      {
        id: "cafe-challenge",
        type: "phrase-choice",
        categoryId: "cafe",
        label: "Abschluss-Challenge",
        isChallenge: true,
        prompt: "Kaffee und Brot bitte.",
        instruction: "Wähle den natürlichen japanischen Satz.",
        choices: [
          "コーヒーとパンをください。",
          "コーヒーを飲みます。パンを食べます。",
          "コーヒーを食べます。パンを飲みます。",
          "水と駅をください。",
        ],
        answer: "コーヒーとパンをください。",
        answerKana: "コーヒーとパンをください。",
        answerRomaji: "koohii to pan o kudasai",
        answerGerman: "Kaffee und Brot bitte.",
        exampleJapanese: "コーヒーとパンをください。",
        exampleKana: "コーヒーとパンをください。",
        exampleGerman: "Kaffee und Brot bitte.",
        shortTip: "„A と B“ bedeutet „A und B“.",
        detailTip:
          "„と“ verbindet zwei Nomen. Beispiel: コーヒーとパン = Kaffee und Brot. Mit „〜をください“ wird daraus ein Bestellsatz.",
      },
    ],
  },
  {
    id: "reise",
    name: "Reise",
    stageTitle: "Ankunft in Japan",
    description: "Frage nach Orten und bewege dich in Japan.",
    unlockLevel: 1,
    rewardXp: 80,
    collectedCardIds: [
      "station",
      "hotel",
      "train",
      "toilet",
      "go",
      "where",
      "excuseMe",
      "right",
      "left",
      "near",
      "far",
    ],
    unlocksNext: "schule",
    questions: [
      {
        id: "reise-q1",
        type: "meaning-choice",
        categoryId: "reise",
        prompt: "駅",
        instruction: "Wähle die richtige Bedeutung.",
        choices: ["Bahnhof", "Hotel", "Zug", "Toilette"],
        answer: "Bahnhof",
        vocabId: "station",
        exampleJapanese: "駅はどこですか。",
        exampleKana: "えきはどこですか。",
        exampleGerman: "Wo ist der Bahnhof?",
        shortTip: "„駅“ ist ein wichtiges Wort auf Reisen.",
        detailTip:
          "„駅はどこですか“ ist ein natürlicher Ausdruck, um nach dem Bahnhof zu fragen. „どこですか“ bedeutet „wo ist …?“.",
      },
      {
        id: "reise-q2",
        type: "japanese-choice",
        categoryId: "reise",
        prompt: "Toilette",
        instruction: "Wähle die passende japanische Wortkarte.",
        choices: ["トイレ", "駅", "電車", "ホテル"],
        answer: "トイレ",
        vocabId: "toilet",
        exampleJapanese: "トイレはどこですか。",
        exampleKana: "トイレはどこですか。",
        exampleGerman: "Wo ist die Toilette?",
        shortTip: "„トイレ“ wird auf Japanisch oft in Katakana geschrieben.",
        detailTip:
          "„トイレはどこですか“ ist sehr nützlich auf Reisen. Mit „すみません“ davor klingt die Frage noch höflicher.",
      },
      {
        id: "reise-q3",
        type: "fill-blank",
        categoryId: "reise",
        prompt: "ホテルに____。",
        instruction: "Ergänze den Satz.",
        choices: ["行きます", "食べます", "飲みます", "話します"],
        answer: "行きます",
        vocabId: "go",
        exampleJapanese: "ホテルに行きます。",
        exampleKana: "ホテルにいきます。",
        exampleGerman: "Ich gehe zum Hotel.",
        shortTip: "„〜に行きます“ bedeutet, dass man zu einem Ziel geht.",
        detailTip:
          "„に“ zeigt das Ziel an. „ホテルに行きます“ bedeutet, dass man zum Hotel geht.",
      },
      {
        id: "reise-q4",
        type: "particle-choice",
        categoryId: "reise",
        prompt: "電車____行きます。",
        instruction: "Wähle die passende Partikel.",
        choices: ["で", "に", "を", "は"],
        answer: "で",
        vocabId: "train",
        exampleJapanese: "電車で行きます。",
        exampleKana: "でんしゃでいきます。",
        exampleGerman: "Ich fahre mit dem Zug.",
        shortTip: "„で“ zeigt das Verkehrsmittel an.",
        detailTip:
          "„電車で行きます“ bedeutet „Ich fahre mit dem Zug“. Für Verkehrsmittel benutzt man „で“.",
      },
      {
        id: "reise-q5",
        type: "phrase-choice",
        categoryId: "reise",
        prompt: "Wo ist der Bahnhof?",
        instruction: "Wähle den natürlichen japanischen Satz.",
        choices: [
          "駅はどこですか。",
          "ホテルに行きます。",
          "電車で行きます。",
          "トイレをください。",
        ],
        answer: "駅はどこですか。",
        vocabId: "station",
        answerKana: "えきはどこですか。",
        answerRomaji: "eki wa doko desu ka",
        answerGerman: "Wo ist der Bahnhof?",
        exampleJapanese: "駅はどこですか。",
        exampleKana: "えきはどこですか。",
        exampleGerman: "Wo ist der Bahnhof?",
        shortTip: "„〜はどこですか“ ist ein Grundausdruck, um nach einem Ort zu fragen.",
        detailTip:
          "„駅はどこですか“ ist ein natürlicher Ausdruck, um nach dem Bahnhof zu fragen. „は“ markiert das Thema, „どこですか“ bedeutet „wo ist …?“.",
      },
      {
        id: "reise-q6",
        type: "meaning-choice",
        categoryId: "reise",
        prompt: "右",
        instruction: "Wähle die richtige Bedeutung.",
        choices: ["rechts", "links", "nah", "weit"],
        answer: "rechts",
        vocabId: "right",
        exampleJapanese: "右です。",
        exampleKana: "みぎです。",
        exampleGerman: "Es ist rechts.",
        shortTip: "„右“ ist ein Grundwort für Richtungen.",
        detailTip:
          "„右です“ bedeutet „Es ist rechts“ und ist eine kurze Antwort bei einer Wegbeschreibung. Das kommt oft bei Wegfragen auf Reisen vor.",
      },
      {
        id: "reise-q7",
        type: "fill-blank",
        categoryId: "reise",
        prompt: "駅は____です。",
        instruction: "Ergänze: Der Bahnhof ist nah.",
        choices: ["近い", "遠い", "右", "左"],
        answer: "近い",
        vocabId: "near",
        exampleJapanese: "駅は近いです。",
        exampleKana: "えきはちかいです。",
        exampleGerman: "Der Bahnhof ist nah.",
        shortTip: "„近いです“ bedeutet, dass etwas nah ist.",
        detailTip:
          "„駅は近いです“ bedeutet, dass der Bahnhof nah ist. Das Gegenteil ist „遠いです“.",
      },
      {
        id: "reise-q8",
        type: "phrase-choice",
        categoryId: "reise",
        prompt: "Entschuldigung, wo ist die Toilette?",
        instruction: "Wähle den natürlichen japanischen Satz.",
        choices: [
          "すみません、トイレはどこですか。",
          "トイレを飲みます。",
          "駅に食べます。",
          "ホテルは右をください。",
        ],
        answer: "すみません、トイレはどこですか。",
        vocabId: "excuseMe",
        answerKana: "すみません、トイレはどこですか。",
        answerRomaji: "sumimasen, toire wa doko desu ka",
        answerGerman: "Entschuldigung, wo ist die Toilette?",
        exampleJapanese: "すみません、トイレはどこですか。",
        exampleKana: "すみません、トイレはどこですか。",
        exampleGerman: "Entschuldigung, wo ist die Toilette?",
        shortTip: "„すみません“ am Satzanfang macht eine Frage höflicher.",
        detailTip:
          "Bei einer Wegfrage benutzt man am Anfang oft „すみません“. „トイレはどこですか“ fragt nach einem Ort.",
      },
      {
        id: "reise-q9",
        type: "phrase-choice",
        categoryId: "reise",
        prompt: "The hotel is far away.",
        instruction: "Wähle den natürlichen japanischen Satz.",
        choices: [
          "ホテルは遠いです。",
          "ホテルは近いです。",
          "ホテルに食べます。",
          "電車をください。",
        ],
        answer: "ホテルは遠いです。",
        vocabId: "far",
        answerKana: "ホテルはとおいです。",
        answerRomaji: "hoteru wa tooi desu",
        answerGerman: "Das Hotel ist weit entfernt.",
        exampleJapanese: "ホテルは遠いです。",
        exampleKana: "ホテルはとおいです。",
        exampleGerman: "Das Hotel ist weit entfernt.",
        shortTip: "„遠いです“ bedeutet, dass etwas weit entfernt ist.",
        detailTip:
          "„ホテルは遠いです“ bedeutet, dass das Hotel weit entfernt ist. „近いです“ ist das Gegenteil.",
      },
      {
        id: "reise-challenge",
        type: "phrase-choice",
        categoryId: "reise",
        label: "Abschluss-Challenge",
        isChallenge: true,
        prompt: "Ich fahre mit dem Zug zum Hotel.",
        instruction: "Wähle den natürlichen japanischen Satz.",
        choices: [
          "電車でホテルに行きます。",
          "ホテルで電車に行きます。",
          "電車をホテルに行きます。",
          "トイレでホテルに行きます。",
        ],
        answer: "電車でホテルに行きます。",
        vocabId: "train",
        answerKana: "でんしゃでホテルにいきます。",
        answerRomaji: "densha de hoteru ni ikimasu",
        answerGerman: "Ich fahre mit dem Zug zum Hotel.",
        exampleJapanese: "電車でホテルに行きます。",
        exampleKana: "でんしゃでホテルにいきます。",
        exampleGerman: "Ich fahre mit dem Zug zum Hotel.",
        shortTip: "„電車で“ zeigt das Verkehrsmittel, „ホテルに“ zeigt das Ziel.",
        detailTip:
          "„電車でホテルに行きます“ verbindet Verkehrsmittel und Ziel in einem Satz. „で“ steht für das Verkehrsmittel, „に“ für das Ziel.",
      },
    ],
  },
  {
    id: "schule",
    name: "Schule",
    stageTitle: "Lernen und Alltag",
    description: "Sprich über Schule, Sprache und den heutigen Tag.",
    unlockLevel: 2,
    rewardXp: 100,
    collectedCardIds: [
      "school",
      "teacher",
      "japaneseLanguage",
      "study",
      "today",
    ],
    unlocksNext: "freunde",
    questions: [
      {
        id: "schule-q1",
        type: "meaning-choice",
        categoryId: "schule",
        prompt: "学校",
        instruction: "Wähle die richtige Bedeutung.",
        choices: ["Schule", "Lehrer/Lehrerin", "Japanisch", "heute"],
        answer: "Schule",
        vocabId: "school",
        exampleJapanese: "学校に行きます。",
        exampleKana: "がっこうにいきます。",
        exampleGerman: "Ich gehe zur Schule.",
      },
      {
        id: "schule-q2",
        type: "japanese-choice",
        categoryId: "schule",
        prompt: "lernen",
        instruction: "Wähle die passende Wortkarte.",
        choices: ["勉強する", "学校", "先生", "日本語"],
        answer: "勉強する",
        vocabId: "study",
        exampleJapanese: "日本語を勉強します。",
        exampleKana: "にほんごをべんきょうします。",
        exampleGerman: "Ich lerne Japanisch.",
      },
      {
        id: "schule-q3",
        type: "fill-blank",
        categoryId: "schule",
        prompt: "日本語を____。",
        instruction: "Ergänze den Satz.",
        choices: ["勉強します", "食べます", "飲みます", "行きます"],
        answer: "勉強します",
        vocabId: "study",
        exampleJapanese: "日本語を勉強します。",
        exampleKana: "にほんごをべんきょうします。",
        exampleGerman: "Ich lerne Japanisch.",
      },
      {
        id: "schule-q4",
        type: "phrase-choice",
        categoryId: "schule",
        prompt: "Ich lerne heute Japanisch.",
        instruction: "Wähle den natürlichen japanischen Satz.",
        choices: [
          "今日、日本語を勉強します。",
          "今日、学校に行きます。",
          "先生と日本語を話します。",
          "日本語が好きです。",
        ],
        answer: "今日、日本語を勉強します。",
        vocabId: "japaneseLanguage",
        answerKana: "きょう、にほんごをべんきょうします。",
        answerRomaji: "kyou, nihongo o benkyou shimasu",
        answerGerman: "Ich lerne heute Japanisch.",
        exampleJapanese: "今日、日本語を勉強します。",
        exampleKana: "きょう、にほんごをべんきょうします。",
        exampleGerman: "Ich lerne heute Japanisch.",
        shortTip: "Zeitwörter stehen oft am Satzanfang.",
        detailTip:
          "„今日“ steht meistens am Satzanfang. „今日、日本語を勉強します“ bedeutet „Ich lerne heute Japanisch“.",
      },
      {
        id: "schule-challenge",
        type: "phrase-choice",
        categoryId: "schule",
        label: "Abschluss-Challenge",
        isChallenge: true,
        prompt: "Heute gehe ich zur Schule und lerne Japanisch.",
        instruction: "Wähle den natürlichen japanischen Satz.",
        choices: [
          "今日、学校に行きます。日本語を勉強します。",
          "今日、先生に会います。",
          "学校で日本語を食べます。",
          "明日、日本語を勉強します。",
        ],
        answer: "今日、学校に行きます。日本語を勉強します。",
        answerKana: "きょう、がっこうにいきます。にほんごをべんきょうします。",
        answerRomaji:
          "kyou, gakkou ni ikimasu. nihongo o benkyou shimasu.",
        answerGerman: "Heute gehe ich zur Schule und lerne Japanisch.",
        exampleJapanese: "今日、学校に行きます。日本語を勉強します。",
        exampleKana: "きょう、がっこうにいきます。にほんごをべんきょうします。",
        exampleGerman: "Heute gehe ich zur Schule und lerne Japanisch.",
        shortTip: "Zwei kurze Sätze kann man einfach hintereinander sagen.",
        detailTip:
          "„今日、学校に行きます。日本語を勉強します。“ klingt natürlich, auch wenn man die Sätze einfach aneinanderreiht.",
      },
    ],
  },
  {
    id: "freunde",
    name: "Freunde",
    stageTitle: "Treffen und Pläne",
    description: "Sprich über Freunde und Pläne für morgen.",
    unlockLevel: 3,
    rewardXp: 110,
    collectedCardIds: ["friend", "meet", "talk", "tomorrow", "like"],
    unlocksNext: "review",
    questions: [
      {
        id: "freunde-q1",
        type: "meaning-choice",
        categoryId: "freunde",
        prompt: "友だち",
        instruction: "Wähle die richtige Bedeutung.",
        choices: ["Freund/Freundin", "treffen", "sprechen", "morgen"],
        answer: "Freund/Freundin",
        vocabId: "friend",
        exampleJapanese: "友だちに会います。",
        exampleKana: "ともだちにあいます。",
        exampleGerman: "Ich treffe einen Freund.",
      },
      {
        id: "freunde-q2",
        type: "japanese-choice",
        categoryId: "freunde",
        prompt: "treffen",
        instruction: "Wähle die passende Wortkarte.",
        choices: ["会う", "話す", "友だち", "明日"],
        answer: "会う",
        vocabId: "meet",
        exampleJapanese: "友だちに会います。",
        exampleKana: "ともだちにあいます。",
        exampleGerman: "Ich treffe einen Freund.",
      },
      {
        id: "freunde-q3",
        type: "fill-blank",
        categoryId: "freunde",
        prompt: "友だちと____。",
        instruction: "Ergänze den Satz.",
        choices: ["話します", "食べます", "飲みます", "行きます"],
        answer: "話します",
        vocabId: "talk",
        exampleJapanese: "友だちと話します。",
        exampleKana: "ともだちとはなします。",
        exampleGerman: "Ich spreche mit einem Freund.",
      },
      {
        id: "freunde-q4",
        type: "phrase-choice",
        categoryId: "freunde",
        prompt: "Morgen treffe ich einen Freund.",
        instruction: "Wähle den natürlichen japanischen Satz.",
        choices: [
          "明日、友だちに会います。",
          "今日、友だちに会います。",
          "明日、友だちと話します。",
          "友だちが好きです。",
        ],
        answer: "明日、友だちに会います。",
        vocabId: "tomorrow",
        answerKana: "あした、ともだちにあいます。",
        answerRomaji: "ashita, tomodachi ni aimasu",
        answerGerman: "Morgen treffe ich einen Freund.",
        exampleJapanese: "明日、友だちに会います。",
        exampleKana: "あした、ともだちにあいます。",
        exampleGerman: "Morgen treffe ich einen Freund.",
        shortTip: "„明日“ benutzt man für zukünftige Pläne.",
        detailTip:
          "„明日、友だちに会います“ bedeutet „Morgen treffe ich einen Freund“. Achte auf den Unterschied zu „今日“.",
      },
      {
        id: "freunde-challenge",
        type: "phrase-choice",
        categoryId: "freunde",
        label: "Abschluss-Challenge",
        isChallenge: true,
        prompt: "Ich mag meinen Freund. Morgen treffe ich ihn.",
        instruction: "Wähle den natürlichen japanischen Satz.",
        choices: [
          "友だちが好きです。明日、会います。",
          "友だちが好きです。今日、話します。",
          "先生が好きです。明日、会います。",
          "友だちと話します。今日、会います。",
        ],
        answer: "友だちが好きです。明日、会います。",
        answerKana: "ともだちがすきです。あした、あいます。",
        answerRomaji: "tomodachi ga suki desu. ashita, aimasu.",
        answerGerman: "Ich mag meinen Freund. Morgen treffe ich ihn.",
        exampleJapanese: "友だちが好きです。明日、会います。",
        exampleKana: "ともだちがすきです。あした、あいます。",
        exampleGerman: "Ich mag meinen Freund. Morgen treffe ich ihn.",
        shortTip: "Bei „好き“ benutzt man „が“ für das, was man mag.",
        detailTip:
          "„が“ in „友だちが好きです“ zeigt, wen man mag. „明日、会います“ beschreibt einen zukünftigen Plan.",
      },
    ],
  },
  {
    id: "review",
    name: "Abschluss-Review",
    stageTitle: "Alles zusammen",
    description: "Wiederhole Wörter aus allen Kategorien.",
    unlockLevel: 4,
    rewardXp: 150,
    collectedCardIds: [],
    isReview: true,
    questions: [
      {
        id: "review-q1",
        type: "meaning-choice",
        categoryId: "review",
        prompt: "水",
        instruction: "Wähle die richtige Bedeutung.",
        choices: ["Wasser", "Kaffee", "Brot", "Bahnhof"],
        answer: "Wasser",
        vocabId: "water",
        exampleJapanese: "水をください。",
        exampleKana: "みずをください。",
        exampleGerman: "Wasser bitte.",
      },
      {
        id: "review-q2",
        type: "japanese-choice",
        categoryId: "review",
        prompt: "Schule",
        instruction: "Wähle die passende Wortkarte.",
        choices: ["学校", "駅", "友だち", "パン"],
        answer: "学校",
        vocabId: "school",
        exampleJapanese: "学校に行きます。",
        exampleKana: "がっこうにいきます。",
        exampleGerman: "Ich gehe zur Schule.",
      },
      {
        id: "review-q3",
        type: "fill-blank",
        categoryId: "review",
        prompt: "友だちに____。",
        instruction: "Ergänze den Satz.",
        choices: ["会います", "食べます", "飲みます", "行きます"],
        answer: "会います",
        vocabId: "meet",
        exampleJapanese: "友だちに会います。",
        exampleKana: "ともだちにあいます。",
        exampleGerman: "Ich treffe einen Freund.",
      },
      {
        id: "review-q4",
        type: "phrase-choice",
        categoryId: "review",
        prompt: "Wasser bitte.",
        instruction: "Wähle den natürlichen japanischen Satz.",
        choices: [
          "水をください。",
          "水を飲みます。",
          "パンをください。",
          "コーヒーを飲みます。",
        ],
        answer: "水をください。",
        vocabId: "water",
        answerKana: "みずをください。",
        answerRomaji: "mizu o kudasai",
        answerGerman: "Wasser bitte.",
        exampleJapanese: "水をください。",
        exampleKana: "みずをください。",
        exampleGerman: "Wasser bitte.",
      },
      {
        id: "review-challenge",
        type: "phrase-choice",
        categoryId: "review",
        label: "Abschluss-Challenge",
        isChallenge: true,
        prompt: "Morgen gehe ich zur Schule und treffe einen Freund.",
        instruction: "Wähle den natürlichen japanischen Satz.",
        choices: [
          "明日、学校に行きます。友だちに会います。",
          "今日、学校に行きます。友だちに会います。",
          "明日、駅に行きます。先生に会います。",
          "明日、学校に行きます。パンを食べます。",
        ],
        answer: "明日、学校に行きます。友だちに会います。",
        answerKana: "あした、がっこうにいきます。ともだちにあいます。",
        answerRomaji:
          "ashita, gakkou ni ikimasu. tomodachi ni aimasu.",
        answerGerman: "Morgen gehe ich zur Schule und treffe einen Freund.",
        exampleJapanese: "明日、学校に行きます。友だちに会います。",
        exampleKana: "あした、がっこうにいきます。ともだちにあいます。",
        exampleGerman: "Morgen gehe ich zur Schule und treffe einen Freund.",
        shortTip: "Dieses Abschluss-Review kombiniert Wörter aus allen Kategorien.",
        detailTip:
          "„明日、学校に行きます。友だちに会います。“ verbindet Ausdrücke aus Reise, Schule und Freunde.",
      },
    ],
  },
];

export function getQuestCategory(id: CategoryId): QuestCategory | undefined {
  return questCategories.find((category) => category.id === id);
}
