import type { CategoryId, VocabItem } from "@/types/learning";

export const vocabData: VocabItem[] = [
  // --- Café ---
  {
    id: "coffee",
    kanji: "コーヒー",
    kana: "コーヒー",
    romaji: "koohii",
    german: "Kaffee",
    categoryId: "cafe",
    stage: 0,
    unlockLevel: 0,
    xpReward: 10,
    rarity: "common",
    exampleJapanese: "コーヒーをください。",
    exampleKana: "コーヒーをください。",
    exampleGerman: "Einen Kaffee bitte.",
    commonExamples: [
      "コーヒーをください。",
      "コーヒーを飲みます。",
      "ホットコーヒーをください。",
    ],
    commonPatterns: ["〜をください", "〜を飲みます"],
    relatedExpressions: ["アイスコーヒー", "ホットコーヒー", "コーヒーください"],
    shortTip: "„コーヒーをください“ ist dein Standardsatz, um einen Kaffee zu bestellen.",
    detailTip:
      "Im Café sagst du einfach [Ding] + „をください“ – das ist die sichere Bestellform, egal was du willst. „コーヒーをください“ heißt „Einen Kaffee bitte“. Kurz und locker geht auch „コーヒーください“. Merk dir „ください“ als dein Zauberwort zum Bestellen.",
    relatedVocabIds: ["drink", "water", "bread"],
  },
  {
    id: "water",
    kanji: "水",
    kana: "みず",
    romaji: "mizu",
    german: "Wasser",
    categoryId: "cafe",
    stage: 0,
    unlockLevel: 0,
    xpReward: 10,
    rarity: "common",
    exampleJapanese: "水をください。",
    exampleKana: "みずをください。",
    exampleGerman: "Wasser bitte.",
    commonExamples: ["水をください。", "水を飲みます。", "冷たい水をください。"],
    commonPatterns: ["〜をください", "〜を飲みます"],
    relatedExpressions: ["冷たい水", "水ください", "水を飲む"],
    shortTip: "„〜をください“ ist dein sicherer Standardsatz zum Bestellen.",
    detailTip:
      "Wenn du in Japan etwas bestellen willst, ist „〜をください“ die einfachste sichere Form. Setze einfach das Ding davor: 水をください = Wasser bitte. Das klingt höflich genug für Cafés und Läden. Nicht verwechseln: „水を飲みます“ heißt „Ich trinke Wasser“, nicht „Wasser bitte“ – das eine ist eine Bestellung, das andere eine Beschreibung.",
    relatedVocabIds: ["drink", "coffee", "bread"],
  },
  {
    id: "bread",
    kanji: "パン",
    kana: "パン",
    romaji: "pan",
    german: "Brot",
    categoryId: "cafe",
    stage: 0,
    unlockLevel: 0,
    xpReward: 10,
    rarity: "common",
    exampleJapanese: "パンをください。",
    exampleKana: "パンをください。",
    exampleGerman: "Brot bitte.",
    commonExamples: ["パンをください。", "パンを食べます。", "パンが好きです。"],
    commonPatterns: ["〜をください", "〜を食べます"],
    relatedExpressions: ["朝ごはん", "パンください", "パンを食べる"],
    shortTip: "„パン“ klingt fast wie das deutsche Wort – und bedeutet genau dasselbe.",
    detailTip:
      "„パン“ kommt ursprünglich aus dem Portugiesischen und wird ähnlich wie im Deutschen ausgesprochen, daher leicht zu merken. „パンをください“ bestellt Brot, „パンを食べます“ beschreibt nur, dass du Brot isst. Das „を“ zeigt jeweils, worum es geht. Achte auf den Unterschied: Bestellung vs. Handlung.",
    relatedVocabIds: ["eat", "coffee", "water"],
  },
  {
    id: "drink",
    kanji: "飲む",
    kana: "のむ",
    romaji: "nomu",
    german: "trinken",
    categoryId: "cafe",
    stage: 0,
    unlockLevel: 0,
    xpReward: 10,
    rarity: "common",
    exampleJapanese: "水を飲みます。",
    exampleKana: "みずをのみます。",
    exampleGerman: "Ich trinke Wasser.",
    commonExamples: ["水を飲みます。", "コーヒーを飲みます。", "お茶を飲みます。"],
    commonPatterns: ["〜を飲みます", "〜をください"],
    relatedExpressions: ["水を飲む", "コーヒーを飲む", "飲みます"],
    shortTip: "„飲みます“ benutzt du für alles, was du trinkst – Wasser, Kaffee, Tee.",
    detailTip:
      "„飲む“ ist das Verb für „trinken“, höflich „飲みます“. Das Muster ist immer gleich: [Getränk] + を + 飲みます, z. B. 水を飲みます = Ich trinke Wasser. Anders als im Deutschen steht das Verb im Japanischen immer am Satzende. Verwechsle es nicht mit „食べます“ – das ist für Essen, nicht für Getränke.",
    relatedVocabIds: ["water", "coffee", "eat"],
  },
  {
    id: "eat",
    kanji: "食べる",
    kana: "たべる",
    romaji: "taberu",
    german: "essen",
    categoryId: "cafe",
    stage: 0,
    unlockLevel: 0,
    xpReward: 10,
    rarity: "common",
    exampleJapanese: "パンを食べます。",
    exampleKana: "パンをたべます。",
    exampleGerman: "Ich esse Brot.",
    commonExamples: ["パンを食べます。", "ごはんを食べます。", "朝ごはんを食べます。"],
    commonPatterns: ["〜を食べます", "ごはんを食べる"],
    relatedExpressions: ["パンを食べる", "朝ごはん", "食べます"],
    shortTip: "„食べます“ ist dein Verb für alles, was du isst.",
    detailTip:
      "„食べる“ heißt „essen“, höflich „食べます“. Das Muster [Essen] + を + 食べます funktioniert immer: パンを食べます = Ich esse Brot. Getränke bekommen „飲みます“, feste Nahrung „食べます“ – eine der ersten Unterscheidungen, die Anfänger lernen. Merk dir: „を“ zeigt das Objekt, das Verb kommt zuletzt.",
    relatedVocabIds: ["bread", "drink", "coffee"],
  },

  // --- Reise ---
  {
    id: "station",
    kanji: "駅",
    kana: "えき",
    romaji: "eki",
    german: "Bahnhof",
    categoryId: "reise",
    stage: 1,
    unlockLevel: 1,
    xpReward: 10,
    rarity: "common",
    exampleJapanese: "駅はどこですか。",
    exampleKana: "えきはどこですか。",
    exampleGerman: "Wo ist der Bahnhof?",
    commonExamples: ["駅はどこですか。", "駅に行きます。"],
    commonPatterns: ["〜はどこですか", "〜に行きます"],
    relatedExpressions: ["駅まで", "駅の前"],
    shortTip: "„駅はどこですか“ ist deine Rettung, wenn du den Bahnhof suchst.",
    detailTip:
      "„駅“ heißt „Bahnhof“ und ist eines der wichtigsten Reisewörter überhaupt. Das Muster „〜はどこですか“ bedeutet „Wo ist …?“ und funktioniert für jeden Ort: ホテルはどこですか, トイレはどこですか. Ein häufiger Fehler ist, das „は“ wegzulassen – ohne „は“ klingt der Satz unvollständig. Mit diesem einen Muster findest du fast alles.",
    relatedVocabIds: ["where", "excuseMe", "train", "right", "left", "near", "far"],
  },
  {
    id: "hotel",
    kanji: "ホテル",
    kana: "ホテル",
    romaji: "hoteru",
    german: "Hotel",
    categoryId: "reise",
    stage: 1,
    unlockLevel: 1,
    xpReward: 10,
    rarity: "common",
    exampleJapanese: "ホテルに行きます。",
    exampleKana: "ホテルにいきます。",
    exampleGerman: "Ich gehe zum Hotel.",
    commonExamples: ["ホテルに行きます。", "ホテルはどこですか。"],
    commonPatterns: ["〜に行きます", "〜はどこですか"],
    relatedExpressions: ["ホテルの部屋", "ホテルまで"],
    shortTip: "„ホテル“ ist ein Fremdwort – klingt fast wie im Deutschen.",
    detailTip:
      "„ホテル“ kommt aus dem Englischen und wird genauso benutzt wie im Deutschen, deshalb ist es leicht zu merken. „ホテルに行きます“ heißt „Ich gehe zum Hotel“ – „に“ markiert hier das Ziel. Ein typischer Fehler ist, „で“ statt „に“ zu benutzen; „で“ ist für das Verkehrsmittel, nicht das Ziel. Merk dir das Paar: 電車で (womit) + ホテルに (wohin).",
    relatedVocabIds: ["go", "train", "where", "near", "far"],
  },
  {
    id: "train",
    kanji: "電車",
    kana: "でんしゃ",
    romaji: "densha",
    german: "Zug",
    categoryId: "reise",
    stage: 1,
    unlockLevel: 1,
    xpReward: 10,
    rarity: "common",
    exampleJapanese: "電車で行きます。",
    exampleKana: "でんしゃでいきます。",
    exampleGerman: "Ich fahre mit dem Zug.",
    commonExamples: ["電車で行きます。", "電車に乗ります。"],
    commonPatterns: ["〜で行きます", "〜に乗ります"],
    relatedExpressions: ["電車の中", "電車を降ります"],
    shortTip: "„で“ zeigt hier, womit du dich bewegst: Zug, Bus oder Auto.",
    detailTip:
      "In „電車で行きます“ bedeutet „電車で“ ungefähr „mit dem Zug“. Das Muster ist sehr nützlich: 乗り物 + で + 行きます. Du kannst es austauschen: バスで行きます = Ich fahre mit dem Bus. Wichtig: Für das Ziel benutzt du nicht „で“, sondern „に“, z. B. ホテルに行きます.",
    relatedVocabIds: ["go", "station", "hotel"],
  },
  {
    id: "toilet",
    kanji: "トイレ",
    kana: "トイレ",
    romaji: "toire",
    german: "Toilette",
    categoryId: "reise",
    stage: 1,
    unlockLevel: 1,
    xpReward: 10,
    rarity: "common",
    exampleJapanese: "トイレはどこですか。",
    exampleKana: "トイレはどこですか。",
    exampleGerman: "Wo ist die Toilette?",
    commonExamples: ["トイレはどこですか。"],
    commonPatterns: ["〜はどこですか"],
    relatedExpressions: ["トイレを借ります"],
    shortTip: "„トイレはどこですか“ – vielleicht der nützlichste Satz auf jeder Reise.",
    detailTip:
      "„トイレ“ kommt aus dem Englischen „toilet“ und wird ähnlich ausgesprochen. Mit „トイレはどこですか“ fragst du höflich nach der Toilette – das gleiche Muster wie bei „駅はどこですか“. Für noch mehr Höflichkeit stellst du „すみません“ voran: すみません、トイレはどこですか。 Diesen Satz solltest du als Ersten auswendig lernen.",
    relatedVocabIds: ["where", "excuseMe", "station"],
  },
  {
    id: "go",
    kanji: "行く",
    kana: "いく",
    romaji: "iku",
    german: "gehen",
    categoryId: "reise",
    stage: 1,
    unlockLevel: 1,
    xpReward: 10,
    rarity: "common",
    exampleJapanese: "ホテルに行きます。",
    exampleKana: "ホテルにいきます。",
    exampleGerman: "Ich gehe zum Hotel.",
    commonExamples: ["ホテルに行きます。", "駅に行きます。"],
    commonPatterns: ["〜に行きます"],
    relatedExpressions: ["行きます", "行く"],
    shortTip: "„〜に行きます“ zeigt, wohin du gehst oder fährst.",
    detailTip:
      "„行く“ heißt „gehen“, höflich „行きます“. Das Ziel bekommt immer „に“: ホテルに行きます = Ich gehe zum Hotel. Ein häufiger Fehler ist, hier „で“ statt „に“ zu benutzen – „で“ ist für das Verkehrsmittel reserviert. Eselsbrücke: „に“ zeigt wie ein Pfeil auf den Ort, wo du hinwillst.",
    relatedVocabIds: ["hotel", "station", "train"],
  },
  {
    id: "where",
    kanji: "どこ",
    kana: "どこ",
    romaji: "doko",
    german: "wo",
    categoryId: "reise",
    stage: 1,
    unlockLevel: 1,
    xpReward: 10,
    rarity: "common",
    exampleJapanese: "駅はどこですか。",
    exampleKana: "えきはどこですか。",
    exampleGerman: "Wo ist der Bahnhof?",
    commonExamples: ["駅はどこですか。", "トイレはどこですか。", "ホテルはどこですか。"],
    commonPatterns: ["〜はどこですか"],
    relatedExpressions: ["どこですか", "どこ"],
    shortTip: "„どこですか“ ist dein Werkzeug, um nach jedem Ort zu fragen.",
    detailTip:
      "„どこ“ bedeutet „wo“, und zusammen mit „ですか“ wird daraus eine höfliche Frage. Das Muster [Ort] + はどこですか funktioniert universell: 駅はどこですか, ホテルはどこですか. Vergiss das „は“ nicht – es verbindet den Ort mit der Frage. Wenn du dir nur einen Reisesatz merkst, dann diesen.",
    relatedVocabIds: ["station", "toilet", "hotel", "excuseMe"],
  },
  {
    id: "excuseMe",
    kanji: "すみません",
    kana: "すみません",
    romaji: "sumimasen",
    german: "Entschuldigung",
    categoryId: "reise",
    stage: 1,
    unlockLevel: 1,
    xpReward: 10,
    rarity: "common",
    exampleJapanese: "すみません、駅はどこですか。",
    exampleKana: "すみません、えきはどこですか。",
    exampleGerman: "Entschuldigung, wo ist der Bahnhof?",
    commonExamples: ["すみません、駅はどこですか。", "すみません、トイレはどこですか。"],
    commonPatterns: ["すみません、〜"],
    relatedExpressions: ["すみません"],
    shortTip: "„すみません“ ist deine Türöffner-Floskel, bevor du jemanden ansprichst.",
    detailTip:
      "„すみません“ bedeutet „Entschuldigung“ und wird benutzt, um höflich ein Gespräch zu beginnen – ähnlich wie „Entschuldigen Sie“ im Deutschen. Vor einer Wegfrage klingt es automatisch freundlicher: すみません、駅はどこですか。 Du kannst es auch allein benutzen, um dich zu entschuldigen oder Aufmerksamkeit zu bekommen. Ein Wort, unzählige Situationen.",
    relatedVocabIds: ["where", "toilet", "station"],
  },
  {
    id: "right",
    kanji: "右",
    kana: "みぎ",
    romaji: "migi",
    german: "rechts",
    categoryId: "reise",
    stage: 1,
    unlockLevel: 1,
    xpReward: 10,
    rarity: "common",
    exampleJapanese: "右です。",
    exampleKana: "みぎです。",
    exampleGerman: "Es ist rechts.",
    commonExamples: ["右です。", "右に行きます。"],
    commonPatterns: ["〜です", "右に〜"],
    relatedExpressions: ["右側", "右に曲がります"],
    shortTip: "„右です“ ist deine kurze Antwort, wenn jemand nach dem Weg fragt.",
    detailTip:
      "„右“ bedeutet „rechts“. Mit „です“ dahinter wird daraus eine vollständige, höfliche Antwort: 右です = Es ist rechts. Das gleiche Muster gilt für „左です“ (links). Bei Wegbeschreibungen reicht oft schon dieses eine Wort plus „です“.",
    relatedVocabIds: ["left", "near", "far", "station"],
  },
  {
    id: "left",
    kanji: "左",
    kana: "ひだり",
    romaji: "hidari",
    german: "links",
    categoryId: "reise",
    stage: 1,
    unlockLevel: 1,
    xpReward: 10,
    rarity: "common",
    exampleJapanese: "左です。",
    exampleKana: "ひだりです。",
    exampleGerman: "Es ist links.",
    commonExamples: ["左です。", "左に行きます。"],
    commonPatterns: ["〜です", "左に〜"],
    relatedExpressions: ["左側", "左に曲がります"],
    shortTip: "„左です“ ist das Gegenstück zu „右です“ – links statt rechts.",
    detailTip:
      "„左“ heißt „links“, genau wie „右“ für „rechts“ steht. Mit „です“ wird daraus eine kurze, höfliche Antwort: 左です = Es ist links. Ein guter Trick, um beide nicht zu verwechseln: lerne sie immer als Paar. Übe beide zusammen, dann sitzen sie schneller.",
    relatedVocabIds: ["right", "near", "far", "station"],
  },
  {
    id: "near",
    kanji: "近い",
    kana: "ちかい",
    romaji: "chikai",
    german: "nah",
    categoryId: "reise",
    stage: 1,
    unlockLevel: 1,
    xpReward: 10,
    rarity: "common",
    exampleJapanese: "駅は近いです。",
    exampleKana: "えきはちかいです。",
    exampleGerman: "Der Bahnhof ist nah.",
    commonExamples: ["駅は近いです。", "ホテルは近いです。"],
    commonPatterns: ["〜は近いです"],
    relatedExpressions: ["近くに", "近い"],
    shortTip: "„近いです“ sagt: das ist nicht weit von hier.",
    detailTip:
      "„近い“ bedeutet „nah“, und mit „です“ wird es zur höflichen Aussage: 駅は近いです = Der Bahnhof ist nah. Das Gegenteil ist „遠いです“ (weit entfernt) – lerne beide Wörter als Paar. Das Muster [Ort] + は近いです funktioniert für jeden Ort. Praktisch, um schnell einzuschätzen, ob sich ein Fußweg lohnt.",
    relatedVocabIds: ["far", "right", "left", "station", "hotel"],
  },
  {
    id: "far",
    kanji: "遠い",
    kana: "とおい",
    romaji: "tooi",
    german: "weit / entfernt",
    categoryId: "reise",
    stage: 1,
    unlockLevel: 1,
    xpReward: 10,
    rarity: "common",
    exampleJapanese: "ホテルは遠いです。",
    exampleKana: "ホテルはとおいです。",
    exampleGerman: "Das Hotel ist weit entfernt.",
    commonExamples: ["ホテルは遠いです。", "駅は遠いです。"],
    commonPatterns: ["〜は遠いです"],
    relatedExpressions: ["遠くに", "遠い"],
    shortTip: "„遠いです“ sagt: das ist ein ganzes Stück entfernt.",
    detailTip:
      "„遠い“ bedeutet „weit“ oder „entfernt“, mit „です“ höflich als Aussage: ホテルは遠いです = Das Hotel ist weit entfernt. Es ist das Gegenteil von „近い“ (nah) – lerne beide zusammen als Paar. Diese Info hilft dir zu entscheiden, ob du lieber ein Taxi oder den Zug nimmst. Ein einfaches Wort mit großer praktischer Wirkung.",
    relatedVocabIds: ["near", "right", "left", "station", "hotel"],
  },

  // --- Schule ---
  {
    id: "school",
    kanji: "学校",
    kana: "がっこう",
    romaji: "gakkou",
    german: "Schule",
    categoryId: "schule",
    stage: 2,
    unlockLevel: 2,
    xpReward: 10,
    rarity: "common",
    exampleJapanese: "学校に行きます。",
    exampleKana: "がっこうにいきます。",
    exampleGerman: "Ich gehe zur Schule.",
    commonExamples: ["学校に行きます。"],
    commonPatterns: ["〜に行きます"],
    relatedExpressions: ["学校の後で"],
    shortTip: "„学校“ ist dein Grundwort für alles rund ums Lernen.",
    detailTip:
      "„学校“ bedeutet „Schule“. Mit „学校に行きます“ sagst du „Ich gehe zur Schule“ – „に“ zeigt hier das Ziel. Mit „学校で勉強します“ sagst du „Ich lerne in der Schule“ – „で“ zeigt den Ort der Handlung. Ein häufiger Anfängerfehler ist, „に“ und „で“ zu vertauschen. Am besten lernst du beide Sätze als Paar: 学校に行きます (wohin) und 学校で勉強します (wo).",
    relatedVocabIds: ["teacher", "study", "today", "japaneseLanguage"],
    usageExamples: [
      {
        id: "school-going-today-casual",
        japanese: "今日は学校に行く。",
        kana: "きょうはがっこうにいく。",
        romaji: "kyou wa gakkou ni iku",
        german: "Heute gehe ich zur Schule.",
        register: "casual",
        suitableFor: ["friend", "family", "classmate"],
        contextGerman: "Du sprichst locker mit einem Freund oder Mitschüler.",
        noteGerman: "Die einfache Form „行く“ ohne „です/ます“ klingt unter Freunden ganz normal.",
        contrastGroup: "school-going-today",
      },
      {
        id: "school-going-today-polite",
        japanese: "今日は学校に行きます。",
        kana: "きょうはがっこうにいきます。",
        romaji: "kyou wa gakkou ni ikimasu",
        german: "Heute gehe ich zur Schule.",
        register: "polite",
        suitableFor: ["teacher", "stranger", "work"],
        contextGerman:
          "Du sprichst höflich mit einer Lehrkraft oder einer weniger vertrauten Person.",
        noteGerman: "Die „-masu“-Form ist die sichere Wahl, wenn du dir nicht sicher bist.",
        contrastGroup: "school-going-today",
      },
    ],
  },
  {
    id: "teacher",
    kanji: "先生",
    kana: "せんせい",
    romaji: "sensei",
    german: "Lehrer/Lehrerin",
    categoryId: "schule",
    stage: 2,
    unlockLevel: 2,
    xpReward: 10,
    rarity: "common",
    exampleJapanese: "先生に聞きます。",
    exampleKana: "せんせいにききます。",
    exampleGerman: "Ich frage den Lehrer.",
    commonExamples: ["先生に聞きます。"],
    commonPatterns: ["〜に聞きます"],
    relatedExpressions: ["先生、質問があります"],
    shortTip: "„先生“ ist eine höfliche Anrede – nicht nur für Lehrer.",
    detailTip:
      "„先生“ bedeutet „Lehrer“ oder „Lehrerin“. In Japan wird das Wort auch für andere Berufe mit Respekt benutzt, zum Beispiel für Ärztinnen und Ärzte. Als Anfänger merkst du dir „先生“ am einfachsten als „Lehrer/Lehrerin“. Wichtig: Du nennst dich selbst nie „先生“ – das Wort ist eine Anrede für andere, nicht für dich.",
    relatedVocabIds: ["school", "study", "japaneseLanguage"],
    usageExamples: [
      {
        id: "study-with-teacher-casual",
        japanese: "先生と日本語を勉強する。",
        kana: "せんせいとにほんごをべんきょうする。",
        romaji: "sensei to nihongo o benkyou suru",
        german: "Ich lerne mit der Lehrkraft Japanisch.",
        register: "casual",
        suitableFor: ["friend", "family", "classmate"],
        contextGerman: "Du erzählst einem Freund locker davon, dass du mit der Lehrkraft lernst.",
        noteGerman:
          "Diese lockere Form richtet sich an einen Freund, nicht an die Lehrkraft selbst.",
        contrastGroup: "study-with-teacher",
      },
      {
        id: "study-with-teacher-polite",
        japanese: "先生と日本語を勉強します。",
        kana: "せんせいとにほんごをべんきょうします。",
        romaji: "sensei to nihongo o benkyou shimasu",
        german: "Ich lerne mit der Lehrkraft Japanisch.",
        register: "polite",
        suitableFor: ["teacher", "stranger", "work"],
        contextGerman:
          "Du sprichst höflich darüber – zum Beispiel mit der Lehrkraft selbst oder in einer offiziellen Situation.",
        noteGerman: "Mit „-masu“ ist die Aussage auch für die Lehrkraft selbst passend.",
        contrastGroup: "study-with-teacher",
      },
    ],
  },
  {
    id: "japaneseLanguage",
    kanji: "日本語",
    kana: "にほんご",
    romaji: "nihongo",
    german: "Japanisch",
    categoryId: "schule",
    stage: 2,
    unlockLevel: 2,
    xpReward: 10,
    rarity: "common",
    exampleJapanese: "日本語を勉強します。",
    exampleKana: "にほんごをべんきょうします。",
    exampleGerman: "Ich lerne Japanisch.",
    commonExamples: ["日本語を勉強します。"],
    commonPatterns: ["〜を勉強します"],
    relatedExpressions: ["日本語が好きです"],
    shortTip: "„日本語“ ist die Sprache, „日本“ ist das Land.",
    detailTip:
      "„日本語“ bedeutet „Japanisch“ bzw. „die japanische Sprache“. Mit „日本語を勉強します“ sagst du „Ich lerne Japanisch“, mit „日本語が好きです“ sagst du „Ich mag Japanisch“. Verwechsle „日本“ (Japan, das Land) nicht mit „日本語“ (Japanisch, die Sprache) – das „語“ am Ende steht für „Sprache“ und taucht bei vielen Sprachnamen auf.",
    relatedVocabIds: ["study", "school", "teacher", "today"],
    usageExamples: [
      {
        id: "like-japanese-casual",
        japanese: "日本語が好き。",
        kana: "にほんごがすき。",
        romaji: "nihongo ga suki",
        german: "Ich mag Japanisch.",
        register: "casual",
        suitableFor: ["friend", "family", "classmate"],
        contextGerman: "Du sprichst locker mit einem Freund oder einer Freundin.",
        noteGerman: "Ohne „です“ klingt „好き“ unter Freunden natürlich und nicht abgehackt.",
        contrastGroup: "like-japanese",
      },
      {
        id: "like-japanese-polite",
        japanese: "日本語が好きです。",
        kana: "にほんごがすきです。",
        romaji: "nihongo ga suki desu",
        german: "Ich mag Japanisch.",
        register: "polite",
        suitableFor: ["teacher", "stranger", "work"],
        contextGerman: "Du sprichst höflich, zum Beispiel mit einer neuen Bekanntschaft.",
        noteGerman: "„です“ macht aus der Aussage eine höfliche, vollständige Antwort.",
        contrastGroup: "like-japanese",
      },
    ],
  },
  {
    id: "study",
    kanji: "勉強する",
    kana: "べんきょうする",
    romaji: "benkyou suru",
    german: "lernen",
    categoryId: "schule",
    stage: 2,
    unlockLevel: 2,
    xpReward: 10,
    rarity: "common",
    exampleJapanese: "日本語を勉強します。",
    exampleKana: "にほんごをべんきょうします。",
    exampleGerman: "Ich lerne Japanisch.",
    commonExamples: ["日本語を勉強します。"],
    commonPatterns: ["〜を勉強します"],
    relatedExpressions: ["勉強します"],
    shortTip: "„勉強する“ heißt „lernen“ – die höfliche Form ist „勉強します“.",
    detailTip:
      "„勉強する“ bedeutet „lernen“ oder „studieren“, höflich „勉強します“. Das Muster ist immer [Fach/Sprache] + を + 勉強します: 日本語を勉強します = Ich lerne Japanisch, 学校で勉強します = Ich lerne in der Schule. Anders als im Deutschen brauchst du für das Lernobjekt immer „を“ – nicht einfach nur das Wort direkt vor dem Verb.",
    relatedVocabIds: ["japaneseLanguage", "school", "teacher", "today"],
    usageExamples: [
      {
        id: "study-japanese-casual",
        japanese: "日本語を勉強する。",
        kana: "にほんごをべんきょうする。",
        romaji: "nihongo o benkyou suru",
        german: "Ich lerne Japanisch.",
        register: "casual",
        suitableFor: ["friend", "family", "classmate"],
        contextGerman: "Du sprichst locker mit einem Freund oder Familienmitglied.",
        noteGerman: "„勉強する“ ohne „-masu“ ist die Wörterbuchform, typisch im lockeren Gespräch.",
        contrastGroup: "study-japanese",
      },
      {
        id: "study-japanese-polite",
        japanese: "日本語を勉強します。",
        kana: "にほんごをべんきょうします。",
        romaji: "nihongo o benkyou shimasu",
        german: "Ich lerne Japanisch.",
        register: "polite",
        suitableFor: ["teacher", "stranger", "work"],
        contextGerman: "Du sprichst höflich, zum Beispiel mit einer Lehrkraft.",
        noteGerman: "„勉強します“ ist die sichere Form für Gespräche außerhalb des Freundeskreises.",
        contrastGroup: "study-japanese",
      },
    ],
  },
  {
    id: "today",
    kanji: "今日",
    kana: "きょう",
    romaji: "kyou",
    german: "heute",
    categoryId: "schule",
    stage: 2,
    unlockLevel: 2,
    xpReward: 10,
    rarity: "common",
    exampleJapanese: "今日、学校に行きます。",
    exampleKana: "きょう、がっこうにいきます。",
    exampleGerman: "Heute gehe ich zur Schule.",
    commonExamples: ["今日、学校に行きます。"],
    commonPatterns: ["今日、〜"],
    relatedExpressions: ["今日は"],
    shortTip: "„今日“ steht fast immer am Satzanfang, oft mit „は“.",
    detailTip:
      "„今日“ bedeutet „heute“, gesprochen „きょう“. Meistens steht es ganz am Satzanfang: 今日は学校に行きます = Heute gehe ich zur Schule, 今日、日本語を勉強します = Heute lerne ich Japanisch. Das „は“ nach „今日“ wird „wa“ ausgesprochen, nicht „ha“ – ein klassischer Stolperstein für Anfänger, den du dir am besten sofort einprägst.",
    relatedVocabIds: ["study", "school", "japaneseLanguage"],
    usageExamples: [
      {
        id: "study-today-casual",
        japanese: "今日は学校で勉強する。",
        kana: "きょうはがっこうでべんきょうする。",
        romaji: "kyou wa gakkou de benkyou suru",
        german: "Heute lerne ich in der Schule.",
        register: "casual",
        suitableFor: ["friend", "family", "classmate"],
        contextGerman: "Du erzählst einem Freund locker von deinem Tag.",
        noteGerman: "Für den lockeren Plausch reicht die einfache Form ohne „です/ます“.",
        contrastGroup: "study-today",
      },
      {
        id: "study-today-polite",
        japanese: "今日は学校で勉強します。",
        kana: "きょうはがっこうでべんきょうします。",
        romaji: "kyou wa gakkou de benkyou shimasu",
        german: "Heute lerne ich in der Schule.",
        register: "polite",
        suitableFor: ["teacher", "stranger", "work"],
        contextGerman: "Du sprichst höflich, zum Beispiel mit einer Lehrkraft oder in der Schule.",
        noteGerman: "Die „-masu“-Form passt zu jeder formelleren oder unbekannten Situation.",
        contrastGroup: "study-today",
      },
    ],
  },

  // --- Freunde ---
  {
    id: "friend",
    kanji: "友だち",
    kana: "ともだち",
    romaji: "tomodachi",
    german: "Freund/Freundin",
    categoryId: "freunde",
    stage: 3,
    unlockLevel: 3,
    xpReward: 10,
    rarity: "common",
    exampleJapanese: "友だちに会います。",
    exampleKana: "ともだちにあいます。",
    exampleGerman: "Ich treffe einen Freund.",
    commonExamples: ["友だちに会います。"],
    commonPatterns: ["〜に会います"],
    relatedExpressions: ["友だちと話す"],
    shortTip: "„友だち“ ist ein häufiges Wort im Alltag.",
    detailTip: "„友だちに会います“ bedeutet „Ich treffe einen Freund“.",
    relatedVocabIds: ["meet", "talk", "tomorrow", "like"],
  },
  {
    id: "meet",
    kanji: "会う",
    kana: "あう",
    romaji: "au",
    german: "treffen",
    categoryId: "freunde",
    stage: 3,
    unlockLevel: 3,
    xpReward: 10,
    rarity: "common",
    exampleJapanese: "友だちに会います。",
    exampleKana: "ともだちにあいます。",
    exampleGerman: "Ich treffe einen Freund.",
    commonExamples: ["友だちに会います。"],
    commonPatterns: ["〜に会います"],
    relatedExpressions: ["会います"],
    shortTip: "Bei „会う“ benutzt man „に“ für die Person.",
    detailTip:
      "Wie in „友だちに会います“ benutzt man das Partikel „に“ für die Person, die man trifft.",
    relatedVocabIds: ["friend", "talk", "tomorrow"],
  },
  {
    id: "talk",
    kanji: "話す",
    kana: "はなす",
    romaji: "hanasu",
    german: "sprechen",
    categoryId: "freunde",
    stage: 3,
    unlockLevel: 3,
    xpReward: 10,
    rarity: "common",
    exampleJapanese: "友だちと話します。",
    exampleKana: "ともだちとはなします。",
    exampleGerman: "Ich spreche mit einem Freund.",
    commonExamples: ["友だちと話します。"],
    commonPatterns: ["〜と話します"],
    relatedExpressions: ["話します"],
    shortTip: "„〜と話します“ benutzt man, wenn man mit jemandem spricht.",
    detailTip: "„友だちと話します“ bedeutet „Ich spreche mit einem Freund“.",
    relatedVocabIds: ["friend", "meet", "like"],
  },
  {
    id: "tomorrow",
    kanji: "明日",
    kana: "あした",
    romaji: "ashita",
    german: "morgen",
    categoryId: "freunde",
    stage: 3,
    unlockLevel: 3,
    xpReward: 10,
    rarity: "common",
    exampleJapanese: "明日、友だちに会います。",
    exampleKana: "あした、ともだちにあいます。",
    exampleGerman: "Morgen treffe ich einen Freund.",
    commonExamples: ["明日、友だちに会います。"],
    commonPatterns: ["明日、〜"],
    relatedExpressions: ["明日は"],
    shortTip: "„明日“ steht oft am Satzanfang.",
    detailTip:
      "„明日“ bedeutet „morgen“ und wird oft benutzt, wenn man über zukünftige Pläne spricht.",
    relatedVocabIds: ["meet", "friend", "like"],
  },
  {
    id: "like",
    kanji: "好き",
    kana: "すき",
    romaji: "suki",
    german: "mögen / gern haben",
    categoryId: "freunde",
    stage: 3,
    unlockLevel: 3,
    xpReward: 10,
    rarity: "common",
    exampleJapanese: "友だちが好きです。",
    exampleKana: "ともだちがすきです。",
    exampleGerman: "Ich mag meine Freunde.",
    commonExamples: ["友だちが好きです。"],
    commonPatterns: ["〜が好きです"],
    relatedExpressions: ["好きです"],
    shortTip: "Bei „好き“ benutzt man „が“ für das, was man mag.",
    detailTip:
      "„好き“ wird wie ein Adjektiv benutzt, gehört aber zu den Na-Adjektiven. Für das, was man mag, benutzt man das Partikel „が“.",
    relatedVocabIds: ["friend", "talk", "tomorrow"],
  },
];

export function getVocabById(id: string): VocabItem | undefined {
  return vocabData.find((item) => item.id === id);
}

export function getVocabByCategory(categoryId: CategoryId): VocabItem[] {
  return vocabData.filter((item) => item.categoryId === categoryId);
}
