import type { CategoryId, VocabItem } from "@/types/learning";

export const vocabData: VocabItem[] = [
  // --- Café ---
  {
    id: "coffee",
    kanji: "コーヒー",
    kana: "コーヒー",
    romaji: "koohii",
    german: "Kaffee",
    categoryId: "cafe",
    stage: 0,
    unlockLevel: 0,
    xpReward: 10,
    rarity: "common",
    exampleJapanese: "コーヒーをください。",
    exampleKana: "コーヒーをください。",
    exampleGerman: "Einen Kaffee bitte.",
    commonExamples: [
      "コーヒーをください。",
      "コーヒーを飲みます。",
      "ホットコーヒーをください。",
    ],
    commonPatterns: ["〜をください", "〜を飲みます"],
    relatedExpressions: ["アイスコーヒー", "ホットコーヒー", "コーヒーください"],
    shortTip: "「ください」は注文やお願いで使える基本表現です。",
    detailTip:
      "「コーヒーをください」は、カフェや店で使える丁寧なお願いです。カジュアルには「コーヒーください」と言うこともあります。",
  },
  {
    id: "water",
    kanji: "水",
    kana: "みず",
    romaji: "mizu",
    german: "Wasser",
    categoryId: "cafe",
    stage: 0,
    unlockLevel: 0,
    xpReward: 10,
    rarity: "common",
    exampleJapanese: "水をください。",
    exampleKana: "みずをください。",
    exampleGerman: "Wasser bitte.",
    commonExamples: ["水をください。", "水を飲みます。", "冷たい水をください。"],
    commonPatterns: ["〜をください", "〜を飲みます"],
    relatedExpressions: ["冷たい水", "水ください", "水を飲む"],
    shortTip: "「〜をください」は注文やお願いで使えます。",
    detailTip:
      "「水をください」は、店やレストランで使える実用表現です。「水を飲みます」は行動説明であり、注文ではありません。",
  },
  {
    id: "bread",
    kanji: "パン",
    kana: "パン",
    romaji: "pan",
    german: "Brot",
    categoryId: "cafe",
    stage: 0,
    unlockLevel: 0,
    xpReward: 10,
    rarity: "common",
    exampleJapanese: "パンをください。",
    exampleKana: "パンをください。",
    exampleGerman: "Brot bitte.",
    commonExamples: ["パンをください。", "パンを食べます。", "パンが好きです。"],
    commonPatterns: ["〜をください", "〜を食べます"],
    relatedExpressions: ["朝ごはん", "パンください", "パンを食べる"],
    shortTip: "「パン」は日本語でもカタカナで使われます。",
    detailTip:
      "「パンをください」は店で使える注文表現です。「パンを食べます」は行動説明です。",
  },
  {
    id: "drink",
    kanji: "飲む",
    kana: "のむ",
    romaji: "nomu",
    german: "trinken",
    categoryId: "cafe",
    stage: 0,
    unlockLevel: 0,
    xpReward: 10,
    rarity: "common",
    exampleJapanese: "水を飲みます。",
    exampleKana: "みずをのみます。",
    exampleGerman: "Ich trinke Wasser.",
    commonExamples: ["水を飲みます。", "コーヒーを飲みます。", "お茶を飲みます。"],
    commonPatterns: ["〜を飲みます", "〜をください"],
    relatedExpressions: ["水を飲む", "コーヒーを飲む", "飲みます"],
    shortTip: "「飲む」は Wasser, Kaffee, Tee などに使います。",
    detailTip:
      "日本語では動詞が文の最後に置かれることが多いです。例: 水を + 飲みます。飲みます は丁寧な形です。",
  },
  {
    id: "eat",
    kanji: "食べる",
    kana: "たべる",
    romaji: "taberu",
    german: "essen",
    categoryId: "cafe",
    stage: 0,
    unlockLevel: 0,
    xpReward: 10,
    rarity: "common",
    exampleJapanese: "パンを食べます。",
    exampleKana: "パンをたべます。",
    exampleGerman: "Ich esse Brot.",
    commonExamples: ["パンを食べます。", "ごはんを食べます。", "朝ごはんを食べます。"],
    commonPatterns: ["〜を食べます", "ごはんを食べる"],
    relatedExpressions: ["パンを食べる", "朝ごはん", "食べます"],
    shortTip: "「食べます」は食べ物に使います。",
    detailTip:
      "「パンを食べます」は Ich esse Brot. です。「を」は食べる対象を示します。水やコーヒーには「飲みます」、パンやごはんには「食べます」を使います。",
  },

  // --- Reise ---
  {
    id: "station",
    kanji: "駅",
    kana: "えき",
    romaji: "eki",
    german: "Bahnhof",
    categoryId: "reise",
    stage: 1,
    unlockLevel: 1,
    xpReward: 10,
    rarity: "common",
    exampleJapanese: "駅はどこですか。",
    exampleKana: "えきはどこですか。",
    exampleGerman: "Wo ist der Bahnhof?",
    commonExamples: ["駅はどこですか。", "駅に行きます。"],
    commonPatterns: ["〜はどこですか", "〜に行きます"],
    relatedExpressions: ["駅まで", "駅の前"],
    shortTip: "「どこですか」は場所を尋ねる基本表現です。",
    detailTip:
      "「駅はどこですか」は道を尋ねるときの定番フレーズです。「〜はどこですか」は他の場所にも使えます。",
  },
  {
    id: "hotel",
    kanji: "ホテル",
    kana: "ホテル",
    romaji: "hoteru",
    german: "Hotel",
    categoryId: "reise",
    stage: 1,
    unlockLevel: 1,
    xpReward: 10,
    rarity: "common",
    exampleJapanese: "ホテルはどこですか。",
    exampleKana: "ホテルはどこですか。",
    exampleGerman: "Wo ist das Hotel?",
    commonExamples: ["ホテルはどこですか。", "ホテルに行きます。"],
    commonPatterns: ["〜はどこですか", "〜に行きます"],
    relatedExpressions: ["ホテルの部屋", "ホテルまで"],
    shortTip: "「ホテル」は外来語としてそのまま使われます。",
    detailTip:
      "「ホテル」はドイツ語の Hotel と同じ意味で、旅行中によく使う単語です。",
  },
  {
    id: "train",
    kanji: "電車",
    kana: "でんしゃ",
    romaji: "densha",
    german: "Zug",
    categoryId: "reise",
    stage: 1,
    unlockLevel: 1,
    xpReward: 10,
    rarity: "common",
    exampleJapanese: "電車に乗ります。",
    exampleKana: "でんしゃにのります。",
    exampleGerman: "Ich steige in den Zug ein.",
    commonExamples: ["電車に乗ります。", "電車で行きます。"],
    commonPatterns: ["〜に乗ります", "〜で行きます"],
    relatedExpressions: ["電車の中", "電車を降ります"],
    shortTip: "「〜に乗ります」は乗り物に乗るときに使います。",
    detailTip:
      "「電車に乗ります」は Ich steige in den Zug ein. です。「〜で行きます」は移動手段を表します。",
  },
  {
    id: "toilet",
    kanji: "トイレ",
    kana: "トイレ",
    romaji: "toire",
    german: "Toilette",
    categoryId: "reise",
    stage: 1,
    unlockLevel: 1,
    xpReward: 10,
    rarity: "common",
    exampleJapanese: "トイレはどこですか。",
    exampleKana: "トイレはどこですか。",
    exampleGerman: "Wo ist die Toilette?",
    commonExamples: ["トイレはどこですか。"],
    commonPatterns: ["〜はどこですか"],
    relatedExpressions: ["トイレを借ります"],
    shortTip: "旅行中に一番よく使う質問のひとつです。",
    detailTip: "「トイレはどこですか」は場所を尋ねる定番フレーズです。",
  },
  {
    id: "go",
    kanji: "行く",
    kana: "いく",
    romaji: "iku",
    german: "gehen",
    categoryId: "reise",
    stage: 1,
    unlockLevel: 1,
    xpReward: 10,
    rarity: "common",
    exampleJapanese: "駅に行きます。",
    exampleKana: "えきにいきます。",
    exampleGerman: "Ich gehe zum Bahnhof.",
    commonExamples: ["駅に行きます。", "ホテルに行きます。"],
    commonPatterns: ["〜に行きます"],
    relatedExpressions: ["行きます", "行く"],
    shortTip: "「〜に行きます」は目的地を表す基本文型です。",
    detailTip:
      "「行く」は移動を表す動詞です。「〜に行きます」の形でよく使われます。",
  },

  // --- Schule ---
  {
    id: "school",
    kanji: "学校",
    kana: "がっこう",
    romaji: "gakkou",
    german: "Schule",
    categoryId: "schule",
    stage: 2,
    unlockLevel: 2,
    xpReward: 10,
    rarity: "common",
    exampleJapanese: "学校に行きます。",
    exampleKana: "がっこうにいきます。",
    exampleGerman: "Ich gehe zur Schule.",
    commonExamples: ["学校に行きます。"],
    commonPatterns: ["〜に行きます"],
    relatedExpressions: ["学校の後で"],
    shortTip: "「学校」は日常会話でよく出てくる基本単語です。",
    detailTip: "「学校に行きます」は Ich gehe zur Schule. です。",
  },
  {
    id: "teacher",
    kanji: "先生",
    kana: "せんせい",
    romaji: "sensei",
    german: "Lehrer/Lehrerin",
    categoryId: "schule",
    stage: 2,
    unlockLevel: 2,
    xpReward: 10,
    rarity: "common",
    exampleJapanese: "先生に聞きます。",
    exampleKana: "せんせいにききます。",
    exampleGerman: "Ich frage den Lehrer.",
    commonExamples: ["先生に聞きます。"],
    commonPatterns: ["〜に聞きます"],
    relatedExpressions: ["先生、質問があります"],
    shortTip: "「先生」は学校でも他の職業でも敬称として使われます。",
    detailTip:
      "「先生」は teacher の意味以外にも、医者などにも使われる敬称です。",
  },
  {
    id: "japaneseLanguage",
    kanji: "日本語",
    kana: "にほんご",
    romaji: "nihongo",
    german: "Japanisch",
    categoryId: "schule",
    stage: 2,
    unlockLevel: 2,
    xpReward: 10,
    rarity: "common",
    exampleJapanese: "日本語を勉強します。",
    exampleKana: "にほんごをべんきょうします。",
    exampleGerman: "Ich lerne Japanisch.",
    commonExamples: ["日本語を勉強します。"],
    commonPatterns: ["〜を勉強します"],
    relatedExpressions: ["日本語が好きです"],
    shortTip: "「〜を勉強します」は学習内容を表す表現です。",
    detailTip: "「日本語を勉強します」は Ich lerne Japanisch. です。",
  },
  {
    id: "study",
    kanji: "勉強する",
    kana: "べんきょうする",
    romaji: "benkyou suru",
    german: "lernen",
    categoryId: "schule",
    stage: 2,
    unlockLevel: 2,
    xpReward: 10,
    rarity: "common",
    exampleJapanese: "日本語を勉強します。",
    exampleKana: "にほんごをべんきょうします。",
    exampleGerman: "Ich lerne Japanisch.",
    commonExamples: ["日本語を勉強します。"],
    commonPatterns: ["〜を勉強します"],
    relatedExpressions: ["勉強します"],
    shortTip: "「勉強する」は「する動詞」のひとつです。",
    detailTip:
      "「勉強する」は名詞「勉強」+「する」でできた動詞です。丁寧形は「勉強します」です。",
  },
  {
    id: "today",
    kanji: "今日",
    kana: "きょう",
    romaji: "kyou",
    german: "heute",
    categoryId: "schule",
    stage: 2,
    unlockLevel: 2,
    xpReward: 10,
    rarity: "common",
    exampleJapanese: "今日、学校に行きます。",
    exampleKana: "きょう、がっこうにいきます。",
    exampleGerman: "Heute gehe ich zur Schule.",
    commonExamples: ["今日、学校に行きます。"],
    commonPatterns: ["今日、〜"],
    relatedExpressions: ["今日は"],
    shortTip: "「今日」は文の最初に置かれることが多いです。",
    detailTip: "「今日」は heute の意味で、時を表す言葉として文頭で使われます。",
  },

  // --- Freunde ---
  {
    id: "friend",
    kanji: "友だち",
    kana: "ともだち",
    romaji: "tomodachi",
    german: "Freund/Freundin",
    categoryId: "freunde",
    stage: 3,
    unlockLevel: 3,
    xpReward: 10,
    rarity: "common",
    exampleJapanese: "友だちに会います。",
    exampleKana: "ともだちにあいます。",
    exampleGerman: "Ich treffe einen Freund.",
    commonExamples: ["友だちに会います。"],
    commonPatterns: ["〜に会います"],
    relatedExpressions: ["友だちと話す"],
    shortTip: "「友だち」は日常会話で頻出の基本語です。",
    detailTip: "「友だちに会います」は Ich treffe einen Freund. です。",
  },
  {
    id: "meet",
    kanji: "会う",
    kana: "あう",
    romaji: "au",
    german: "treffen",
    categoryId: "freunde",
    stage: 3,
    unlockLevel: 3,
    xpReward: 10,
    rarity: "common",
    exampleJapanese: "友だちに会います。",
    exampleKana: "ともだちにあいます。",
    exampleGerman: "Ich treffe einen Freund.",
    commonExamples: ["友だちに会います。"],
    commonPatterns: ["〜に会います"],
    relatedExpressions: ["会います"],
    shortTip: "「会う」の対象には「に」を使います。",
    detailTip:
      "「友だちに会います」のように、人と会う対象には助詞「に」を使います。",
  },
  {
    id: "talk",
    kanji: "話す",
    kana: "はなす",
    romaji: "hanasu",
    german: "sprechen",
    categoryId: "freunde",
    stage: 3,
    unlockLevel: 3,
    xpReward: 10,
    rarity: "common",
    exampleJapanese: "友だちと話します。",
    exampleKana: "ともだちとはなします。",
    exampleGerman: "Ich spreche mit einem Freund.",
    commonExamples: ["友だちと話します。"],
    commonPatterns: ["〜と話します"],
    relatedExpressions: ["話します"],
    shortTip: "「〜と話します」は誰かと一緒に話すときに使います。",
    detailTip: "「友だちと話します」は Ich spreche mit einem Freund. です。",
  },
  {
    id: "tomorrow",
    kanji: "明日",
    kana: "あした",
    romaji: "ashita",
    german: "morgen",
    categoryId: "freunde",
    stage: 3,
    unlockLevel: 3,
    xpReward: 10,
    rarity: "common",
    exampleJapanese: "明日、友だちに会います。",
    exampleKana: "あした、ともだちにあいます。",
    exampleGerman: "Morgen treffe ich einen Freund.",
    commonExamples: ["明日、友だちに会います。"],
    commonPatterns: ["明日、〜"],
    relatedExpressions: ["明日は"],
    shortTip: "「明日」は文頭で使われることが多い時間表現です。",
    detailTip: "「明日」は morgen の意味で、未来の予定を話すときによく使います。",
  },
  {
    id: "like",
    kanji: "好き",
    kana: "すき",
    romaji: "suki",
    german: "mögen / gern haben",
    categoryId: "freunde",
    stage: 3,
    unlockLevel: 3,
    xpReward: 10,
    rarity: "common",
    exampleJapanese: "友だちが好きです。",
    exampleKana: "ともだちがすきです。",
    exampleGerman: "Ich mag meine Freunde.",
    commonExamples: ["友だちが好きです。"],
    commonPatterns: ["〜が好きです"],
    relatedExpressions: ["好きです"],
    shortTip: "「好き」はな形容詞で、対象には「が」を使います。",
    detailTip:
      "「好き」は形容詞のように使われますが、活用はな形容詞タイプです。対象には助詞「が」を使います。",
  },
];

export function getVocabById(id: string): VocabItem | undefined {
  return vocabData.find((item) => item.id === id);
}

export function getVocabByCategory(categoryId: CategoryId): VocabItem[] {
  return vocabData.filter((item) => item.categoryId === categoryId);
}
