import type { CategoryId, VocabItem } from "@/types/learning";

export const vocabData: VocabItem[] = [
  // --- Café ---
  {
    id: "coffee",
    kanji: "コーヒー",
    kana: "コーヒー",
    romaji: "koohii",
    german: "Kaffee",
    categoryId: "cafe",
    stage: 0,
    unlockLevel: 0,
    xpReward: 10,
    rarity: "common",
    exampleJapanese: "コーヒーをください。",
    exampleKana: "コーヒーをください。",
    exampleGerman: "Einen Kaffee bitte.",
    commonExamples: [
      "コーヒーをください。",
      "コーヒーを飲みます。",
      "ホットコーヒーをください。",
    ],
    commonPatterns: ["〜をください", "〜を飲みます"],
    relatedExpressions: ["アイスコーヒー", "ホットコーヒー", "コーヒーください"],
    shortTip: "„Kudasai“ ist ein Grundausdruck für Bestellungen und Bitten.",
    detailTip:
      "„コーヒーをください“ ist eine höfliche Bitte, die man im Café oder Geschäft benutzt. Im lockeren Ton sagt man auch einfach „コーヒーください“.",
  },
  {
    id: "water",
    kanji: "水",
    kana: "みず",
    romaji: "mizu",
    german: "Wasser",
    categoryId: "cafe",
    stage: 0,
    unlockLevel: 0,
    xpReward: 10,
    rarity: "common",
    exampleJapanese: "水をください。",
    exampleKana: "みずをください。",
    exampleGerman: "Wasser bitte.",
    commonExamples: ["水をください。", "水を飲みます。", "冷たい水をください。"],
    commonPatterns: ["〜をください", "〜を飲みます"],
    relatedExpressions: ["冷たい水", "水ください", "水を飲む"],
    shortTip: "„〜をください“ benutzt man beim Bestellen oder Bitten.",
    detailTip:
      "„水をください“ ist ein nützlicher Ausdruck im Geschäft oder Restaurant. „水を飲みます“ beschreibt dagegen nur eine Handlung, keine Bestellung.",
  },
  {
    id: "bread",
    kanji: "パン",
    kana: "パン",
    romaji: "pan",
    german: "Brot",
    categoryId: "cafe",
    stage: 0,
    unlockLevel: 0,
    xpReward: 10,
    rarity: "common",
    exampleJapanese: "パンをください。",
    exampleKana: "パンをください。",
    exampleGerman: "Brot bitte.",
    commonExamples: ["パンをください。", "パンを食べます。", "パンが好きです。"],
    commonPatterns: ["〜をください", "〜を食べます"],
    relatedExpressions: ["朝ごはん", "パンください", "パンを食べる"],
    shortTip: "„パン“ wird auf Japanisch auch in Katakana geschrieben.",
    detailTip:
      "„パンをください“ ist ein Bestellsatz im Geschäft. „パンを食べます“ beschreibt dagegen nur, dass man Brot isst.",
  },
  {
    id: "drink",
    kanji: "飲む",
    kana: "のむ",
    romaji: "nomu",
    german: "trinken",
    categoryId: "cafe",
    stage: 0,
    unlockLevel: 0,
    xpReward: 10,
    rarity: "common",
    exampleJapanese: "水を飲みます。",
    exampleKana: "みずをのみます。",
    exampleGerman: "Ich trinke Wasser.",
    commonExamples: ["水を飲みます。", "コーヒーを飲みます。", "お茶を飲みます。"],
    commonPatterns: ["〜を飲みます", "〜をください"],
    relatedExpressions: ["水を飲む", "コーヒーを飲む", "飲みます"],
    shortTip: "„飲む“ benutzt man für Wasser, Kaffee, Tee und andere Getränke.",
    detailTip:
      "Im Japanischen steht das Verb meistens am Satzende, z. B. „水を + 飲みます“. „飲みます“ ist die höfliche Form.",
  },
  {
    id: "eat",
    kanji: "食べる",
    kana: "たべる",
    romaji: "taberu",
    german: "essen",
    categoryId: "cafe",
    stage: 0,
    unlockLevel: 0,
    xpReward: 10,
    rarity: "common",
    exampleJapanese: "パンを食べます。",
    exampleKana: "パンをたべます。",
    exampleGerman: "Ich esse Brot.",
    commonExamples: ["パンを食べます。", "ごはんを食べます。", "朝ごはんを食べます。"],
    commonPatterns: ["〜を食べます", "ごはんを食べる"],
    relatedExpressions: ["パンを食べる", "朝ごはん", "食べます"],
    shortTip: "„食べます“ benutzt man für Essen.",
    detailTip:
      "„パンを食べます“ bedeutet „Ich esse Brot“. „を“ markiert, was gegessen wird. Für Wasser oder Kaffee sagt man „飲みます“, für Brot oder Reis „食べます“.",
  },

  // --- Reise ---
  {
    id: "station",
    kanji: "駅",
    kana: "えき",
    romaji: "eki",
    german: "Bahnhof",
    categoryId: "reise",
    stage: 1,
    unlockLevel: 1,
    xpReward: 10,
    rarity: "common",
    exampleJapanese: "駅はどこですか。",
    exampleKana: "えきはどこですか。",
    exampleGerman: "Wo ist der Bahnhof?",
    commonExamples: ["駅はどこですか。", "駅に行きます。"],
    commonPatterns: ["〜はどこですか", "〜に行きます"],
    relatedExpressions: ["駅まで", "駅の前"],
    shortTip: "„駅“ ist ein wichtiges Wort auf Reisen.",
    detailTip:
      "„駅はどこですか“ ist ein natürlicher Ausdruck, um nach dem Bahnhof zu fragen. „どこですか“ bedeutet „wo ist …?“ und funktioniert auch für andere Orte.",
  },
  {
    id: "hotel",
    kanji: "ホテル",
    kana: "ホテル",
    romaji: "hoteru",
    german: "Hotel",
    categoryId: "reise",
    stage: 1,
    unlockLevel: 1,
    xpReward: 10,
    rarity: "common",
    exampleJapanese: "ホテルに行きます。",
    exampleKana: "ホテルにいきます。",
    exampleGerman: "Ich gehe zum Hotel.",
    commonExamples: ["ホテルに行きます。", "ホテルはどこですか。"],
    commonPatterns: ["〜に行きます", "〜はどこですか"],
    relatedExpressions: ["ホテルの部屋", "ホテルまで"],
    shortTip: "„ホテル“ wird als Fremdwort direkt übernommen.",
    detailTip:
      "„ホテルに行きます“ bedeutet „Ich gehe zum Hotel“. „ホテル“ hat die gleiche Bedeutung wie im Deutschen und wird oft auf Reisen benutzt.",
  },
  {
    id: "train",
    kanji: "電車",
    kana: "でんしゃ",
    romaji: "densha",
    german: "Zug",
    categoryId: "reise",
    stage: 1,
    unlockLevel: 1,
    xpReward: 10,
    rarity: "common",
    exampleJapanese: "電車で行きます。",
    exampleKana: "でんしゃでいきます。",
    exampleGerman: "Ich fahre mit dem Zug.",
    commonExamples: ["電車で行きます。", "電車に乗ります。"],
    commonPatterns: ["〜で行きます", "〜に乗ります"],
    relatedExpressions: ["電車の中", "電車を降ります"],
    shortTip: "„〜で行きます“ benutzt man, um ein Verkehrsmittel auszudrücken.",
    detailTip:
      "„電車で行きます“ bedeutet „Ich fahre mit dem Zug“. „で“ zeigt hier das Verkehrsmittel an.",
  },
  {
    id: "toilet",
    kanji: "トイレ",
    kana: "トイレ",
    romaji: "toire",
    german: "Toilette",
    categoryId: "reise",
    stage: 1,
    unlockLevel: 1,
    xpReward: 10,
    rarity: "common",
    exampleJapanese: "トイレはどこですか。",
    exampleKana: "トイレはどこですか。",
    exampleGerman: "Wo ist die Toilette?",
    commonExamples: ["トイレはどこですか。"],
    commonPatterns: ["〜はどこですか"],
    relatedExpressions: ["トイレを借ります"],
    shortTip: "Diese Frage ist eine der nützlichsten auf Reisen.",
    detailTip: "„トイレはどこですか“ ist ein Standardsatz, um nach der Toilette zu fragen.",
  },
  {
    id: "go",
    kanji: "行く",
    kana: "いく",
    romaji: "iku",
    german: "gehen",
    categoryId: "reise",
    stage: 1,
    unlockLevel: 1,
    xpReward: 10,
    rarity: "common",
    exampleJapanese: "ホテルに行きます。",
    exampleKana: "ホテルにいきます。",
    exampleGerman: "Ich gehe zum Hotel.",
    commonExamples: ["ホテルに行きます。", "駅に行きます。"],
    commonPatterns: ["〜に行きます"],
    relatedExpressions: ["行きます", "行く"],
    shortTip: "„〜に行きます“ zeigt ein Ziel an.",
    detailTip:
      "„行く“ ist ein Bewegungsverb. Wie in „ホテルに行きます“ wird es oft in der Form „〜に行きます“ benutzt.",
  },
  {
    id: "where",
    kanji: "どこ",
    kana: "どこ",
    romaji: "doko",
    german: "wo",
    categoryId: "reise",
    stage: 1,
    unlockLevel: 1,
    xpReward: 10,
    rarity: "common",
    exampleJapanese: "駅はどこですか。",
    exampleKana: "えきはどこですか。",
    exampleGerman: "Wo ist der Bahnhof?",
    commonExamples: ["駅はどこですか。", "トイレはどこですか。", "ホテルはどこですか。"],
    commonPatterns: ["〜はどこですか"],
    relatedExpressions: ["どこですか", "どこ"],
    shortTip: "„どこ“ ist das Grundwort, um nach einem Ort zu fragen.",
    detailTip:
      "„どこですか“ bedeutet „wo ist …?“. Mit „〜はどこですか“ kann man nach verschiedenen Orten fragen.",
  },
  {
    id: "excuseMe",
    kanji: "すみません",
    kana: "すみません",
    romaji: "sumimasen",
    german: "Entschuldigung",
    categoryId: "reise",
    stage: 1,
    unlockLevel: 1,
    xpReward: 10,
    rarity: "common",
    exampleJapanese: "すみません、駅はどこですか。",
    exampleKana: "すみません、えきはどこですか。",
    exampleGerman: "Entschuldigung, wo ist der Bahnhof?",
    commonExamples: ["すみません、駅はどこですか。", "すみません、トイレはどこですか。"],
    commonPatterns: ["すみません、〜"],
    relatedExpressions: ["すみません"],
    shortTip: "„すみません“ benutzt man, um jemanden höflich anzusprechen.",
    detailTip:
      "„すみません“ bedeutet „Entschuldigung“ und macht eine Frage nach dem Weg höflicher. Man kann es auch allein als Entschuldigung benutzen.",
  },
  {
    id: "right",
    kanji: "右",
    kana: "みぎ",
    romaji: "migi",
    german: "rechts",
    categoryId: "reise",
    stage: 1,
    unlockLevel: 1,
    xpReward: 10,
    rarity: "common",
    exampleJapanese: "右です。",
    exampleKana: "みぎです。",
    exampleGerman: "Es ist rechts.",
    commonExamples: ["右です。", "右に行きます。"],
    commonPatterns: ["〜です", "右に〜"],
    relatedExpressions: ["右側", "右に曲がります"],
    shortTip: "„右“ ist ein Grundwort für Richtungen.",
    detailTip:
      "„右です“ bedeutet „Es ist rechts“ und ist eine kurze Antwort bei einer Wegbeschreibung.",
  },
  {
    id: "left",
    kanji: "左",
    kana: "ひだり",
    romaji: "hidari",
    german: "links",
    categoryId: "reise",
    stage: 1,
    unlockLevel: 1,
    xpReward: 10,
    rarity: "common",
    exampleJapanese: "左です。",
    exampleKana: "ひだりです。",
    exampleGerman: "Es ist links.",
    commonExamples: ["左です。", "左に行きます。"],
    commonPatterns: ["〜です", "左に〜"],
    relatedExpressions: ["左側", "左に曲がります"],
    shortTip: "„左です“ ist eine kurze Antwort für eine Richtung.",
    detailTip: "„左です“ bedeutet „Es ist links“ und ist das Gegenteil von „右“.",
  },
  {
    id: "near",
    kanji: "近い",
    kana: "ちかい",
    romaji: "chikai",
    german: "nah",
    categoryId: "reise",
    stage: 1,
    unlockLevel: 1,
    xpReward: 10,
    rarity: "common",
    exampleJapanese: "駅は近いです。",
    exampleKana: "えきはちかいです。",
    exampleGerman: "Der Bahnhof ist nah.",
    commonExamples: ["駅は近いです。", "ホテルは近いです。"],
    commonPatterns: ["〜は近いです"],
    relatedExpressions: ["近くに", "近い"],
    shortTip: "„近いです“ bedeutet, dass etwas nah ist.",
    detailTip: "„駅は近いです“ bedeutet „Der Bahnhof ist nah“. Das Gegenteil ist „遠いです“.",
  },
  {
    id: "far",
    kanji: "遠い",
    kana: "とおい",
    romaji: "tooi",
    german: "weit / entfernt",
    categoryId: "reise",
    stage: 1,
    unlockLevel: 1,
    xpReward: 10,
    rarity: "common",
    exampleJapanese: "ホテルは遠いです。",
    exampleKana: "ホテルはとおいです。",
    exampleGerman: "Das Hotel ist weit entfernt.",
    commonExamples: ["ホテルは遠いです。", "駅は遠いです。"],
    commonPatterns: ["〜は遠いです"],
    relatedExpressions: ["遠くに", "遠い"],
    shortTip: "„遠いです“ bedeutet, dass etwas weit entfernt ist.",
    detailTip:
      "„ホテルは遠いです“ bedeutet „Das Hotel ist weit entfernt“. Das ist das Gegenteil von „近い“.",
  },

  // --- Schule ---
  {
    id: "school",
    kanji: "学校",
    kana: "がっこう",
    romaji: "gakkou",
    german: "Schule",
    categoryId: "schule",
    stage: 2,
    unlockLevel: 2,
    xpReward: 10,
    rarity: "common",
    exampleJapanese: "学校に行きます。",
    exampleKana: "がっこうにいきます。",
    exampleGerman: "Ich gehe zur Schule.",
    commonExamples: ["学校に行きます。"],
    commonPatterns: ["〜に行きます"],
    relatedExpressions: ["学校の後で"],
    shortTip: "„学校“ ist ein Grundwort im Alltag.",
    detailTip: "„学校に行きます“ bedeutet „Ich gehe zur Schule“.",
  },
  {
    id: "teacher",
    kanji: "先生",
    kana: "せんせい",
    romaji: "sensei",
    german: "Lehrer/Lehrerin",
    categoryId: "schule",
    stage: 2,
    unlockLevel: 2,
    xpReward: 10,
    rarity: "common",
    exampleJapanese: "先生に聞きます。",
    exampleKana: "せんせいにききます。",
    exampleGerman: "Ich frage den Lehrer.",
    commonExamples: ["先生に聞きます。"],
    commonPatterns: ["〜に聞きます"],
    relatedExpressions: ["先生、質問があります"],
    shortTip: "„先生“ ist eine höfliche Anrede, nicht nur in der Schule.",
    detailTip:
      "„先生“ wird nicht nur für Lehrer benutzt, sondern auch für Ärzte und andere Berufe als höfliche Anrede.",
  },
  {
    id: "japaneseLanguage",
    kanji: "日本語",
    kana: "にほんご",
    romaji: "nihongo",
    german: "Japanisch",
    categoryId: "schule",
    stage: 2,
    unlockLevel: 2,
    xpReward: 10,
    rarity: "common",
    exampleJapanese: "日本語を勉強します。",
    exampleKana: "にほんごをべんきょうします。",
    exampleGerman: "Ich lerne Japanisch.",
    commonExamples: ["日本語を勉強します。"],
    commonPatterns: ["〜を勉強します"],
    relatedExpressions: ["日本語が好きです"],
    shortTip: "„〜を勉強します“ zeigt an, was man lernt.",
    detailTip: "„日本語を勉強します“ bedeutet „Ich lerne Japanisch“.",
  },
  {
    id: "study",
    kanji: "勉強する",
    kana: "べんきょうする",
    romaji: "benkyou suru",
    german: "lernen",
    categoryId: "schule",
    stage: 2,
    unlockLevel: 2,
    xpReward: 10,
    rarity: "common",
    exampleJapanese: "日本語を勉強します。",
    exampleKana: "にほんごをべんきょうします。",
    exampleGerman: "Ich lerne Japanisch.",
    commonExamples: ["日本語を勉強します。"],
    commonPatterns: ["〜を勉強します"],
    relatedExpressions: ["勉強します"],
    shortTip: "„勉強する“ ist ein „Suru-Verb“.",
    detailTip:
      "„勉強する“ besteht aus dem Nomen „勉強“ und „する“. Die höfliche Form ist „勉強します“.",
  },
  {
    id: "today",
    kanji: "今日",
    kana: "きょう",
    romaji: "kyou",
    german: "heute",
    categoryId: "schule",
    stage: 2,
    unlockLevel: 2,
    xpReward: 10,
    rarity: "common",
    exampleJapanese: "今日、学校に行きます。",
    exampleKana: "きょう、がっこうにいきます。",
    exampleGerman: "Heute gehe ich zur Schule.",
    commonExamples: ["今日、学校に行きます。"],
    commonPatterns: ["今日、〜"],
    relatedExpressions: ["今日は"],
    shortTip: "„今日“ steht meistens am Satzanfang.",
    detailTip:
      "„今日“ bedeutet „heute“ und wird als Zeitangabe oft an den Satzanfang gestellt.",
  },

  // --- Freunde ---
  {
    id: "friend",
    kanji: "友だち",
    kana: "ともだち",
    romaji: "tomodachi",
    german: "Freund/Freundin",
    categoryId: "freunde",
    stage: 3,
    unlockLevel: 3,
    xpReward: 10,
    rarity: "common",
    exampleJapanese: "友だちに会います。",
    exampleKana: "ともだちにあいます。",
    exampleGerman: "Ich treffe einen Freund.",
    commonExamples: ["友だちに会います。"],
    commonPatterns: ["〜に会います"],
    relatedExpressions: ["友だちと話す"],
    shortTip: "„友だち“ ist ein häufiges Wort im Alltag.",
    detailTip: "„友だちに会います“ bedeutet „Ich treffe einen Freund“.",
  },
  {
    id: "meet",
    kanji: "会う",
    kana: "あう",
    romaji: "au",
    german: "treffen",
    categoryId: "freunde",
    stage: 3,
    unlockLevel: 3,
    xpReward: 10,
    rarity: "common",
    exampleJapanese: "友だちに会います。",
    exampleKana: "ともだちにあいます。",
    exampleGerman: "Ich treffe einen Freund.",
    commonExamples: ["友だちに会います。"],
    commonPatterns: ["〜に会います"],
    relatedExpressions: ["会います"],
    shortTip: "Bei „会う“ benutzt man „に“ für die Person.",
    detailTip:
      "Wie in „友だちに会います“ benutzt man das Partikel „に“ für die Person, die man trifft.",
  },
  {
    id: "talk",
    kanji: "話す",
    kana: "はなす",
    romaji: "hanasu",
    german: "sprechen",
    categoryId: "freunde",
    stage: 3,
    unlockLevel: 3,
    xpReward: 10,
    rarity: "common",
    exampleJapanese: "友だちと話します。",
    exampleKana: "ともだちとはなします。",
    exampleGerman: "Ich spreche mit einem Freund.",
    commonExamples: ["友だちと話します。"],
    commonPatterns: ["〜と話します"],
    relatedExpressions: ["話します"],
    shortTip: "„〜と話します“ benutzt man, wenn man mit jemandem spricht.",
    detailTip: "„友だちと話します“ bedeutet „Ich spreche mit einem Freund“.",
  },
  {
    id: "tomorrow",
    kanji: "明日",
    kana: "あした",
    romaji: "ashita",
    german: "morgen",
    categoryId: "freunde",
    stage: 3,
    unlockLevel: 3,
    xpReward: 10,
    rarity: "common",
    exampleJapanese: "明日、友だちに会います。",
    exampleKana: "あした、ともだちにあいます。",
    exampleGerman: "Morgen treffe ich einen Freund.",
    commonExamples: ["明日、友だちに会います。"],
    commonPatterns: ["明日、〜"],
    relatedExpressions: ["明日は"],
    shortTip: "„明日“ steht oft am Satzanfang.",
    detailTip:
      "„明日“ bedeutet „morgen“ und wird oft benutzt, wenn man über zukünftige Pläne spricht.",
  },
  {
    id: "like",
    kanji: "好き",
    kana: "すき",
    romaji: "suki",
    german: "mögen / gern haben",
    categoryId: "freunde",
    stage: 3,
    unlockLevel: 3,
    xpReward: 10,
    rarity: "common",
    exampleJapanese: "友だちが好きです。",
    exampleKana: "ともだちがすきです。",
    exampleGerman: "Ich mag meine Freunde.",
    commonExamples: ["友だちが好きです。"],
    commonPatterns: ["〜が好きです"],
    relatedExpressions: ["好きです"],
    shortTip: "Bei „好き“ benutzt man „が“ für das, was man mag.",
    detailTip:
      "„好き“ wird wie ein Adjektiv benutzt, gehört aber zu den Na-Adjektiven. Für das, was man mag, benutzt man das Partikel „が“.",
  },
];

export function getVocabById(id: string): VocabItem | undefined {
  return vocabData.find((item) => item.id === id);
}

export function getVocabByCategory(categoryId: CategoryId): VocabItem[] {
  return vocabData.filter((item) => item.categoryId === categoryId);
}
