import type { QuizQuestion } from "@/types/learning";
import { defineSubQuest } from "./shared";

/**
 * Hand-authored Sub Quests for the Café words (Block 1, A0). Learning focus of the
 * category: bestellen mit „〜をください“, beschreiben mit „〜を飲みます / 〜を食べます“,
 * and the object particle を. Every question keeps the selected word as its subject.
 */
export const cafeSubQuests: Record<string, QuizQuestion[]> = {
  coffee: defineSubQuest(
    "coffee",
    "cafe",
    [
      {
        step: "meaning",
        type: "meaning-choice",
        instruction: "Wähle die richtige Bedeutung.",
        prompt: "コーヒー",
        choices: ["Kaffee", "Wasser", "Brot", "trinken"],
        answer: "Kaffee",
      },
      {
        step: "word",
        type: "japanese-choice",
        instruction: "Wähle das passende japanische Wort.",
        prompt: "Kaffee",
        choices: ["コーヒー", "水", "パン", "飲む"],
        answer: "コーヒー",
      },
      {
        step: "particle",
        type: "particle-choice",
        instruction: "Wähle die passende Partikel.",
        prompt: "„Einen Kaffee bitte.“\nコーヒー____ください。",
        choices: ["を", "に", "と", "は"],
        answer: "を",
        exampleJapanese: "コーヒーをください。",
        exampleKana: "コーヒーをください。",
        exampleGerman: "Einen Kaffee bitte.",
      },
      {
        step: "verb",
        type: "fill-blank",
        instruction: "Ergänze den Satz.",
        prompt: "„Ich trinke Kaffee.“\nコーヒーを____。",
        choices: ["飲みます", "食べます", "ください", "行きます"],
        answer: "飲みます",
        exampleJapanese: "コーヒーを飲みます。",
        exampleKana: "コーヒーをのみます。",
        exampleGerman: "Ich trinke Kaffee.",
      },
      {
        step: "sentence-meaning",
        type: "sentence-meaning-choice",
        instruction: "Was bedeutet dieser Satz?",
        prompt: "コーヒーとパンをください。",
        choices: [
          "Kaffee und Brot bitte.",
          "Einen Kaffee bitte.",
          "Ich trinke Kaffee und esse Brot.",
          "Wasser und Brot bitte.",
        ],
        answer: "Kaffee und Brot bitte.",
        exampleJapanese: "コーヒーとパンをください。",
        exampleKana: "コーヒーとパンをください。",
        exampleGerman: "Kaffee und Brot bitte.",
      },
      {
        step: "phrase",
        type: "phrase-choice",
        instruction: "Wähle den natürlichen japanischen Satz.",
        prompt: "Ich trinke Kaffee.",
        choices: ["コーヒーを飲みます。", "コーヒーをください。", "コーヒーを食べます。", "水を飲みます。"],
        answer: "コーヒーを飲みます。",
        answerKana: "コーヒーをのみます。",
        answerRomaji: "koohii o nomimasu",
        answerGerman: "Ich trinke Kaffee.",
        exampleJapanese: "コーヒーを飲みます。",
        exampleKana: "コーヒーをのみます。",
        exampleGerman: "Ich trinke Kaffee.",
      },
      {
        step: "mistake",
        type: "mistake-choice",
        instruction: "Achtung, Verwechslungsgefahr: Wähle den richtigen Satz.",
        prompt: "Du bestellst im Café: „Einen Kaffee bitte.“",
        choices: ["コーヒーをください。", "コーヒーを飲みます。", "コーヒーを食べます。", "コーヒーはどこですか。"],
        answer: "コーヒーをください。",
        exampleJapanese: "コーヒーをください。",
        exampleKana: "コーヒーをください。",
        exampleGerman: "Einen Kaffee bitte.",
      },
      {
        step: "combo",
        type: "sentence-meaning-choice",
        instruction: "Was bedeutet dieser Satz?",
        prompt: "コーヒーを飲みます。パンを食べます。",
        choices: [
          "Ich trinke Kaffee und esse Brot.",
          "Ich trinke Wasser und esse Brot.",
          "Kaffee und Brot bitte.",
          "Ich esse Brot.",
        ],
        answer: "Ich trinke Kaffee und esse Brot.",
        exampleJapanese: "コーヒーを飲みます。パンを食べます。",
        exampleKana: "コーヒーをのみます。パンをたべます。",
        exampleGerman: "Ich trinke Kaffee und esse Brot.",
      },
      {
        step: "mini",
        type: "phrase-choice",
        instruction: "Mini Challenge: Wähle den natürlichen japanischen Satz.",
        prompt: "Kaffee und Wasser bitte.",
        choices: ["コーヒーと水をください。", "コーヒーをください。", "水とパンをください。", "コーヒーと水を飲みます。"],
        answer: "コーヒーと水をください。",
        answerKana: "コーヒーとみずをください。",
        answerRomaji: "koohii to mizu o kudasai",
        answerGerman: "Kaffee und Wasser bitte.",
        exampleJapanese: "コーヒーと水をください。",
        exampleKana: "コーヒーとみずをください。",
        exampleGerman: "Kaffee und Wasser bitte.",
      },
    ],
    {
      speechText: "コーヒーをください。",
      speechKana: "コーヒーをください。",
      speechRomaji: "koohii o kudasai",
      speechGerman: "Einen Kaffee bitte.",
      acceptedTranscripts: ["コーヒーをください", "こーひーをください"],
    }
  ),

  water: defineSubQuest(
    "water",
    "cafe",
    [
      {
        step: "meaning",
        type: "meaning-choice",
        instruction: "Wähle die richtige Bedeutung.",
        prompt: "水",
        choices: ["Wasser", "Kaffee", "Brot", "essen"],
        answer: "Wasser",
      },
      {
        step: "word",
        type: "japanese-choice",
        instruction: "Wähle das passende japanische Wort.",
        prompt: "Wasser",
        choices: ["水", "コーヒー", "パン", "飲む"],
        answer: "水",
      },
      {
        step: "particle",
        type: "particle-choice",
        instruction: "Wähle die passende Partikel.",
        prompt: "„Ich trinke Wasser.“\n水____飲みます。",
        choices: ["を", "に", "と", "は"],
        answer: "を",
        exampleJapanese: "水を飲みます。",
        exampleKana: "みずをのみます。",
        exampleGerman: "Ich trinke Wasser.",
      },
      {
        step: "verb",
        type: "fill-blank",
        instruction: "Ergänze den Satz.",
        prompt: "„Wasser bitte.“\n水を____。",
        choices: ["ください", "飲みます", "食べます", "行きます"],
        answer: "ください",
        exampleJapanese: "水をください。",
        exampleKana: "みずをください。",
        exampleGerman: "Wasser bitte.",
      },
      {
        step: "sentence-meaning",
        type: "sentence-meaning-choice",
        instruction: "Was bedeutet dieser Satz?",
        prompt: "水を飲みます。",
        choices: ["Ich trinke Wasser.", "Wasser bitte.", "Ich trinke Kaffee.", "Ich esse Brot."],
        answer: "Ich trinke Wasser.",
        exampleJapanese: "水を飲みます。",
        exampleKana: "みずをのみます。",
        exampleGerman: "Ich trinke Wasser.",
      },
      {
        step: "phrase",
        type: "phrase-choice",
        instruction: "Wähle den natürlichen japanischen Satz.",
        prompt: "Wasser bitte.",
        choices: ["水をください。", "水を飲みます。", "コーヒーをください。", "水を食べます。"],
        answer: "水をください。",
        answerKana: "みずをください。",
        answerRomaji: "mizu o kudasai",
        answerGerman: "Wasser bitte.",
        exampleJapanese: "水をください。",
        exampleKana: "みずをください。",
        exampleGerman: "Wasser bitte.",
      },
      {
        step: "mistake",
        type: "mistake-choice",
        instruction: "Achtung, Verwechslungsgefahr: Wähle den richtigen Satz.",
        prompt: "Bestellung, keine Beschreibung: „Wasser bitte.“",
        choices: ["水をください。", "水を飲みます。", "水を食べます。", "水です。"],
        answer: "水をください。",
        exampleJapanese: "水をください。",
        exampleKana: "みずをください。",
        exampleGerman: "Wasser bitte.",
      },
      {
        step: "combo",
        type: "phrase-choice",
        instruction: "Wähle den natürlichen japanischen Satz.",
        prompt: "Wasser und Brot bitte.",
        choices: ["水とパンをください。", "水をください。", "水とパンを食べます。", "パンとコーヒーをください。"],
        answer: "水とパンをください。",
        answerKana: "みずとパンをください。",
        answerRomaji: "mizu to pan o kudasai",
        answerGerman: "Wasser und Brot bitte.",
        exampleJapanese: "水とパンをください。",
        exampleKana: "みずとパンをください。",
        exampleGerman: "Wasser und Brot bitte.",
      },
      {
        step: "mini",
        type: "phrase-choice",
        instruction: "Mini Challenge: Wähle den natürlichen japanischen Satz.",
        prompt: "Trinkst du Wasser?",
        choices: ["水を飲みますか。", "水を飲みます。", "水をください。", "パンを食べますか。"],
        answer: "水を飲みますか。",
        answerKana: "みずをのみますか。",
        answerRomaji: "mizu o nomimasu ka",
        answerGerman: "Trinkst du Wasser?",
        exampleJapanese: "水を飲みますか。",
        exampleKana: "みずをのみますか。",
        exampleGerman: "Trinkst du Wasser?",
      },
    ],
    {
      speechText: "水をください。",
      speechKana: "みずをください。",
      speechRomaji: "mizu o kudasai",
      speechGerman: "Wasser bitte.",
      acceptedTranscripts: ["水をください", "みずをください"],
    }
  ),

  bread: defineSubQuest(
    "bread",
    "cafe",
    [
      {
        step: "meaning",
        type: "meaning-choice",
        instruction: "Wähle die richtige Bedeutung.",
        prompt: "パン",
        choices: ["Brot", "Kaffee", "Wasser", "essen"],
        answer: "Brot",
      },
      {
        step: "word",
        type: "japanese-choice",
        instruction: "Wähle das passende japanische Wort.",
        prompt: "Brot",
        choices: ["パン", "水", "コーヒー", "食べる"],
        answer: "パン",
      },
      {
        step: "particle",
        type: "particle-choice",
        instruction: "Wähle die passende Partikel.",
        prompt: "„Ich esse Brot.“\nパン____食べます。",
        choices: ["を", "に", "と", "は"],
        answer: "を",
        exampleJapanese: "パンを食べます。",
        exampleKana: "パンをたべます。",
        exampleGerman: "Ich esse Brot.",
      },
      {
        step: "verb",
        type: "fill-blank",
        instruction: "Ergänze den Satz.",
        prompt: "„Brot bitte.“\nパンを____。",
        choices: ["ください", "食べます", "飲みます", "行きます"],
        answer: "ください",
        exampleJapanese: "パンをください。",
        exampleKana: "パンをください。",
        exampleGerman: "Brot bitte.",
      },
      {
        step: "sentence-meaning",
        type: "sentence-meaning-choice",
        instruction: "Was bedeutet dieser Satz?",
        prompt: "パンを食べます。",
        choices: ["Ich esse Brot.", "Brot bitte.", "Ich trinke Wasser.", "Ich trinke Kaffee."],
        answer: "Ich esse Brot.",
        exampleJapanese: "パンを食べます。",
        exampleKana: "パンをたべます。",
        exampleGerman: "Ich esse Brot.",
      },
      {
        step: "phrase",
        type: "phrase-choice",
        instruction: "Wähle den natürlichen japanischen Satz.",
        prompt: "Brot bitte.",
        choices: ["パンをください。", "パンを食べます。", "水をください。", "パンを飲みます。"],
        answer: "パンをください。",
        answerKana: "パンをください。",
        answerRomaji: "pan o kudasai",
        answerGerman: "Brot bitte.",
        exampleJapanese: "パンをください。",
        exampleKana: "パンをください。",
        exampleGerman: "Brot bitte.",
      },
      {
        step: "mistake",
        type: "mistake-choice",
        instruction: "Achtung, Verwechslungsgefahr: Wähle den richtigen Satz.",
        prompt: "Essen, nicht trinken: „Ich esse Brot.“",
        choices: ["パンを食べます。", "パンを飲みます。", "パンをください。", "パンです。"],
        answer: "パンを食べます。",
        exampleJapanese: "パンを食べます。",
        exampleKana: "パンをたべます。",
        exampleGerman: "Ich esse Brot.",
      },
      {
        step: "combo",
        type: "phrase-choice",
        instruction: "Wähle den natürlichen japanischen Satz.",
        prompt: "Brot und Wasser bitte.",
        choices: ["パンと水をください。", "パンをください。", "パンと水を食べます。", "水とコーヒーをください。"],
        answer: "パンと水をください。",
        answerKana: "パンとみずをください。",
        answerRomaji: "pan to mizu o kudasai",
        answerGerman: "Brot und Wasser bitte.",
        exampleJapanese: "パンと水をください。",
        exampleKana: "パンとみずをください。",
        exampleGerman: "Brot und Wasser bitte.",
      },
      {
        step: "mini",
        type: "sentence-meaning-choice",
        instruction: "Mini Challenge: Was bedeutet dieser Satz?",
        prompt: "パンを食べます。水を飲みます。",
        choices: [
          "Ich esse Brot und trinke Wasser.",
          "Ich esse Brot und trinke Kaffee.",
          "Brot und Wasser bitte.",
          "Ich trinke Wasser.",
        ],
        answer: "Ich esse Brot und trinke Wasser.",
        exampleJapanese: "パンを食べます。水を飲みます。",
        exampleKana: "パンをたべます。みずをのみます。",
        exampleGerman: "Ich esse Brot und trinke Wasser.",
      },
    ],
    {
      speechText: "パンをください。",
      speechKana: "パンをください。",
      speechRomaji: "pan o kudasai",
      speechGerman: "Brot bitte.",
      acceptedTranscripts: ["パンをください", "ぱんをください"],
    }
  ),

  drink: defineSubQuest(
    "drink",
    "cafe",
    [
      {
        step: "meaning",
        type: "meaning-choice",
        instruction: "Wähle die richtige Bedeutung.",
        prompt: "飲む",
        choices: ["trinken", "essen", "Wasser", "Kaffee"],
        answer: "trinken",
      },
      {
        step: "word",
        type: "japanese-choice",
        instruction: "Wähle das passende japanische Wort.",
        prompt: "trinken",
        choices: ["飲む", "食べる", "水", "コーヒー"],
        answer: "飲む",
      },
      {
        step: "particle",
        type: "particle-choice",
        instruction: "Wähle die passende Partikel.",
        prompt: "„Ich trinke Kaffee.“\nコーヒー____飲みます。",
        choices: ["を", "と", "に", "は"],
        answer: "を",
        exampleJapanese: "コーヒーを飲みます。",
        exampleKana: "コーヒーをのみます。",
        exampleGerman: "Ich trinke Kaffee.",
      },
      {
        step: "verb",
        type: "fill-blank",
        instruction: "Ergänze den Satz.",
        prompt: "„Ich trinke Wasser.“\n水を____。",
        choices: ["飲みます", "ください", "食べます", "行きます"],
        answer: "飲みます",
        exampleJapanese: "水を飲みます。",
        exampleKana: "みずをのみます。",
        exampleGerman: "Ich trinke Wasser.",
      },
      {
        step: "sentence-meaning",
        type: "sentence-meaning-choice",
        instruction: "Was bedeutet dieser Satz?",
        prompt: "コーヒーを飲みます。",
        choices: ["Ich trinke Kaffee.", "Ich trinke Wasser.", "Einen Kaffee bitte.", "Ich esse Brot."],
        answer: "Ich trinke Kaffee.",
        exampleJapanese: "コーヒーを飲みます。",
        exampleKana: "コーヒーをのみます。",
        exampleGerman: "Ich trinke Kaffee.",
      },
      {
        step: "phrase",
        type: "phrase-choice",
        instruction: "Wähle den natürlichen japanischen Satz.",
        prompt: "Ich trinke Wasser.",
        choices: ["水を飲みます。", "水をください。", "水を食べます。", "コーヒーを飲みます。"],
        answer: "水を飲みます。",
        answerKana: "みずをのみます。",
        answerRomaji: "mizu o nomimasu",
        answerGerman: "Ich trinke Wasser.",
        exampleJapanese: "水を飲みます。",
        exampleKana: "みずをのみます。",
        exampleGerman: "Ich trinke Wasser.",
      },
      {
        step: "mistake",
        type: "mistake-choice",
        instruction: "Achtung, Verwechslungsgefahr: Wähle den richtigen Satz.",
        prompt: "Beschreibung, keine Bestellung: „Ich trinke Kaffee.“",
        choices: ["コーヒーを飲みます。", "コーヒーをください。", "コーヒーを食べます。", "コーヒーです。"],
        answer: "コーヒーを飲みます。",
        exampleJapanese: "コーヒーを飲みます。",
        exampleKana: "コーヒーをのみます。",
        exampleGerman: "Ich trinke Kaffee.",
      },
      {
        step: "combo",
        type: "phrase-choice",
        instruction: "Wähle den natürlichen japanischen Satz.",
        prompt: "Trinkst du Kaffee?",
        choices: ["コーヒーを飲みますか。", "コーヒーを飲みます。", "コーヒーをください。", "水を飲みますか。"],
        answer: "コーヒーを飲みますか。",
        answerKana: "コーヒーをのみますか。",
        answerRomaji: "koohii o nomimasu ka",
        answerGerman: "Trinkst du Kaffee?",
        exampleJapanese: "コーヒーを飲みますか。",
        exampleKana: "コーヒーをのみますか。",
        exampleGerman: "Trinkst du Kaffee?",
      },
      {
        step: "mini",
        type: "sentence-meaning-choice",
        instruction: "Mini Challenge: Was bedeutet dieser Satz?",
        prompt: "パンを食べます。コーヒーを飲みます。",
        choices: [
          "Ich esse Brot und trinke Kaffee.",
          "Ich esse Brot und trinke Wasser.",
          "Ich trinke Kaffee.",
          "Brot und Kaffee bitte.",
        ],
        answer: "Ich esse Brot und trinke Kaffee.",
        exampleJapanese: "パンを食べます。コーヒーを飲みます。",
        exampleKana: "パンをたべます。コーヒーをのみます。",
        exampleGerman: "Ich esse Brot und trinke Kaffee.",
      },
    ],
    {
      speechText: "水を飲みます。",
      speechKana: "みずをのみます。",
      speechRomaji: "mizu o nomimasu",
      speechGerman: "Ich trinke Wasser.",
      acceptedTranscripts: ["水を飲みます", "みずをのみます"],
    }
  ),

  eat: defineSubQuest(
    "eat",
    "cafe",
    [
      {
        step: "meaning",
        type: "meaning-choice",
        instruction: "Wähle die richtige Bedeutung.",
        prompt: "食べる",
        choices: ["essen", "trinken", "Brot", "Wasser"],
        answer: "essen",
      },
      {
        step: "word",
        type: "japanese-choice",
        instruction: "Wähle das passende japanische Wort.",
        prompt: "essen",
        choices: ["食べる", "飲む", "パン", "水"],
        answer: "食べる",
      },
      {
        step: "particle",
        type: "particle-choice",
        instruction: "Wähle die passende Partikel.",
        prompt: "„Ich esse Brot.“\nパン____食べます。",
        choices: ["を", "に", "と", "で"],
        answer: "を",
        exampleJapanese: "パンを食べます。",
        exampleKana: "パンをたべます。",
        exampleGerman: "Ich esse Brot.",
      },
      {
        step: "verb",
        type: "fill-blank",
        instruction: "Ergänze den Satz.",
        prompt: "„Ich esse Brot.“\nパンを____。",
        choices: ["食べます", "飲みます", "ください", "行きます"],
        answer: "食べます",
        exampleJapanese: "パンを食べます。",
        exampleKana: "パンをたべます。",
        exampleGerman: "Ich esse Brot.",
      },
      {
        step: "sentence-meaning",
        type: "sentence-meaning-choice",
        instruction: "Was bedeutet dieser Satz?",
        prompt: "パンを食べます。",
        choices: ["Ich esse Brot.", "Ich trinke Wasser.", "Brot bitte.", "Ich trinke Kaffee."],
        answer: "Ich esse Brot.",
        exampleJapanese: "パンを食べます。",
        exampleKana: "パンをたべます。",
        exampleGerman: "Ich esse Brot.",
      },
      {
        step: "phrase",
        type: "phrase-choice",
        instruction: "Wähle den natürlichen japanischen Satz.",
        prompt: "Isst du Brot?",
        choices: ["パンを食べますか。", "パンを食べます。", "パンを飲みますか。", "パンをください。"],
        answer: "パンを食べますか。",
        answerKana: "パンをたべますか。",
        answerRomaji: "pan o tabemasu ka",
        answerGerman: "Isst du Brot?",
        exampleJapanese: "パンを食べますか。",
        exampleKana: "パンをたべますか。",
        exampleGerman: "Isst du Brot?",
      },
      {
        step: "mistake",
        type: "mistake-choice",
        instruction: "Achtung, Verwechslungsgefahr: Wähle den richtigen Satz.",
        prompt: "Essen, nicht trinken: „Ich esse Brot.“",
        choices: ["パンを食べます。", "パンを飲みます。", "パンで食べます。", "パンに食べます。"],
        answer: "パンを食べます。",
        exampleJapanese: "パンを食べます。",
        exampleKana: "パンをたべます。",
        exampleGerman: "Ich esse Brot.",
      },
      {
        step: "combo",
        type: "sentence-meaning-choice",
        instruction: "Was bedeutet dieser Satz?",
        prompt: "パンを食べます。コーヒーを飲みます。",
        choices: [
          "Ich esse Brot und trinke Kaffee.",
          "Ich esse Brot und trinke Wasser.",
          "Kaffee und Brot bitte.",
          "Ich trinke Kaffee.",
        ],
        answer: "Ich esse Brot und trinke Kaffee.",
        exampleJapanese: "パンを食べます。コーヒーを飲みます。",
        exampleKana: "パンをたべます。コーヒーをのみます。",
        exampleGerman: "Ich esse Brot und trinke Kaffee.",
      },
      {
        step: "mini",
        type: "phrase-choice",
        instruction: "Mini Challenge: Wähle den natürlichen japanischen Satz.",
        prompt: "Ich esse Brot. Ich trinke Wasser.",
        choices: [
          "パンを食べます。水を飲みます。",
          "パンを飲みます。水を食べます。",
          "パンと水をください。",
          "水を飲みます。",
        ],
        answer: "パンを食べます。水を飲みます。",
        answerKana: "パンをたべます。みずをのみます。",
        answerRomaji: "pan o tabemasu. mizu o nomimasu",
        answerGerman: "Ich esse Brot. Ich trinke Wasser.",
        exampleJapanese: "パンを食べます。水を飲みます。",
        exampleKana: "パンをたべます。みずをのみます。",
        exampleGerman: "Ich esse Brot. Ich trinke Wasser.",
      },
    ],
    {
      speechText: "パンを食べます。",
      speechKana: "パンをたべます。",
      speechRomaji: "pan o tabemasu",
      speechGerman: "Ich esse Brot.",
      acceptedTranscripts: ["パンを食べます", "ぱんをたべます"],
    }
  ),
};
