import type { QuizQuestion } from "@/types/learning";
import { defineSubQuest } from "./shared";

/**
 * Hand-authored Sub Quests for the Freunde words (Block 1, A0–A1). Learning focus of the
 * category: Person mit に treffen (〜に会います), mit jemandem sprechen (〜と話します),
 * 明日 als Zeitangabe, and „〜が好きです“ mit が statt を.
 */
export const freundeSubQuests: Record<string, QuizQuestion[]> = {
  friend: defineSubQuest(
    "friend",
    "freunde",
    [
      {
        step: "meaning",
        type: "meaning-choice",
        instruction: "Wähle die richtige Bedeutung.",
        prompt: "友だち",
        choices: ["Freund/Freundin", "Lehrer/Lehrerin", "Schule", "heute"],
        answer: "Freund/Freundin",
      },
      {
        step: "word",
        type: "japanese-choice",
        instruction: "Wähle das passende japanische Wort.",
        prompt: "Freund/Freundin",
        choices: ["友だち", "先生", "明日", "学校"],
        answer: "友だち",
      },
      {
        step: "particle",
        type: "particle-choice",
        instruction: "Wähle die passende Partikel.",
        prompt: "„Ich treffe einen Freund.“\n友だち____会います。",
        choices: ["に", "を", "で", "は"],
        answer: "に",
        exampleJapanese: "友だちに会います。",
        exampleKana: "ともだちにあいます。",
        exampleGerman: "Ich treffe einen Freund.",
      },
      {
        step: "verb",
        type: "fill-blank",
        instruction: "Ergänze den Satz.",
        prompt: "„Ich spreche mit einem Freund.“\n友だちと____。",
        choices: ["話します", "食べます", "飲みます", "行きます"],
        answer: "話します",
        exampleJapanese: "友だちと話します。",
        exampleKana: "ともだちとはなします。",
        exampleGerman: "Ich spreche mit einem Freund.",
      },
      {
        step: "sentence-meaning",
        type: "sentence-meaning-choice",
        instruction: "Was bedeutet dieser Satz?",
        prompt: "友だちに会います。",
        choices: [
          "Ich treffe einen Freund.",
          "Ich spreche mit einem Freund.",
          "Ich mag meine Freunde.",
          "Morgen treffe ich einen Freund.",
        ],
        answer: "Ich treffe einen Freund.",
        exampleJapanese: "友だちに会います。",
        exampleKana: "ともだちにあいます。",
        exampleGerman: "Ich treffe einen Freund.",
      },
      {
        step: "phrase",
        type: "phrase-choice",
        instruction: "Wähle den natürlichen japanischen Satz.",
        prompt: "Ich mag meine Freunde.",
        choices: ["友だちが好きです。", "友だちに会います。", "友だちと話します。", "友だちです。"],
        answer: "友だちが好きです。",
        answerKana: "ともだちがすきです。",
        answerRomaji: "tomodachi ga suki desu",
        answerGerman: "Ich mag meine Freunde.",
        exampleJapanese: "友だちが好きです。",
        exampleKana: "ともだちがすきです。",
        exampleGerman: "Ich mag meine Freunde.",
      },
      {
        step: "mistake",
        type: "mistake-choice",
        instruction: "Achtung, Verwechslungsgefahr: Wähle den richtigen Satz.",
        prompt: "Person mit に: „Ich treffe einen Freund.“",
        choices: ["友だちに会います。", "友だちを会います。", "友だちで会います。", "友だちは会います。"],
        answer: "友だちに会います。",
        exampleJapanese: "友だちに会います。",
        exampleKana: "ともだちにあいます。",
        exampleGerman: "Ich treffe einen Freund.",
      },
      {
        step: "combo",
        type: "phrase-choice",
        instruction: "Wähle den natürlichen japanischen Satz.",
        prompt: "Morgen treffe ich einen Freund.",
        choices: [
          "明日、友だちに会います。",
          "今日、友だちに会います。",
          "友だちに会います。",
          "明日、友だちと話します。",
        ],
        answer: "明日、友だちに会います。",
        answerKana: "あした、ともだちにあいます。",
        answerRomaji: "ashita, tomodachi ni aimasu",
        answerGerman: "Morgen treffe ich einen Freund.",
        exampleJapanese: "明日、友だちに会います。",
        exampleKana: "あした、ともだちにあいます。",
        exampleGerman: "Morgen treffe ich einen Freund.",
      },
      {
        step: "mini",
        type: "sentence-meaning-choice",
        instruction: "Mini Challenge: Was bedeutet dieser Satz?",
        prompt: "明日、友だちと日本語を話します。",
        choices: [
          "Morgen spreche ich mit einem Freund Japanisch.",
          "Morgen treffe ich einen Freund.",
          "Ich spreche mit einem Freund.",
          "Morgen lernt mein Freund Japanisch.",
        ],
        answer: "Morgen spreche ich mit einem Freund Japanisch.",
        exampleJapanese: "明日、友だちと日本語を話します。",
        exampleKana: "あした、ともだちとにほんごをはなします。",
        exampleGerman: "Morgen spreche ich mit einem Freund Japanisch.",
      },
    ],
    {
      speechText: "友だちに会います。",
      speechKana: "ともだちにあいます。",
      speechRomaji: "tomodachi ni aimasu",
      speechGerman: "Ich treffe einen Freund.",
      acceptedTranscripts: ["友だちに会います", "友達に会います", "ともだちにあいます"],
    }
  ),

  meet: defineSubQuest(
    "meet",
    "freunde",
    [
      {
        step: "meaning",
        type: "meaning-choice",
        instruction: "Wähle die richtige Bedeutung.",
        prompt: "会う",
        choices: ["treffen", "sprechen", "gehen", "mögen / gern haben"],
        answer: "treffen",
      },
      {
        step: "word",
        type: "japanese-choice",
        instruction: "Wähle das passende japanische Wort.",
        prompt: "treffen",
        choices: ["会う", "話す", "行く", "好き"],
        answer: "会う",
      },
      {
        step: "particle",
        type: "particle-choice",
        instruction: "Wähle die passende Partikel.",
        prompt: "„Morgen treffe ich einen Freund.“\n明日、友だち____会います。",
        choices: ["に", "を", "で", "は"],
        answer: "に",
        exampleJapanese: "明日、友だちに会います。",
        exampleKana: "あした、ともだちにあいます。",
        exampleGerman: "Morgen treffe ich einen Freund.",
      },
      {
        step: "verb",
        type: "fill-blank",
        instruction: "Ergänze den Satz.",
        prompt: "„Ich treffe einen Freund.“\n友だちに____。",
        choices: ["会います", "話します", "行きます", "食べます"],
        answer: "会います",
        exampleJapanese: "友だちに会います。",
        exampleKana: "ともだちにあいます。",
        exampleGerman: "Ich treffe einen Freund.",
      },
      {
        step: "sentence-meaning",
        type: "sentence-meaning-choice",
        instruction: "Was bedeutet dieser Satz?",
        prompt: "明日、友だちに会います。",
        choices: [
          "Morgen treffe ich einen Freund.",
          "Heute treffe ich einen Freund.",
          "Ich treffe einen Freund.",
          "Morgen spreche ich mit einem Freund.",
        ],
        answer: "Morgen treffe ich einen Freund.",
        exampleJapanese: "明日、友だちに会います。",
        exampleKana: "あした、ともだちにあいます。",
        exampleGerman: "Morgen treffe ich einen Freund.",
      },
      {
        step: "phrase",
        type: "phrase-choice",
        instruction: "Wähle den natürlichen japanischen Satz.",
        prompt: "Heute treffe ich einen Freund.",
        choices: [
          "今日、友だちに会います。",
          "明日、友だちに会います。",
          "友だちに会います。",
          "今日、友だちと話します。",
        ],
        answer: "今日、友だちに会います。",
        answerKana: "きょう、ともだちにあいます。",
        answerRomaji: "kyou, tomodachi ni aimasu",
        answerGerman: "Heute treffe ich einen Freund.",
        exampleJapanese: "今日、友だちに会います。",
        exampleKana: "きょう、ともだちにあいます。",
        exampleGerman: "Heute treffe ich einen Freund.",
      },
      {
        step: "mistake",
        type: "mistake-choice",
        instruction: "Achtung, Verwechslungsgefahr: Wähle den richtigen Satz.",
        prompt: "Treffen, nicht sprechen: „Ich treffe einen Freund.“",
        choices: ["友だちに会います。", "友だちと話します。", "友だちに行きます。", "友だちを会います。"],
        answer: "友だちに会います。",
        exampleJapanese: "友だちに会います。",
        exampleKana: "ともだちにあいます。",
        exampleGerman: "Ich treffe einen Freund.",
      },
      {
        step: "combo",
        type: "phrase-choice",
        instruction: "Wähle den natürlichen japanischen Satz.",
        prompt: "Ich treffe den Lehrer.",
        choices: ["先生に会います。", "先生と話します。", "先生に行きます。", "友だちに会います。"],
        answer: "先生に会います。",
        answerKana: "せんせいにあいます。",
        answerRomaji: "sensei ni aimasu",
        answerGerman: "Ich treffe den Lehrer.",
        exampleJapanese: "先生に会います。",
        exampleKana: "せんせいにあいます。",
        exampleGerman: "Ich treffe den Lehrer.",
      },
      {
        step: "mini",
        type: "sentence-meaning-choice",
        instruction: "Mini Challenge: Was bedeutet dieser Satz?",
        prompt: "明日、駅で友だちに会います。",
        choices: [
          "Morgen treffe ich am Bahnhof einen Freund.",
          "Heute treffe ich am Bahnhof einen Freund.",
          "Morgen gehe ich mit einem Freund zum Bahnhof.",
          "Morgen spreche ich am Bahnhof mit einem Freund.",
        ],
        answer: "Morgen treffe ich am Bahnhof einen Freund.",
        exampleJapanese: "明日、駅で友だちに会います。",
        exampleKana: "あした、えきでともだちにあいます。",
        exampleGerman: "Morgen treffe ich am Bahnhof einen Freund.",
      },
    ],
    {
      speechText: "明日、友だちに会います。",
      speechKana: "あした、ともだちにあいます。",
      speechRomaji: "ashita, tomodachi ni aimasu",
      speechGerman: "Morgen treffe ich einen Freund.",
      acceptedTranscripts: ["明日友だちに会います", "明日友達に会います", "あしたともだちにあいます"],
    }
  ),

  talk: defineSubQuest(
    "talk",
    "freunde",
    [
      {
        step: "meaning",
        type: "meaning-choice",
        instruction: "Wähle die richtige Bedeutung.",
        prompt: "話す",
        choices: ["sprechen", "treffen", "lernen", "essen"],
        answer: "sprechen",
      },
      {
        step: "word",
        type: "japanese-choice",
        instruction: "Wähle das passende japanische Wort.",
        prompt: "sprechen",
        choices: ["話す", "会う", "勉強する", "食べる"],
        answer: "話す",
      },
      {
        step: "particle",
        type: "particle-choice",
        instruction: "Wähle die passende Partikel.",
        prompt: "„Ich spreche mit einem Freund.“\n友だち____話します。",
        choices: ["と", "を", "で", "は"],
        answer: "と",
        exampleJapanese: "友だちと話します。",
        exampleKana: "ともだちとはなします。",
        exampleGerman: "Ich spreche mit einem Freund.",
      },
      {
        step: "verb",
        type: "fill-blank",
        instruction: "Ergänze den Satz.",
        prompt: "„Ich spreche Japanisch.“\n日本語を____。",
        choices: ["話します", "勉強します", "会います", "飲みます"],
        answer: "話します",
        exampleJapanese: "日本語を話します。",
        exampleKana: "にほんごをはなします。",
        exampleGerman: "Ich spreche Japanisch.",
      },
      {
        step: "sentence-meaning",
        type: "sentence-meaning-choice",
        instruction: "Was bedeutet dieser Satz?",
        prompt: "友だちと話します。",
        choices: [
          "Ich spreche mit einem Freund.",
          "Ich treffe einen Freund.",
          "Ich spreche Japanisch.",
          "Ich mag meine Freunde.",
        ],
        answer: "Ich spreche mit einem Freund.",
        exampleJapanese: "友だちと話します。",
        exampleKana: "ともだちとはなします。",
        exampleGerman: "Ich spreche mit einem Freund.",
      },
      {
        step: "phrase",
        type: "phrase-choice",
        instruction: "Wähle den natürlichen japanischen Satz.",
        prompt: "Ich spreche mit dem Lehrer.",
        choices: ["先生と話します。", "先生に会います。", "友だちと話します。", "先生と勉強します。"],
        answer: "先生と話します。",
        answerKana: "せんせいとはなします。",
        answerRomaji: "sensei to hanashimasu",
        answerGerman: "Ich spreche mit dem Lehrer.",
        exampleJapanese: "先生と話します。",
        exampleKana: "せんせいとはなします。",
        exampleGerman: "Ich spreche mit dem Lehrer.",
      },
      {
        step: "mistake",
        type: "mistake-choice",
        instruction: "Achtung, Verwechslungsgefahr: Wähle den richtigen Satz.",
        prompt: "Mit jemandem sprechen = と: „Ich spreche mit einem Freund.“",
        choices: ["友だちと話します。", "友だちを話します。", "友だちに食べます。", "友だちが話します。"],
        answer: "友だちと話します。",
        exampleJapanese: "友だちと話します。",
        exampleKana: "ともだちとはなします。",
        exampleGerman: "Ich spreche mit einem Freund.",
      },
      {
        step: "combo",
        type: "phrase-choice",
        instruction: "Wähle den natürlichen japanischen Satz.",
        prompt: "Morgen spreche ich mit einem Freund.",
        choices: [
          "明日、友だちと話します。",
          "今日、友だちと話します。",
          "明日、友だちに会います。",
          "友だちと話します。",
        ],
        answer: "明日、友だちと話します。",
        answerKana: "あした、ともだちとはなします。",
        answerRomaji: "ashita, tomodachi to hanashimasu",
        answerGerman: "Morgen spreche ich mit einem Freund.",
        exampleJapanese: "明日、友だちと話します。",
        exampleKana: "あした、ともだちとはなします。",
        exampleGerman: "Morgen spreche ich mit einem Freund.",
      },
      {
        step: "mini",
        type: "sentence-meaning-choice",
        instruction: "Mini Challenge: Was bedeutet dieser Satz?",
        prompt: "学校で友だちと話します。",
        choices: [
          "Ich spreche in der Schule mit einem Freund.",
          "Ich gehe mit einem Freund zur Schule.",
          "Ich spreche in der Schule mit dem Lehrer.",
          "Ich lerne in der Schule mit einem Freund.",
        ],
        answer: "Ich spreche in der Schule mit einem Freund.",
        exampleJapanese: "学校で友だちと話します。",
        exampleKana: "がっこうでともだちとはなします。",
        exampleGerman: "Ich spreche in der Schule mit einem Freund.",
      },
    ],
    {
      speechText: "友だちと話します。",
      speechKana: "ともだちとはなします。",
      speechRomaji: "tomodachi to hanashimasu",
      speechGerman: "Ich spreche mit einem Freund.",
      acceptedTranscripts: ["友だちと話します", "友達と話します", "ともだちとはなします"],
    }
  ),

  tomorrow: defineSubQuest(
    "tomorrow",
    "freunde",
    [
      {
        step: "meaning",
        type: "meaning-choice",
        instruction: "Wähle die richtige Bedeutung.",
        prompt: "明日",
        choices: ["morgen", "heute", "Freund/Freundin", "treffen"],
        answer: "morgen",
      },
      {
        step: "word",
        type: "japanese-choice",
        instruction: "Wähle das passende japanische Wort.",
        prompt: "morgen",
        choices: ["明日", "今日", "友だち", "先生"],
        answer: "明日",
      },
      {
        step: "particle",
        type: "particle-choice",
        instruction: "Wähle die passende Partikel.",
        prompt: "„Morgen treffe ich einen Freund.“\n明日、友だち____会います。",
        choices: ["に", "を", "で", "は"],
        answer: "に",
        exampleJapanese: "明日、友だちに会います。",
        exampleKana: "あした、ともだちにあいます。",
        exampleGerman: "Morgen treffe ich einen Freund.",
      },
      {
        step: "word-blank",
        type: "fill-blank",
        instruction: "Ergänze den Satz.",
        prompt: "„Morgen treffe ich einen Freund.“\n____、友だちに会います。",
        choices: ["明日", "今日", "学校", "先生"],
        answer: "明日",
        exampleJapanese: "明日、友だちに会います。",
        exampleKana: "あした、ともだちにあいます。",
        exampleGerman: "Morgen treffe ich einen Freund.",
      },
      {
        step: "sentence-meaning",
        type: "sentence-meaning-choice",
        instruction: "Was bedeutet dieser Satz?",
        prompt: "明日、友だちに会います。",
        choices: [
          "Morgen treffe ich einen Freund.",
          "Heute treffe ich einen Freund.",
          "Morgen spreche ich mit einem Freund.",
          "Ich treffe einen Freund.",
        ],
        answer: "Morgen treffe ich einen Freund.",
        exampleJapanese: "明日、友だちに会います。",
        exampleKana: "あした、ともだちにあいます。",
        exampleGerman: "Morgen treffe ich einen Freund.",
      },
      {
        step: "phrase",
        type: "phrase-choice",
        instruction: "Wähle den natürlichen japanischen Satz.",
        prompt: "Morgen gehe ich zur Schule.",
        choices: [
          "明日、学校に行きます。",
          "今日、学校に行きます。",
          "明日、学校で行きます。",
          "学校に行きます。",
        ],
        answer: "明日、学校に行きます。",
        answerKana: "あした、がっこうにいきます。",
        answerRomaji: "ashita, gakkou ni ikimasu",
        answerGerman: "Morgen gehe ich zur Schule.",
        exampleJapanese: "明日、学校に行きます。",
        exampleKana: "あした、がっこうにいきます。",
        exampleGerman: "Morgen gehe ich zur Schule.",
      },
      {
        step: "mistake",
        type: "mistake-choice",
        instruction: "Achtung, Verwechslungsgefahr: Wähle den richtigen Satz.",
        prompt: "Morgen, nicht heute: „Morgen lerne ich Japanisch.“",
        choices: [
          "明日、日本語を勉強します。",
          "今日、日本語を勉強します。",
          "日本語を勉強します。",
          "明日、日本語を話します。",
        ],
        answer: "明日、日本語を勉強します。",
        exampleJapanese: "明日、日本語を勉強します。",
        exampleKana: "あした、にほんごをべんきょうします。",
        exampleGerman: "Morgen lerne ich Japanisch.",
      },
      {
        step: "combo",
        type: "sentence-meaning-choice",
        instruction: "Was bedeutet dieser Satz?",
        prompt: "明日、友だちと話します。",
        choices: [
          "Morgen spreche ich mit einem Freund.",
          "Heute spreche ich mit einem Freund.",
          "Morgen treffe ich einen Freund.",
          "Ich spreche mit einem Freund.",
        ],
        answer: "Morgen spreche ich mit einem Freund.",
        exampleJapanese: "明日、友だちと話します。",
        exampleKana: "あした、ともだちとはなします。",
        exampleGerman: "Morgen spreche ich mit einem Freund.",
      },
      {
        step: "mini",
        type: "phrase-choice",
        instruction: "Mini Challenge: Wähle den natürlichen japanischen Satz.",
        prompt: "Morgen treffe ich am Bahnhof einen Freund.",
        choices: [
          "明日、駅で友だちに会います。",
          "今日、駅で友だちに会います。",
          "明日、友だちに会います。",
          "明日、駅に行きます。",
        ],
        answer: "明日、駅で友だちに会います。",
        answerKana: "あした、えきでともだちにあいます。",
        answerRomaji: "ashita, eki de tomodachi ni aimasu",
        answerGerman: "Morgen treffe ich am Bahnhof einen Freund.",
        exampleJapanese: "明日、駅で友だちに会います。",
        exampleKana: "あした、えきでともだちにあいます。",
        exampleGerman: "Morgen treffe ich am Bahnhof einen Freund.",
      },
    ],
    {
      speechText: "明日、友だちに会います。",
      speechKana: "あした、ともだちにあいます。",
      speechRomaji: "ashita, tomodachi ni aimasu",
      speechGerman: "Morgen treffe ich einen Freund.",
      acceptedTranscripts: ["明日友だちに会います", "明日友達に会います", "あしたともだちにあいます"],
    }
  ),

  like: defineSubQuest(
    "like",
    "freunde",
    [
      {
        step: "meaning",
        type: "meaning-choice",
        instruction: "Wähle die richtige Bedeutung.",
        prompt: "好き",
        choices: ["mögen / gern haben", "treffen", "sprechen", "lernen"],
        answer: "mögen / gern haben",
      },
      {
        step: "word",
        type: "japanese-choice",
        instruction: "Wähle das passende japanische Wort.",
        prompt: "mögen / gern haben",
        choices: ["好き", "会う", "話す", "勉強する"],
        answer: "好き",
      },
      {
        step: "particle",
        type: "particle-choice",
        instruction: "Wähle die passende Partikel.",
        prompt: "„Ich mag Japanisch.“\n日本語____好きです。",
        choices: ["が", "を", "に", "と"],
        answer: "が",
        exampleJapanese: "日本語が好きです。",
        exampleKana: "にほんごがすきです。",
        exampleGerman: "Ich mag Japanisch.",
      },
      {
        step: "word-blank",
        type: "fill-blank",
        instruction: "Ergänze den Satz.",
        prompt: "„Ich mag meine Freunde.“\n友だちが____です。",
        choices: ["好き", "どこ", "近い", "遠い"],
        answer: "好き",
        exampleJapanese: "友だちが好きです。",
        exampleKana: "ともだちがすきです。",
        exampleGerman: "Ich mag meine Freunde.",
      },
      {
        step: "sentence-meaning",
        type: "sentence-meaning-choice",
        instruction: "Was bedeutet dieser Satz?",
        prompt: "友だちが好きです。",
        choices: [
          "Ich mag meine Freunde.",
          "Ich treffe einen Freund.",
          "Ich mag Japanisch.",
          "Ich spreche mit einem Freund.",
        ],
        answer: "Ich mag meine Freunde.",
        exampleJapanese: "友だちが好きです。",
        exampleKana: "ともだちがすきです。",
        exampleGerman: "Ich mag meine Freunde.",
      },
      {
        step: "phrase",
        type: "phrase-choice",
        instruction: "Wähle den natürlichen japanischen Satz.",
        prompt: "Ich mag Kaffee.",
        choices: ["コーヒーが好きです。", "コーヒーを好きです。", "コーヒーを飲みます。", "コーヒーです。"],
        answer: "コーヒーが好きです。",
        answerKana: "コーヒーがすきです。",
        answerRomaji: "koohii ga suki desu",
        answerGerman: "Ich mag Kaffee.",
        exampleJapanese: "コーヒーが好きです。",
        exampleKana: "コーヒーがすきです。",
        exampleGerman: "Ich mag Kaffee.",
      },
      {
        step: "mistake",
        type: "mistake-choice",
        instruction: "Achtung, Verwechslungsgefahr: Wähle den richtigen Satz.",
        prompt: "好き braucht が, nicht を: „Ich mag Japanisch.“",
        choices: [
          "日本語が好きです。",
          "日本語を好きです。",
          "日本語に好きです。",
          "日本語は好きですか。",
        ],
        answer: "日本語が好きです。",
        exampleJapanese: "日本語が好きです。",
        exampleKana: "にほんごがすきです。",
        exampleGerman: "Ich mag Japanisch.",
      },
      {
        step: "combo",
        type: "sentence-meaning-choice",
        instruction: "Was bedeutet dieser Satz?",
        prompt: "パンが好きです。",
        choices: ["Ich mag Brot.", "Ich esse Brot.", "Ich mag Kaffee.", "Brot bitte."],
        answer: "Ich mag Brot.",
        exampleJapanese: "パンが好きです。",
        exampleKana: "パンがすきです。",
        exampleGerman: "Ich mag Brot.",
      },
      {
        step: "mini",
        type: "sentence-meaning-choice",
        instruction: "Mini Challenge: Was bedeutet dieser Satz?",
        prompt: "日本語が好きです。今日、日本語を勉強します。",
        choices: [
          "Ich mag Japanisch. Heute lerne ich Japanisch.",
          "Ich mag Japanisch. Heute spreche ich Japanisch.",
          "Ich mag die Schule. Heute lerne ich Japanisch.",
          "Heute lerne ich Japanisch.",
        ],
        answer: "Ich mag Japanisch. Heute lerne ich Japanisch.",
        exampleJapanese: "日本語が好きです。今日、日本語を勉強します。",
        exampleKana: "にほんごがすきです。きょう、にほんごをべんきょうします。",
        exampleGerman: "Ich mag Japanisch. Heute lerne ich Japanisch.",
      },
    ],
    {
      speechText: "日本語が好きです。",
      speechKana: "にほんごがすきです。",
      speechRomaji: "nihongo ga suki desu",
      speechGerman: "Ich mag Japanisch.",
      acceptedTranscripts: ["日本語が好きです", "にほんごがすきです"],
    }
  ),
};
