import type { QuizQuestion } from "@/types/learning";
import { defineSubQuest } from "./shared";

/**
 * Hand-authored Sub Quests for the Reise words (Block 1, A0–A1). Learning focus of the
 * category: nach dem Weg fragen („〜はどこですか“), Ziel mit に und Verkehrsmittel mit で,
 * Richtungen/Entfernung mit „〜です“, and höfliches Ansprechen mit „すみません“.
 */
export const reiseSubQuests: Record<string, QuizQuestion[]> = {
  station: defineSubQuest(
    "station",
    "reise",
    [
      {
        step: "meaning",
        type: "meaning-choice",
        instruction: "Wähle die richtige Bedeutung.",
        prompt: "駅",
        choices: ["Bahnhof", "Hotel", "Zug", "Toilette"],
        answer: "Bahnhof",
      },
      {
        step: "word",
        type: "japanese-choice",
        instruction: "Wähle das passende japanische Wort.",
        prompt: "Bahnhof",
        choices: ["駅", "ホテル", "電車", "トイレ"],
        answer: "駅",
      },
      {
        step: "particle",
        type: "particle-choice",
        instruction: "Wähle die passende Partikel.",
        prompt: "„Wo ist der Bahnhof?“\n駅____どこですか。",
        choices: ["は", "を", "に", "で"],
        answer: "は",
        exampleJapanese: "駅はどこですか。",
        exampleKana: "えきはどこですか。",
        exampleGerman: "Wo ist der Bahnhof?",
      },
      {
        step: "verb",
        type: "fill-blank",
        instruction: "Ergänze den Satz.",
        prompt: "„Ich gehe zum Bahnhof.“\n駅に____。",
        choices: ["行きます", "飲みます", "食べます", "ください"],
        answer: "行きます",
        exampleJapanese: "駅に行きます。",
        exampleKana: "えきにいきます。",
        exampleGerman: "Ich gehe zum Bahnhof.",
      },
      {
        step: "sentence-meaning",
        type: "sentence-meaning-choice",
        instruction: "Was bedeutet dieser Satz?",
        prompt: "駅は近いです。",
        choices: [
          "Der Bahnhof ist nah.",
          "Der Bahnhof ist weit entfernt.",
          "Wo ist der Bahnhof?",
          "Der Bahnhof ist rechts.",
        ],
        answer: "Der Bahnhof ist nah.",
        exampleJapanese: "駅は近いです。",
        exampleKana: "えきはちかいです。",
        exampleGerman: "Der Bahnhof ist nah.",
      },
      {
        step: "phrase",
        type: "phrase-choice",
        instruction: "Wähle den natürlichen japanischen Satz.",
        prompt: "Wo ist der Bahnhof?",
        choices: ["駅はどこですか。", "駅は近いです。", "駅に行きます。", "トイレはどこですか。"],
        answer: "駅はどこですか。",
        answerKana: "えきはどこですか。",
        answerRomaji: "eki wa doko desu ka",
        answerGerman: "Wo ist der Bahnhof?",
        exampleJapanese: "駅はどこですか。",
        exampleKana: "えきはどこですか。",
        exampleGerman: "Wo ist der Bahnhof?",
      },
      {
        step: "mistake",
        type: "mistake-choice",
        instruction: "Achtung, Verwechslungsgefahr: Wähle den richtigen Satz.",
        prompt: "Ziel mit に: „Ich gehe zum Bahnhof.“",
        choices: ["駅に行きます。", "駅で行きます。", "駅を行きます。", "駅は行きます。"],
        answer: "駅に行きます。",
        exampleJapanese: "駅に行きます。",
        exampleKana: "えきにいきます。",
        exampleGerman: "Ich gehe zum Bahnhof.",
      },
      {
        step: "combo",
        type: "phrase-choice",
        instruction: "Wähle den natürlichen japanischen Satz.",
        prompt: "Ich fahre mit dem Zug zum Bahnhof.",
        choices: ["電車で駅に行きます。", "駅で電車に行きます。", "電車に駅で行きます。", "駅に行きます。"],
        answer: "電車で駅に行きます。",
        answerKana: "でんしゃでえきにいきます。",
        answerRomaji: "densha de eki ni ikimasu",
        answerGerman: "Ich fahre mit dem Zug zum Bahnhof.",
        exampleJapanese: "電車で駅に行きます。",
        exampleKana: "でんしゃでえきにいきます。",
        exampleGerman: "Ich fahre mit dem Zug zum Bahnhof.",
      },
      {
        step: "mini",
        type: "phrase-choice",
        instruction: "Mini Challenge: Wähle den vollständigen, höflichen Satz.",
        prompt: "Entschuldigung, wo ist der Bahnhof?",
        choices: [
          "すみません、駅はどこですか。",
          "すみません、トイレはどこですか。",
          "駅はどこですか。",
          "駅は近いです。",
        ],
        answer: "すみません、駅はどこですか。",
        answerKana: "すみません、えきはどこですか。",
        answerRomaji: "sumimasen, eki wa doko desu ka",
        answerGerman: "Entschuldigung, wo ist der Bahnhof?",
        exampleJapanese: "すみません、駅はどこですか。",
        exampleKana: "すみません、えきはどこですか。",
        exampleGerman: "Entschuldigung, wo ist der Bahnhof?",
      },
    ],
    {
      speechText: "すみません、駅はどこですか。",
      speechKana: "すみません、えきはどこですか。",
      speechRomaji: "sumimasen, eki wa doko desu ka",
      speechGerman: "Entschuldigung, wo ist der Bahnhof?",
      acceptedTranscripts: ["すみません駅はどこですか", "すみませんえきはどこですか"],
    }
  ),

  hotel: defineSubQuest(
    "hotel",
    "reise",
    [
      {
        step: "meaning",
        type: "meaning-choice",
        instruction: "Wähle die richtige Bedeutung.",
        prompt: "ホテル",
        choices: ["Hotel", "Bahnhof", "Zug", "Toilette"],
        answer: "Hotel",
      },
      {
        step: "word",
        type: "japanese-choice",
        instruction: "Wähle das passende japanische Wort.",
        prompt: "Hotel",
        choices: ["ホテル", "駅", "電車", "トイレ"],
        answer: "ホテル",
      },
      {
        step: "particle",
        type: "particle-choice",
        instruction: "Wähle die passende Partikel.",
        prompt: "„Ich gehe zum Hotel.“\nホテル____行きます。",
        choices: ["に", "を", "と", "は"],
        answer: "に",
        exampleJapanese: "ホテルに行きます。",
        exampleKana: "ホテルにいきます。",
        exampleGerman: "Ich gehe zum Hotel.",
      },
      {
        step: "adjective",
        type: "fill-blank",
        instruction: "Ergänze den Satz.",
        prompt: "„Das Hotel ist weit entfernt.“\nホテルは____です。",
        choices: ["遠い", "近い", "右", "左"],
        answer: "遠い",
        exampleJapanese: "ホテルは遠いです。",
        exampleKana: "ホテルはとおいです。",
        exampleGerman: "Das Hotel ist weit entfernt.",
      },
      {
        step: "sentence-meaning",
        type: "sentence-meaning-choice",
        instruction: "Was bedeutet dieser Satz?",
        prompt: "ホテルはどこですか。",
        choices: [
          "Wo ist das Hotel?",
          "Wo ist der Bahnhof?",
          "Das Hotel ist nah.",
          "Ich gehe zum Hotel.",
        ],
        answer: "Wo ist das Hotel?",
        exampleJapanese: "ホテルはどこですか。",
        exampleKana: "ホテルはどこですか。",
        exampleGerman: "Wo ist das Hotel?",
      },
      {
        step: "phrase",
        type: "phrase-choice",
        instruction: "Wähle den natürlichen japanischen Satz.",
        prompt: "Das Hotel ist nah.",
        choices: ["ホテルは近いです。", "ホテルは遠いです。", "駅は近いです。", "ホテルに行きます。"],
        answer: "ホテルは近いです。",
        answerKana: "ホテルはちかいです。",
        answerRomaji: "hoteru wa chikai desu",
        answerGerman: "Das Hotel ist nah.",
        exampleJapanese: "ホテルは近いです。",
        exampleKana: "ホテルはちかいです。",
        exampleGerman: "Das Hotel ist nah.",
      },
      {
        step: "mistake",
        type: "mistake-choice",
        instruction: "Achtung, Verwechslungsgefahr: Wähle den richtigen Satz.",
        prompt: "Ziel mit に: „Ich gehe zum Hotel.“",
        choices: ["ホテルに行きます。", "ホテルで行きます。", "ホテルを行きます。", "ホテルに食べます。"],
        answer: "ホテルに行きます。",
        exampleJapanese: "ホテルに行きます。",
        exampleKana: "ホテルにいきます。",
        exampleGerman: "Ich gehe zum Hotel.",
      },
      {
        step: "combo",
        type: "phrase-choice",
        instruction: "Wähle den natürlichen japanischen Satz.",
        prompt: "Ich fahre mit dem Zug zum Hotel.",
        choices: [
          "電車でホテルに行きます。",
          "ホテルで電車に行きます。",
          "電車をホテルに行きます。",
          "ホテルに行きます。",
        ],
        answer: "電車でホテルに行きます。",
        answerKana: "でんしゃでホテルにいきます。",
        answerRomaji: "densha de hoteru ni ikimasu",
        answerGerman: "Ich fahre mit dem Zug zum Hotel.",
        exampleJapanese: "電車でホテルに行きます。",
        exampleKana: "でんしゃでホテルにいきます。",
        exampleGerman: "Ich fahre mit dem Zug zum Hotel.",
      },
      {
        step: "mini",
        type: "phrase-choice",
        instruction: "Mini Challenge: Wähle den vollständigen, höflichen Satz.",
        prompt: "Entschuldigung, wo ist das Hotel?",
        choices: [
          "すみません、ホテルはどこですか。",
          "すみません、駅はどこですか。",
          "ホテルはどこですか。",
          "ホテルは近いです。",
        ],
        answer: "すみません、ホテルはどこですか。",
        answerKana: "すみません、ホテルはどこですか。",
        answerRomaji: "sumimasen, hoteru wa doko desu ka",
        answerGerman: "Entschuldigung, wo ist das Hotel?",
        exampleJapanese: "すみません、ホテルはどこですか。",
        exampleKana: "すみません、ホテルはどこですか。",
        exampleGerman: "Entschuldigung, wo ist das Hotel?",
      },
    ],
    {
      speechText: "ホテルに行きます。",
      speechKana: "ホテルにいきます。",
      speechRomaji: "hoteru ni ikimasu",
      speechGerman: "Ich gehe zum Hotel.",
      acceptedTranscripts: ["ホテルに行きます", "ほてるにいきます"],
    }
  ),

  train: defineSubQuest(
    "train",
    "reise",
    [
      {
        step: "meaning",
        type: "meaning-choice",
        instruction: "Wähle die richtige Bedeutung.",
        prompt: "電車",
        choices: ["Zug", "Bahnhof", "Hotel", "Toilette"],
        answer: "Zug",
      },
      {
        step: "word",
        type: "japanese-choice",
        instruction: "Wähle das passende japanische Wort.",
        prompt: "Zug",
        choices: ["電車", "駅", "ホテル", "トイレ"],
        answer: "電車",
      },
      {
        step: "particle",
        type: "particle-choice",
        instruction: "Wähle die passende Partikel.",
        prompt: "„Ich fahre mit dem Zug.“\n電車____行きます。",
        choices: ["で", "に", "を", "は"],
        answer: "で",
        exampleJapanese: "電車で行きます。",
        exampleKana: "でんしゃでいきます。",
        exampleGerman: "Ich fahre mit dem Zug.",
      },
      {
        step: "verb",
        type: "fill-blank",
        instruction: "Ergänze den Satz.",
        prompt: "„Ich fahre mit dem Zug zum Bahnhof.“\n電車で駅に____。",
        choices: ["行きます", "飲みます", "食べます", "ください"],
        answer: "行きます",
        exampleJapanese: "電車で駅に行きます。",
        exampleKana: "でんしゃでえきにいきます。",
        exampleGerman: "Ich fahre mit dem Zug zum Bahnhof.",
      },
      {
        step: "sentence-meaning",
        type: "sentence-meaning-choice",
        instruction: "Was bedeutet dieser Satz?",
        prompt: "電車で行きます。",
        choices: [
          "Ich fahre mit dem Zug.",
          "Ich gehe zum Bahnhof.",
          "Der Zug ist nah.",
          "Ich fahre mit dem Zug zum Hotel.",
        ],
        answer: "Ich fahre mit dem Zug.",
        exampleJapanese: "電車で行きます。",
        exampleKana: "でんしゃでいきます。",
        exampleGerman: "Ich fahre mit dem Zug.",
      },
      {
        step: "phrase",
        type: "phrase-choice",
        instruction: "Wähle den natürlichen japanischen Satz.",
        prompt: "Ich fahre mit dem Zug zum Hotel.",
        choices: [
          "電車でホテルに行きます。",
          "ホテルで電車に行きます。",
          "電車にホテルで行きます。",
          "ホテルに行きます。",
        ],
        answer: "電車でホテルに行きます。",
        answerKana: "でんしゃでホテルにいきます。",
        answerRomaji: "densha de hoteru ni ikimasu",
        answerGerman: "Ich fahre mit dem Zug zum Hotel.",
        exampleJapanese: "電車でホテルに行きます。",
        exampleKana: "でんしゃでホテルにいきます。",
        exampleGerman: "Ich fahre mit dem Zug zum Hotel.",
      },
      {
        step: "mistake",
        type: "mistake-choice",
        instruction: "Achtung, Verwechslungsgefahr: Wähle den richtigen Satz.",
        prompt: "Verkehrsmittel mit で: „Ich fahre mit dem Zug.“",
        choices: ["電車で行きます。", "電車に行きます。", "電車を行きます。", "電車は行きます。"],
        answer: "電車で行きます。",
        exampleJapanese: "電車で行きます。",
        exampleKana: "でんしゃでいきます。",
        exampleGerman: "Ich fahre mit dem Zug.",
      },
      {
        step: "combo",
        type: "sentence-meaning-choice",
        instruction: "Was bedeutet dieser Satz?",
        prompt: "電車で駅に行きます。",
        choices: [
          "Ich fahre mit dem Zug zum Bahnhof.",
          "Ich fahre mit dem Zug zum Hotel.",
          "Ich gehe zum Bahnhof.",
          "Ich fahre mit dem Zug.",
        ],
        answer: "Ich fahre mit dem Zug zum Bahnhof.",
        exampleJapanese: "電車で駅に行きます。",
        exampleKana: "でんしゃでえきにいきます。",
        exampleGerman: "Ich fahre mit dem Zug zum Bahnhof.",
      },
      {
        step: "mini",
        type: "phrase-choice",
        instruction: "Mini Challenge: Wähle den vollständigen, höflichen Satz.",
        prompt: "Entschuldigung, wo ist der Zug?",
        choices: [
          "すみません、電車はどこですか。",
          "すみません、駅はどこですか。",
          "電車はどこですか。",
          "電車で行きます。",
        ],
        answer: "すみません、電車はどこですか。",
        answerKana: "すみません、でんしゃはどこですか。",
        answerRomaji: "sumimasen, densha wa doko desu ka",
        answerGerman: "Entschuldigung, wo ist der Zug?",
        exampleJapanese: "すみません、電車はどこですか。",
        exampleKana: "すみません、でんしゃはどこですか。",
        exampleGerman: "Entschuldigung, wo ist der Zug?",
      },
    ],
    {
      speechText: "電車で行きます。",
      speechKana: "でんしゃでいきます。",
      speechRomaji: "densha de ikimasu",
      speechGerman: "Ich fahre mit dem Zug.",
      acceptedTranscripts: ["電車で行きます", "でんしゃでいきます"],
    }
  ),

  toilet: defineSubQuest(
    "toilet",
    "reise",
    [
      {
        step: "meaning",
        type: "meaning-choice",
        instruction: "Wähle die richtige Bedeutung.",
        prompt: "トイレ",
        choices: ["Toilette", "Bahnhof", "Hotel", "Zug"],
        answer: "Toilette",
      },
      {
        step: "word",
        type: "japanese-choice",
        instruction: "Wähle das passende japanische Wort.",
        prompt: "Toilette",
        choices: ["トイレ", "駅", "ホテル", "電車"],
        answer: "トイレ",
      },
      {
        step: "particle",
        type: "particle-choice",
        instruction: "Wähle die passende Partikel.",
        prompt: "„Wo ist die Toilette?“\nトイレ____どこですか。",
        choices: ["は", "を", "で", "に"],
        answer: "は",
        exampleJapanese: "トイレはどこですか。",
        exampleKana: "トイレはどこですか。",
        exampleGerman: "Wo ist die Toilette?",
      },
      {
        step: "direction",
        type: "fill-blank",
        instruction: "Ergänze den Satz.",
        prompt: "„Die Toilette ist links.“\nトイレは____です。",
        choices: ["左", "右", "どこ", "遠い"],
        answer: "左",
        exampleJapanese: "トイレは左です。",
        exampleKana: "トイレはひだりです。",
        exampleGerman: "Die Toilette ist links.",
      },
      {
        step: "sentence-meaning",
        type: "sentence-meaning-choice",
        instruction: "Was bedeutet dieser Satz?",
        prompt: "トイレは右です。",
        choices: [
          "Die Toilette ist rechts.",
          "Die Toilette ist links.",
          "Wo ist die Toilette?",
          "Die Toilette ist nah.",
        ],
        answer: "Die Toilette ist rechts.",
        exampleJapanese: "トイレは右です。",
        exampleKana: "トイレはみぎです。",
        exampleGerman: "Die Toilette ist rechts.",
      },
      {
        step: "phrase",
        type: "phrase-choice",
        instruction: "Wähle den natürlichen japanischen Satz.",
        prompt: "Wo ist die Toilette?",
        choices: ["トイレはどこですか。", "トイレは右です。", "駅はどこですか。", "トイレに行きます。"],
        answer: "トイレはどこですか。",
        answerKana: "トイレはどこですか。",
        answerRomaji: "toire wa doko desu ka",
        answerGerman: "Wo ist die Toilette?",
        exampleJapanese: "トイレはどこですか。",
        exampleKana: "トイレはどこですか。",
        exampleGerman: "Wo ist die Toilette?",
      },
      {
        step: "mistake",
        type: "mistake-choice",
        instruction: "Achtung, Verwechslungsgefahr: Wähle den richtigen Satz.",
        prompt: "Ziel mit に: „Ich gehe zur Toilette.“",
        choices: ["トイレに行きます。", "トイレで行きます。", "トイレを行きます。", "トイレと行きます。"],
        answer: "トイレに行きます。",
        exampleJapanese: "トイレに行きます。",
        exampleKana: "トイレにいきます。",
        exampleGerman: "Ich gehe zur Toilette.",
      },
      {
        step: "combo",
        type: "sentence-meaning-choice",
        instruction: "Was bedeutet dieser Satz?",
        prompt: "トイレは近いです。",
        choices: [
          "Die Toilette ist nah.",
          "Die Toilette ist weit entfernt.",
          "Die Toilette ist rechts.",
          "Wo ist die Toilette?",
        ],
        answer: "Die Toilette ist nah.",
        exampleJapanese: "トイレは近いです。",
        exampleKana: "トイレはちかいです。",
        exampleGerman: "Die Toilette ist nah.",
      },
      {
        step: "mini",
        type: "phrase-choice",
        instruction: "Mini Challenge: Wähle den vollständigen, höflichen Satz.",
        prompt: "Entschuldigung, wo ist die Toilette?",
        choices: [
          "すみません、トイレはどこですか。",
          "トイレはどこですか。",
          "すみません、駅はどこですか。",
          "トイレは右です。",
        ],
        answer: "すみません、トイレはどこですか。",
        answerKana: "すみません、トイレはどこですか。",
        answerRomaji: "sumimasen, toire wa doko desu ka",
        answerGerman: "Entschuldigung, wo ist die Toilette?",
        exampleJapanese: "すみません、トイレはどこですか。",
        exampleKana: "すみません、トイレはどこですか。",
        exampleGerman: "Entschuldigung, wo ist die Toilette?",
      },
    ],
    {
      speechText: "すみません、トイレはどこですか。",
      speechKana: "すみません、トイレはどこですか。",
      speechRomaji: "sumimasen, toire wa doko desu ka",
      speechGerman: "Entschuldigung, wo ist die Toilette?",
      acceptedTranscripts: ["すみませんトイレはどこですか", "すみませんといれはどこですか"],
    }
  ),

  go: defineSubQuest(
    "go",
    "reise",
    [
      {
        step: "meaning",
        type: "meaning-choice",
        instruction: "Wähle die richtige Bedeutung.",
        prompt: "行く",
        choices: ["gehen", "trinken", "essen", "Bahnhof"],
        answer: "gehen",
      },
      {
        step: "word",
        type: "japanese-choice",
        instruction: "Wähle das passende japanische Wort.",
        prompt: "gehen",
        choices: ["行く", "飲む", "食べる", "駅"],
        answer: "行く",
      },
      {
        step: "particle",
        type: "particle-choice",
        instruction: "Wähle die passende Partikel.",
        prompt: "„Ich gehe zum Bahnhof.“\n駅____行きます。",
        choices: ["に", "を", "で", "と"],
        answer: "に",
        exampleJapanese: "駅に行きます。",
        exampleKana: "えきにいきます。",
        exampleGerman: "Ich gehe zum Bahnhof.",
      },
      {
        step: "verb",
        type: "fill-blank",
        instruction: "Ergänze den Satz.",
        prompt: "„Ich gehe zum Hotel.“\nホテルに____。",
        choices: ["行きます", "食べます", "飲みます", "ください"],
        answer: "行きます",
        exampleJapanese: "ホテルに行きます。",
        exampleKana: "ホテルにいきます。",
        exampleGerman: "Ich gehe zum Hotel.",
      },
      {
        step: "sentence-meaning",
        type: "sentence-meaning-choice",
        instruction: "Was bedeutet dieser Satz?",
        prompt: "駅に行きます。",
        choices: [
          "Ich gehe zum Bahnhof.",
          "Ich gehe zum Hotel.",
          "Der Bahnhof ist nah.",
          "Ich fahre mit dem Zug.",
        ],
        answer: "Ich gehe zum Bahnhof.",
        exampleJapanese: "駅に行きます。",
        exampleKana: "えきにいきます。",
        exampleGerman: "Ich gehe zum Bahnhof.",
      },
      {
        step: "phrase",
        type: "phrase-choice",
        instruction: "Wähle den natürlichen japanischen Satz.",
        prompt: "Ich gehe zum Hotel.",
        choices: ["ホテルに行きます。", "ホテルで行きます。", "駅に行きます。", "ホテルは遠いです。"],
        answer: "ホテルに行きます。",
        answerKana: "ホテルにいきます。",
        answerRomaji: "hoteru ni ikimasu",
        answerGerman: "Ich gehe zum Hotel.",
        exampleJapanese: "ホテルに行きます。",
        exampleKana: "ホテルにいきます。",
        exampleGerman: "Ich gehe zum Hotel.",
      },
      {
        step: "mistake",
        type: "mistake-choice",
        instruction: "Achtung, Verwechslungsgefahr: Wähle den richtigen Satz.",
        prompt: "で (womit) und に (wohin): „Ich fahre mit dem Zug zum Bahnhof.“",
        choices: [
          "電車で駅に行きます。",
          "電車に駅で行きます。",
          "駅で電車に行きます。",
          "電車と駅に行きます。",
        ],
        answer: "電車で駅に行きます。",
        exampleJapanese: "電車で駅に行きます。",
        exampleKana: "でんしゃでえきにいきます。",
        exampleGerman: "Ich fahre mit dem Zug zum Bahnhof.",
      },
      {
        step: "combo",
        type: "sentence-meaning-choice",
        instruction: "Was bedeutet dieser Satz?",
        prompt: "トイレに行きます。",
        choices: [
          "Ich gehe zur Toilette.",
          "Wo ist die Toilette?",
          "Ich gehe zum Bahnhof.",
          "Ich fahre mit dem Zug.",
        ],
        answer: "Ich gehe zur Toilette.",
        exampleJapanese: "トイレに行きます。",
        exampleKana: "トイレにいきます。",
        exampleGerman: "Ich gehe zur Toilette.",
      },
      {
        step: "mini",
        type: "phrase-choice",
        instruction: "Mini Challenge: Wähle den natürlichen japanischen Satz.",
        prompt: "Gehst du zum Bahnhof?",
        choices: ["駅に行きますか。", "駅に行きます。", "駅はどこですか。", "ホテルに行きますか。"],
        answer: "駅に行きますか。",
        answerKana: "えきにいきますか。",
        answerRomaji: "eki ni ikimasu ka",
        answerGerman: "Gehst du zum Bahnhof?",
        exampleJapanese: "駅に行きますか。",
        exampleKana: "えきにいきますか。",
        exampleGerman: "Gehst du zum Bahnhof?",
      },
    ],
    {
      speechText: "ホテルに行きます。",
      speechKana: "ホテルにいきます。",
      speechRomaji: "hoteru ni ikimasu",
      speechGerman: "Ich gehe zum Hotel.",
      acceptedTranscripts: ["ホテルに行きます", "ほてるにいきます"],
    }
  ),

  where: defineSubQuest(
    "where",
    "reise",
    [
      {
        step: "meaning",
        type: "meaning-choice",
        instruction: "Wähle die richtige Bedeutung.",
        prompt: "どこ",
        choices: ["wo", "rechts", "links", "nah"],
        answer: "wo",
      },
      {
        step: "word",
        type: "japanese-choice",
        instruction: "Wähle das passende japanische Wort.",
        prompt: "wo",
        choices: ["どこ", "右", "左", "近い"],
        answer: "どこ",
      },
      {
        step: "particle",
        type: "particle-choice",
        instruction: "Wähle die passende Partikel.",
        prompt: "„Wo ist der Bahnhof?“\n駅____どこですか。",
        choices: ["は", "を", "に", "が"],
        answer: "は",
        exampleJapanese: "駅はどこですか。",
        exampleKana: "えきはどこですか。",
        exampleGerman: "Wo ist der Bahnhof?",
      },
      {
        step: "word-blank",
        type: "fill-blank",
        instruction: "Ergänze den Satz.",
        prompt: "„Wo ist das Hotel?“\nホテルは____ですか。",
        choices: ["どこ", "近い", "右", "遠い"],
        answer: "どこ",
        exampleJapanese: "ホテルはどこですか。",
        exampleKana: "ホテルはどこですか。",
        exampleGerman: "Wo ist das Hotel?",
      },
      {
        step: "sentence-meaning",
        type: "sentence-meaning-choice",
        instruction: "Was bedeutet dieser Satz?",
        prompt: "トイレはどこですか。",
        choices: [
          "Wo ist die Toilette?",
          "Wo ist der Bahnhof?",
          "Die Toilette ist rechts.",
          "Wo ist das Hotel?",
        ],
        answer: "Wo ist die Toilette?",
        exampleJapanese: "トイレはどこですか。",
        exampleKana: "トイレはどこですか。",
        exampleGerman: "Wo ist die Toilette?",
      },
      {
        step: "phrase",
        type: "phrase-choice",
        instruction: "Wähle den natürlichen japanischen Satz.",
        prompt: "Wo ist der Bahnhof?",
        choices: ["駅はどこですか。", "駅は近いです。", "ホテルはどこですか。", "駅に行きます。"],
        answer: "駅はどこですか。",
        answerKana: "えきはどこですか。",
        answerRomaji: "eki wa doko desu ka",
        answerGerman: "Wo ist der Bahnhof?",
        exampleJapanese: "駅はどこですか。",
        exampleKana: "えきはどこですか。",
        exampleGerman: "Wo ist der Bahnhof?",
      },
      {
        step: "mistake",
        type: "mistake-choice",
        instruction: "Achtung, Verwechslungsgefahr: Wähle den richtigen Satz.",
        prompt: "Eine Frage braucht か: „Wo ist das Hotel?“",
        choices: [
          "ホテルはどこですか。",
          "ホテルはどこです。",
          "ホテルをどこですか。",
          "ホテルにどこですか。",
        ],
        answer: "ホテルはどこですか。",
        exampleJapanese: "ホテルはどこですか。",
        exampleKana: "ホテルはどこですか。",
        exampleGerman: "Wo ist das Hotel?",
      },
      {
        step: "combo",
        type: "phrase-choice",
        instruction: "Wähle den natürlichen japanischen Satz.",
        prompt: "Entschuldigung, wo ist der Bahnhof?",
        choices: [
          "すみません、駅はどこですか。",
          "駅はどこですか。",
          "すみません、ホテルはどこですか。",
          "駅は遠いです。",
        ],
        answer: "すみません、駅はどこですか。",
        answerKana: "すみません、えきはどこですか。",
        answerRomaji: "sumimasen, eki wa doko desu ka",
        answerGerman: "Entschuldigung, wo ist der Bahnhof?",
        exampleJapanese: "すみません、駅はどこですか。",
        exampleKana: "すみません、えきはどこですか。",
        exampleGerman: "Entschuldigung, wo ist der Bahnhof?",
      },
      {
        step: "mini",
        type: "phrase-choice",
        instruction: "Mini Challenge: Wähle den vollständigen, höflichen Satz.",
        prompt: "Entschuldigung, wo ist die Toilette?",
        choices: [
          "すみません、トイレはどこですか。",
          "トイレはどこです。",
          "すみません、トイレに行きます。",
          "トイレは右ですか。",
        ],
        answer: "すみません、トイレはどこですか。",
        answerKana: "すみません、トイレはどこですか。",
        answerRomaji: "sumimasen, toire wa doko desu ka",
        answerGerman: "Entschuldigung, wo ist die Toilette?",
        exampleJapanese: "すみません、トイレはどこですか。",
        exampleKana: "すみません、トイレはどこですか。",
        exampleGerman: "Entschuldigung, wo ist die Toilette?",
      },
    ],
    {
      speechText: "駅はどこですか。",
      speechKana: "えきはどこですか。",
      speechRomaji: "eki wa doko desu ka",
      speechGerman: "Wo ist der Bahnhof?",
      acceptedTranscripts: ["駅はどこですか", "えきはどこですか"],
    }
  ),

  excuseMe: defineSubQuest(
    "excuseMe",
    "reise",
    [
      {
        step: "meaning",
        type: "meaning-choice",
        instruction: "Wähle die richtige Bedeutung.",
        prompt: "すみません",
        choices: ["Entschuldigung", "Danke", "Guten Tag", "Auf Wiedersehen"],
        answer: "Entschuldigung",
      },
      {
        step: "word",
        type: "japanese-choice",
        instruction: "Wähle das passende japanische Wort.",
        prompt: "Entschuldigung",
        choices: ["すみません", "ありがとう", "こんにちは", "さようなら"],
        answer: "すみません",
      },
      {
        step: "particle",
        type: "particle-choice",
        instruction: "Wähle die passende Partikel.",
        prompt: "„Entschuldigung, wo ist der Bahnhof?“\nすみません、駅____どこですか。",
        choices: ["は", "を", "に", "で"],
        answer: "は",
        exampleJapanese: "すみません、駅はどこですか。",
        exampleKana: "すみません、えきはどこですか。",
        exampleGerman: "Entschuldigung, wo ist der Bahnhof?",
      },
      {
        step: "word-blank",
        type: "fill-blank",
        instruction: "Ergänze den Satz.",
        prompt: "„Entschuldigung, wo ist die Toilette?“\n____、トイレはどこですか。",
        choices: ["すみません", "ありがとう", "こんにちは", "さようなら"],
        answer: "すみません",
        exampleJapanese: "すみません、トイレはどこですか。",
        exampleKana: "すみません、トイレはどこですか。",
        exampleGerman: "Entschuldigung, wo ist die Toilette?",
      },
      {
        step: "sentence-meaning",
        type: "sentence-meaning-choice",
        instruction: "Was bedeutet dieser Satz?",
        prompt: "すみません、駅はどこですか。",
        choices: [
          "Entschuldigung, wo ist der Bahnhof?",
          "Entschuldigung, wo ist die Toilette?",
          "Wo ist der Bahnhof?",
          "Entschuldigung, wo ist das Hotel?",
        ],
        answer: "Entschuldigung, wo ist der Bahnhof?",
        exampleJapanese: "すみません、駅はどこですか。",
        exampleKana: "すみません、えきはどこですか。",
        exampleGerman: "Entschuldigung, wo ist der Bahnhof?",
      },
      {
        step: "phrase",
        type: "phrase-choice",
        instruction: "Wähle den natürlichen japanischen Satz.",
        prompt: "Entschuldigung, wo ist die Toilette?",
        choices: [
          "すみません、トイレはどこですか。",
          "トイレはどこですか。",
          "すみません、トイレに行きます。",
          "すみません、駅はどこですか。",
        ],
        answer: "すみません、トイレはどこですか。",
        answerKana: "すみません、トイレはどこですか。",
        answerRomaji: "sumimasen, toire wa doko desu ka",
        answerGerman: "Entschuldigung, wo ist die Toilette?",
        exampleJapanese: "すみません、トイレはどこですか。",
        exampleKana: "すみません、トイレはどこですか。",
        exampleGerman: "Entschuldigung, wo ist die Toilette?",
      },
      {
        step: "mistake",
        type: "mistake-choice",
        instruction: "Achtung: Wähle das passende Wort für diese Situation.",
        prompt: "Du bist jemandem aus Versehen auf den Fuß getreten. Was sagst du?",
        choices: ["すみません。", "ありがとう。", "さようなら。", "こんにちは。"],
        answer: "すみません。",
        exampleJapanese: "すみません。",
        exampleKana: "すみません。",
        exampleGerman: "Entschuldigung.",
      },
      {
        step: "combo",
        type: "phrase-choice",
        instruction: "Wähle den natürlichen japanischen Satz.",
        prompt: "Entschuldigung, wo ist das Hotel?",
        choices: [
          "すみません、ホテルはどこですか。",
          "ホテルはどこですか。",
          "すみません、トイレはどこですか。",
          "ホテルに行きます。",
        ],
        answer: "すみません、ホテルはどこですか。",
        answerKana: "すみません、ホテルはどこですか。",
        answerRomaji: "sumimasen, hoteru wa doko desu ka",
        answerGerman: "Entschuldigung, wo ist das Hotel?",
        exampleJapanese: "すみません、ホテルはどこですか。",
        exampleKana: "すみません、ホテルはどこですか。",
        exampleGerman: "Entschuldigung, wo ist das Hotel?",
      },
      {
        step: "mini",
        type: "sentence-meaning-choice",
        instruction: "Mini Challenge: Was bedeutet dieser Satz?",
        prompt: "すみません、水をください。",
        choices: [
          "Entschuldigung, Wasser bitte.",
          "Entschuldigung, wo ist das Wasser?",
          "Wasser bitte.",
          "Entschuldigung, einen Kaffee bitte.",
        ],
        answer: "Entschuldigung, Wasser bitte.",
        exampleJapanese: "すみません、水をください。",
        exampleKana: "すみません、みずをください。",
        exampleGerman: "Entschuldigung, Wasser bitte.",
      },
    ],
    {
      speechText: "すみません、駅はどこですか。",
      speechKana: "すみません、えきはどこですか。",
      speechRomaji: "sumimasen, eki wa doko desu ka",
      speechGerman: "Entschuldigung, wo ist der Bahnhof?",
      acceptedTranscripts: ["すみません駅はどこですか", "すみませんえきはどこですか"],
    }
  ),

  right: defineSubQuest(
    "right",
    "reise",
    [
      {
        step: "meaning",
        type: "meaning-choice",
        instruction: "Wähle die richtige Bedeutung.",
        prompt: "右",
        choices: ["rechts", "links", "nah", "weit entfernt"],
        answer: "rechts",
      },
      {
        step: "word",
        type: "japanese-choice",
        instruction: "Wähle das passende japanische Wort.",
        prompt: "rechts",
        choices: ["右", "左", "近い", "遠い"],
        answer: "右",
      },
      {
        step: "particle",
        type: "particle-choice",
        instruction: "Wähle die passende Partikel.",
        prompt: "„Der Bahnhof ist rechts.“\n駅____右です。",
        choices: ["は", "を", "に", "で"],
        answer: "は",
        exampleJapanese: "駅は右です。",
        exampleKana: "えきはみぎです。",
        exampleGerman: "Der Bahnhof ist rechts.",
      },
      {
        step: "direction",
        type: "fill-blank",
        instruction: "Ergänze den Satz.",
        prompt: "„Die Toilette ist rechts.“\nトイレは____です。",
        choices: ["右", "左", "近い", "遠い"],
        answer: "右",
        exampleJapanese: "トイレは右です。",
        exampleKana: "トイレはみぎです。",
        exampleGerman: "Die Toilette ist rechts.",
      },
      {
        step: "sentence-meaning",
        type: "sentence-meaning-choice",
        instruction: "Was bedeutet dieser Satz?",
        prompt: "駅は右です。",
        choices: [
          "Der Bahnhof ist rechts.",
          "Der Bahnhof ist links.",
          "Der Bahnhof ist nah.",
          "Die Toilette ist rechts.",
        ],
        answer: "Der Bahnhof ist rechts.",
        exampleJapanese: "駅は右です。",
        exampleKana: "えきはみぎです。",
        exampleGerman: "Der Bahnhof ist rechts.",
      },
      {
        step: "phrase",
        type: "phrase-choice",
        instruction: "Wähle den natürlichen japanischen Satz.",
        prompt: "Das Hotel ist rechts.",
        choices: ["ホテルは右です。", "ホテルは左です。", "駅は右です。", "ホテルは近いです。"],
        answer: "ホテルは右です。",
        answerKana: "ホテルはみぎです。",
        answerRomaji: "hoteru wa migi desu",
        answerGerman: "Das Hotel ist rechts.",
        exampleJapanese: "ホテルは右です。",
        exampleKana: "ホテルはみぎです。",
        exampleGerman: "Das Hotel ist rechts.",
      },
      {
        step: "mistake",
        type: "mistake-choice",
        instruction: "Achtung, Verwechslungsgefahr: Wähle den richtigen Satz.",
        prompt: "Rechts, nicht links – und eine Antwort, keine Frage: „Es ist rechts.“",
        choices: ["右です。", "左です。", "右ですか。", "左ですか。"],
        answer: "右です。",
        exampleJapanese: "右です。",
        exampleKana: "みぎです。",
        exampleGerman: "Es ist rechts.",
      },
      {
        step: "combo",
        type: "phrase-choice",
        instruction: "Wähle den natürlichen japanischen Satz.",
        prompt: "Entschuldigung, ist der Bahnhof rechts?",
        choices: [
          "すみません、駅は右ですか。",
          "すみません、駅は左ですか。",
          "駅は右です。",
          "すみません、駅はどこですか。",
        ],
        answer: "すみません、駅は右ですか。",
        answerKana: "すみません、えきはみぎですか。",
        answerRomaji: "sumimasen, eki wa migi desu ka",
        answerGerman: "Entschuldigung, ist der Bahnhof rechts?",
        exampleJapanese: "すみません、駅は右ですか。",
        exampleKana: "すみません、えきはみぎですか。",
        exampleGerman: "Entschuldigung, ist der Bahnhof rechts?",
      },
      {
        step: "mini",
        type: "sentence-meaning-choice",
        instruction: "Mini Challenge: Was bedeutet dieser Satz?",
        prompt: "トイレは右です。駅は左です。",
        choices: [
          "Die Toilette ist rechts. Der Bahnhof ist links.",
          "Die Toilette ist links. Der Bahnhof ist rechts.",
          "Die Toilette und der Bahnhof sind rechts.",
          "Der Bahnhof ist rechts.",
        ],
        answer: "Die Toilette ist rechts. Der Bahnhof ist links.",
        exampleJapanese: "トイレは右です。駅は左です。",
        exampleKana: "トイレはみぎです。えきはひだりです。",
        exampleGerman: "Die Toilette ist rechts. Der Bahnhof ist links.",
      },
    ],
    {
      speechText: "駅は右です。",
      speechKana: "えきはみぎです。",
      speechRomaji: "eki wa migi desu",
      speechGerman: "Der Bahnhof ist rechts.",
      acceptedTranscripts: ["駅は右です", "えきはみぎです"],
    }
  ),

  left: defineSubQuest(
    "left",
    "reise",
    [
      {
        step: "meaning",
        type: "meaning-choice",
        instruction: "Wähle die richtige Bedeutung.",
        prompt: "左",
        choices: ["links", "rechts", "weit entfernt", "nah"],
        answer: "links",
      },
      {
        step: "word",
        type: "japanese-choice",
        instruction: "Wähle das passende japanische Wort.",
        prompt: "links",
        choices: ["左", "右", "遠い", "近い"],
        answer: "左",
      },
      {
        step: "particle",
        type: "particle-choice",
        instruction: "Wähle die passende Partikel.",
        prompt: "„Die Toilette ist links.“\nトイレ____左です。",
        choices: ["は", "を", "に", "が"],
        answer: "は",
        exampleJapanese: "トイレは左です。",
        exampleKana: "トイレはひだりです。",
        exampleGerman: "Die Toilette ist links.",
      },
      {
        step: "direction",
        type: "fill-blank",
        instruction: "Ergänze den Satz.",
        prompt: "„Der Bahnhof ist links.“\n駅は____です。",
        choices: ["左", "右", "近い", "どこ"],
        answer: "左",
        exampleJapanese: "駅は左です。",
        exampleKana: "えきはひだりです。",
        exampleGerman: "Der Bahnhof ist links.",
      },
      {
        step: "sentence-meaning",
        type: "sentence-meaning-choice",
        instruction: "Was bedeutet dieser Satz?",
        prompt: "ホテルは左です。",
        choices: [
          "Das Hotel ist links.",
          "Das Hotel ist rechts.",
          "Der Bahnhof ist links.",
          "Das Hotel ist nah.",
        ],
        answer: "Das Hotel ist links.",
        exampleJapanese: "ホテルは左です。",
        exampleKana: "ホテルはひだりです。",
        exampleGerman: "Das Hotel ist links.",
      },
      {
        step: "phrase",
        type: "phrase-choice",
        instruction: "Wähle den natürlichen japanischen Satz.",
        prompt: "Der Bahnhof ist links.",
        choices: ["駅は左です。", "駅は右です。", "ホテルは左です。", "駅は近いです。"],
        answer: "駅は左です。",
        answerKana: "えきはひだりです。",
        answerRomaji: "eki wa hidari desu",
        answerGerman: "Der Bahnhof ist links.",
        exampleJapanese: "駅は左です。",
        exampleKana: "えきはひだりです。",
        exampleGerman: "Der Bahnhof ist links.",
      },
      {
        step: "mistake",
        type: "mistake-choice",
        instruction: "Achtung, Verwechslungsgefahr: Wähle den richtigen Satz.",
        prompt: "Links, nicht rechts – und eine Antwort, keine Frage: „Es ist links.“",
        choices: ["左です。", "右です。", "左ですか。", "右ですか。"],
        answer: "左です。",
        exampleJapanese: "左です。",
        exampleKana: "ひだりです。",
        exampleGerman: "Es ist links.",
      },
      {
        step: "combo",
        type: "phrase-choice",
        instruction: "Wähle den natürlichen japanischen Satz.",
        prompt: "Entschuldigung, ist die Toilette links?",
        choices: [
          "すみません、トイレは左ですか。",
          "すみません、トイレは右ですか。",
          "トイレは左です。",
          "すみません、トイレはどこですか。",
        ],
        answer: "すみません、トイレは左ですか。",
        answerKana: "すみません、トイレはひだりですか。",
        answerRomaji: "sumimasen, toire wa hidari desu ka",
        answerGerman: "Entschuldigung, ist die Toilette links?",
        exampleJapanese: "すみません、トイレは左ですか。",
        exampleKana: "すみません、トイレはひだりですか。",
        exampleGerman: "Entschuldigung, ist die Toilette links?",
      },
      {
        step: "mini",
        type: "sentence-meaning-choice",
        instruction: "Mini Challenge: Was bedeutet dieser Satz?",
        prompt: "駅は左です。ホテルは右です。",
        choices: [
          "Der Bahnhof ist links. Das Hotel ist rechts.",
          "Der Bahnhof ist rechts. Das Hotel ist links.",
          "Der Bahnhof und das Hotel sind links.",
          "Das Hotel ist links.",
        ],
        answer: "Der Bahnhof ist links. Das Hotel ist rechts.",
        exampleJapanese: "駅は左です。ホテルは右です。",
        exampleKana: "えきはひだりです。ホテルはみぎです。",
        exampleGerman: "Der Bahnhof ist links. Das Hotel ist rechts.",
      },
    ],
    {
      speechText: "駅は左です。",
      speechKana: "えきはひだりです。",
      speechRomaji: "eki wa hidari desu",
      speechGerman: "Der Bahnhof ist links.",
      acceptedTranscripts: ["駅は左です", "えきはひだりです"],
    }
  ),

  near: defineSubQuest(
    "near",
    "reise",
    [
      {
        step: "meaning",
        type: "meaning-choice",
        instruction: "Wähle die richtige Bedeutung.",
        prompt: "近い",
        choices: ["nah", "weit entfernt", "rechts", "links"],
        answer: "nah",
      },
      {
        step: "word",
        type: "japanese-choice",
        instruction: "Wähle das passende japanische Wort.",
        prompt: "nah",
        choices: ["近い", "遠い", "右", "左"],
        answer: "近い",
      },
      {
        step: "particle",
        type: "particle-choice",
        instruction: "Wähle die passende Partikel.",
        prompt: "„Der Bahnhof ist nah.“\n駅____近いです。",
        choices: ["は", "を", "に", "で"],
        answer: "は",
        exampleJapanese: "駅は近いです。",
        exampleKana: "えきはちかいです。",
        exampleGerman: "Der Bahnhof ist nah.",
      },
      {
        step: "adjective",
        type: "fill-blank",
        instruction: "Ergänze den Satz.",
        prompt: "„Das Hotel ist nah.“\nホテルは____です。",
        choices: ["近い", "遠い", "右", "左"],
        answer: "近い",
        exampleJapanese: "ホテルは近いです。",
        exampleKana: "ホテルはちかいです。",
        exampleGerman: "Das Hotel ist nah.",
      },
      {
        step: "sentence-meaning",
        type: "sentence-meaning-choice",
        instruction: "Was bedeutet dieser Satz?",
        prompt: "駅は近いです。",
        choices: [
          "Der Bahnhof ist nah.",
          "Der Bahnhof ist weit entfernt.",
          "Das Hotel ist nah.",
          "Der Bahnhof ist rechts.",
        ],
        answer: "Der Bahnhof ist nah.",
        exampleJapanese: "駅は近いです。",
        exampleKana: "えきはちかいです。",
        exampleGerman: "Der Bahnhof ist nah.",
      },
      {
        step: "phrase",
        type: "phrase-choice",
        instruction: "Wähle den natürlichen japanischen Satz.",
        prompt: "Die Toilette ist nah.",
        choices: ["トイレは近いです。", "トイレは遠いです。", "駅は近いです。", "トイレは右です。"],
        answer: "トイレは近いです。",
        answerKana: "トイレはちかいです。",
        answerRomaji: "toire wa chikai desu",
        answerGerman: "Die Toilette ist nah.",
        exampleJapanese: "トイレは近いです。",
        exampleKana: "トイレはちかいです。",
        exampleGerman: "Die Toilette ist nah.",
      },
      {
        step: "mistake",
        type: "mistake-choice",
        instruction: "Achtung, Verwechslungsgefahr: Wähle den richtigen Satz.",
        prompt: "Nah, nicht weit – und eine Aussage, keine Frage: „Der Bahnhof ist nah.“",
        choices: ["駅は近いです。", "駅は遠いです。", "駅は近いですか。", "駅は右です。"],
        answer: "駅は近いです。",
        exampleJapanese: "駅は近いです。",
        exampleKana: "えきはちかいです。",
        exampleGerman: "Der Bahnhof ist nah.",
      },
      {
        step: "combo",
        type: "phrase-choice",
        instruction: "Wähle den natürlichen japanischen Satz.",
        prompt: "Ist das Hotel nah?",
        choices: [
          "ホテルは近いですか。",
          "ホテルは近いです。",
          "ホテルは遠いですか。",
          "ホテルはどこですか。",
        ],
        answer: "ホテルは近いですか。",
        answerKana: "ホテルはちかいですか。",
        answerRomaji: "hoteru wa chikai desu ka",
        answerGerman: "Ist das Hotel nah?",
        exampleJapanese: "ホテルは近いですか。",
        exampleKana: "ホテルはちかいですか。",
        exampleGerman: "Ist das Hotel nah?",
      },
      {
        step: "mini",
        type: "sentence-meaning-choice",
        instruction: "Mini Challenge: Was bedeutet dieser Satz?",
        prompt: "ホテルは近いです。駅は遠いです。",
        choices: [
          "Das Hotel ist nah. Der Bahnhof ist weit entfernt.",
          "Das Hotel ist weit entfernt. Der Bahnhof ist nah.",
          "Das Hotel und der Bahnhof sind nah.",
          "Das Hotel ist nah.",
        ],
        answer: "Das Hotel ist nah. Der Bahnhof ist weit entfernt.",
        exampleJapanese: "ホテルは近いです。駅は遠いです。",
        exampleKana: "ホテルはちかいです。えきはとおいです。",
        exampleGerman: "Das Hotel ist nah. Der Bahnhof ist weit entfernt.",
      },
    ],
    {
      speechText: "駅は近いです。",
      speechKana: "えきはちかいです。",
      speechRomaji: "eki wa chikai desu",
      speechGerman: "Der Bahnhof ist nah.",
      acceptedTranscripts: ["駅は近いです", "えきはちかいです"],
    }
  ),

  far: defineSubQuest(
    "far",
    "reise",
    [
      {
        step: "meaning",
        type: "meaning-choice",
        instruction: "Wähle die richtige Bedeutung.",
        prompt: "遠い",
        choices: ["weit entfernt", "nah", "links", "rechts"],
        answer: "weit entfernt",
      },
      {
        step: "word",
        type: "japanese-choice",
        instruction: "Wähle das passende japanische Wort.",
        prompt: "weit entfernt",
        choices: ["遠い", "近い", "左", "右"],
        answer: "遠い",
      },
      {
        step: "particle",
        type: "particle-choice",
        instruction: "Wähle die passende Partikel.",
        prompt: "„Das Hotel ist weit entfernt.“\nホテル____遠いです。",
        choices: ["は", "を", "に", "で"],
        answer: "は",
        exampleJapanese: "ホテルは遠いです。",
        exampleKana: "ホテルはとおいです。",
        exampleGerman: "Das Hotel ist weit entfernt.",
      },
      {
        step: "adjective",
        type: "fill-blank",
        instruction: "Ergänze den Satz.",
        prompt: "„Der Bahnhof ist weit entfernt.“\n駅は____です。",
        choices: ["遠い", "近い", "左", "どこ"],
        answer: "遠い",
        exampleJapanese: "駅は遠いです。",
        exampleKana: "えきはとおいです。",
        exampleGerman: "Der Bahnhof ist weit entfernt.",
      },
      {
        step: "sentence-meaning",
        type: "sentence-meaning-choice",
        instruction: "Was bedeutet dieser Satz?",
        prompt: "ホテルは遠いです。",
        choices: [
          "Das Hotel ist weit entfernt.",
          "Das Hotel ist nah.",
          "Der Bahnhof ist weit entfernt.",
          "Das Hotel ist links.",
        ],
        answer: "Das Hotel ist weit entfernt.",
        exampleJapanese: "ホテルは遠いです。",
        exampleKana: "ホテルはとおいです。",
        exampleGerman: "Das Hotel ist weit entfernt.",
      },
      {
        step: "phrase",
        type: "phrase-choice",
        instruction: "Wähle den natürlichen japanischen Satz.",
        prompt: "Der Bahnhof ist weit entfernt.",
        choices: ["駅は遠いです。", "駅は近いです。", "ホテルは遠いです。", "駅は左です。"],
        answer: "駅は遠いです。",
        answerKana: "えきはとおいです。",
        answerRomaji: "eki wa tooi desu",
        answerGerman: "Der Bahnhof ist weit entfernt.",
        exampleJapanese: "駅は遠いです。",
        exampleKana: "えきはとおいです。",
        exampleGerman: "Der Bahnhof ist weit entfernt.",
      },
      {
        step: "mistake",
        type: "mistake-choice",
        instruction: "Achtung, Verwechslungsgefahr: Wähle den richtigen Satz.",
        prompt: "Weit entfernt, nicht nah: „Die Toilette ist weit entfernt.“",
        choices: ["トイレは遠いです。", "トイレは近いです。", "トイレは遠いですか。", "トイレは左です。"],
        answer: "トイレは遠いです。",
        exampleJapanese: "トイレは遠いです。",
        exampleKana: "トイレはとおいです。",
        exampleGerman: "Die Toilette ist weit entfernt.",
      },
      {
        step: "combo",
        type: "phrase-choice",
        instruction: "Wähle den natürlichen japanischen Satz.",
        prompt: "Ist der Bahnhof weit entfernt?",
        choices: ["駅は遠いですか。", "駅は遠いです。", "駅は近いですか。", "駅はどこですか。"],
        answer: "駅は遠いですか。",
        answerKana: "えきはとおいですか。",
        answerRomaji: "eki wa tooi desu ka",
        answerGerman: "Ist der Bahnhof weit entfernt?",
        exampleJapanese: "駅は遠いですか。",
        exampleKana: "えきはとおいですか。",
        exampleGerman: "Ist der Bahnhof weit entfernt?",
      },
      {
        step: "mini",
        type: "sentence-meaning-choice",
        instruction: "Mini Challenge: Was bedeutet dieser Satz?",
        prompt: "ホテルは遠いです。電車で行きます。",
        choices: [
          "Das Hotel ist weit entfernt. Ich fahre mit dem Zug.",
          "Das Hotel ist nah. Ich fahre mit dem Zug.",
          "Das Hotel ist weit entfernt. Ich gehe zum Bahnhof.",
          "Der Zug ist weit entfernt.",
        ],
        answer: "Das Hotel ist weit entfernt. Ich fahre mit dem Zug.",
        exampleJapanese: "ホテルは遠いです。電車で行きます。",
        exampleKana: "ホテルはとおいです。でんしゃでいきます。",
        exampleGerman: "Das Hotel ist weit entfernt. Ich fahre mit dem Zug.",
      },
    ],
    {
      speechText: "ホテルは遠いです。",
      speechKana: "ホテルはとおいです。",
      speechRomaji: "hoteru wa tooi desu",
      speechGerman: "Das Hotel ist weit entfernt.",
      acceptedTranscripts: ["ホテルは遠いです", "ほてるはとおいです"],
    }
  ),
};
