import type { QuizQuestion } from "@/types/learning";
import { defineSubQuest } from "./shared";

/**
 * Hand-authored Sub Quests for the Schule words (Block 1, A0–A1). Learning focus of the
 * category: „〜を勉強します“, Ort der Handlung mit で (学校で), Ziel mit に (学校に),
 * and 今日 als Zeitangabe am Satzanfang. Uses only vocabulary from Café/Reise/Schule.
 */
export const schuleSubQuests: Record<string, QuizQuestion[]> = {
  school: defineSubQuest(
    "school",
    "schule",
    [
      {
        step: "meaning",
        type: "meaning-choice",
        instruction: "Wähle die richtige Bedeutung.",
        prompt: "学校",
        choices: ["Schule", "Lehrer/Lehrerin", "Japanisch", "Bahnhof"],
        answer: "Schule",
      },
      {
        step: "word",
        type: "japanese-choice",
        instruction: "Wähle das passende japanische Wort.",
        prompt: "Schule",
        choices: ["学校", "先生", "日本語", "駅"],
        answer: "学校",
      },
      {
        step: "particle",
        type: "particle-choice",
        instruction: "Wähle die passende Partikel.",
        prompt: "„Ich gehe zur Schule.“\n学校____行きます。",
        choices: ["に", "を", "で", "と"],
        answer: "に",
        exampleJapanese: "学校に行きます。",
        exampleKana: "がっこうにいきます。",
        exampleGerman: "Ich gehe zur Schule.",
      },
      {
        step: "verb",
        type: "fill-blank",
        instruction: "Ergänze den Satz.",
        prompt: "„Heute gehe ich zur Schule.“\n今日、学校に____。",
        choices: ["行きます", "勉強します", "食べます", "飲みます"],
        answer: "行きます",
        exampleJapanese: "今日、学校に行きます。",
        exampleKana: "きょう、がっこうにいきます。",
        exampleGerman: "Heute gehe ich zur Schule.",
      },
      {
        step: "sentence-meaning",
        type: "sentence-meaning-choice",
        instruction: "Was bedeutet dieser Satz?",
        prompt: "学校は近いです。",
        choices: [
          "Die Schule ist nah.",
          "Die Schule ist weit entfernt.",
          "Ich gehe zur Schule.",
          "Wo ist die Schule?",
        ],
        answer: "Die Schule ist nah.",
        exampleJapanese: "学校は近いです。",
        exampleKana: "がっこうはちかいです。",
        exampleGerman: "Die Schule ist nah.",
      },
      {
        step: "phrase",
        type: "phrase-choice",
        instruction: "Wähle den natürlichen japanischen Satz.",
        prompt: "Ich gehe zur Schule.",
        choices: ["学校に行きます。", "学校で行きます。", "駅に行きます。", "学校はどこですか。"],
        answer: "学校に行きます。",
        answerKana: "がっこうにいきます。",
        answerRomaji: "gakkou ni ikimasu",
        answerGerman: "Ich gehe zur Schule.",
        exampleJapanese: "学校に行きます。",
        exampleKana: "がっこうにいきます。",
        exampleGerman: "Ich gehe zur Schule.",
      },
      {
        step: "mistake",
        type: "mistake-choice",
        instruction: "Achtung, Verwechslungsgefahr: Wähle den richtigen Satz.",
        prompt: "Ort der Handlung mit で: „Ich lerne in der Schule Japanisch.“",
        choices: [
          "学校で日本語を勉強します。",
          "学校に日本語を勉強します。",
          "学校を日本語で勉強します。",
          "学校と日本語を勉強します。",
        ],
        answer: "学校で日本語を勉強します。",
        exampleJapanese: "学校で日本語を勉強します。",
        exampleKana: "がっこうでにほんごをべんきょうします。",
        exampleGerman: "Ich lerne in der Schule Japanisch.",
      },
      {
        step: "combo",
        type: "sentence-meaning-choice",
        instruction: "Was bedeutet dieser Satz?",
        prompt: "今日、学校に行きます。",
        choices: [
          "Heute gehe ich zur Schule.",
          "Ich gehe zur Schule.",
          "Heute lerne ich Japanisch.",
          "Heute gehe ich zum Bahnhof.",
        ],
        answer: "Heute gehe ich zur Schule.",
        exampleJapanese: "今日、学校に行きます。",
        exampleKana: "きょう、がっこうにいきます。",
        exampleGerman: "Heute gehe ich zur Schule.",
      },
      {
        step: "mini",
        type: "phrase-choice",
        instruction: "Mini Challenge: Wähle den natürlichen japanischen Satz.",
        prompt: "Ich fahre mit dem Zug zur Schule.",
        choices: [
          "電車で学校に行きます。",
          "学校で電車に行きます。",
          "電車に学校で行きます。",
          "学校に行きます。",
        ],
        answer: "電車で学校に行きます。",
        answerKana: "でんしゃでがっこうにいきます。",
        answerRomaji: "densha de gakkou ni ikimasu",
        answerGerman: "Ich fahre mit dem Zug zur Schule.",
        exampleJapanese: "電車で学校に行きます。",
        exampleKana: "でんしゃでがっこうにいきます。",
        exampleGerman: "Ich fahre mit dem Zug zur Schule.",
      },
    ],
    {
      speechText: "学校に行きます。",
      speechKana: "がっこうにいきます。",
      speechRomaji: "gakkou ni ikimasu",
      speechGerman: "Ich gehe zur Schule.",
      acceptedTranscripts: ["学校に行きます", "がっこうにいきます"],
    }
  ),

  teacher: defineSubQuest(
    "teacher",
    "schule",
    [
      {
        step: "meaning",
        type: "meaning-choice",
        instruction: "Wähle die richtige Bedeutung.",
        prompt: "先生",
        choices: ["Lehrer/Lehrerin", "Schule", "Japanisch", "Freund/Freundin"],
        answer: "Lehrer/Lehrerin",
      },
      {
        step: "word",
        type: "japanese-choice",
        instruction: "Wähle das passende japanische Wort.",
        prompt: "Lehrer/Lehrerin",
        choices: ["先生", "学校", "日本語", "今日"],
        answer: "先生",
      },
      {
        step: "particle",
        type: "particle-choice",
        instruction: "Wähle die passende Partikel.",
        prompt: "„Ich lerne mit dem Lehrer Japanisch.“\n先生____日本語を勉強します。",
        choices: ["と", "を", "に", "は"],
        answer: "と",
        exampleJapanese: "先生と日本語を勉強します。",
        exampleKana: "せんせいとにほんごをべんきょうします。",
        exampleGerman: "Ich lerne mit dem Lehrer Japanisch.",
      },
      {
        step: "word-blank",
        type: "fill-blank",
        instruction: "Ergänze den Satz.",
        prompt: "„Wo ist der Lehrer?“\n先生は____ですか。",
        choices: ["どこ", "近い", "右", "左"],
        answer: "どこ",
        exampleJapanese: "先生はどこですか。",
        exampleKana: "せんせいはどこですか。",
        exampleGerman: "Wo ist der Lehrer?",
      },
      {
        step: "sentence-meaning",
        type: "sentence-meaning-choice",
        instruction: "Was bedeutet dieser Satz?",
        prompt: "先生と勉強します。",
        choices: [
          "Ich lerne mit dem Lehrer.",
          "Ich gehe mit dem Lehrer zur Schule.",
          "Ich lerne in der Schule.",
          "Ich lerne Japanisch.",
        ],
        answer: "Ich lerne mit dem Lehrer.",
        exampleJapanese: "先生と勉強します。",
        exampleKana: "せんせいとべんきょうします。",
        exampleGerman: "Ich lerne mit dem Lehrer.",
      },
      {
        step: "phrase",
        type: "phrase-choice",
        instruction: "Wähle den natürlichen japanischen Satz.",
        prompt: "Ich gehe mit dem Lehrer zur Schule.",
        choices: [
          "先生と学校に行きます。",
          "先生と勉強します。",
          "学校に行きます。",
          "先生に学校と行きます。",
        ],
        answer: "先生と学校に行きます。",
        answerKana: "せんせいとがっこうにいきます。",
        answerRomaji: "sensei to gakkou ni ikimasu",
        answerGerman: "Ich gehe mit dem Lehrer zur Schule.",
        exampleJapanese: "先生と学校に行きます。",
        exampleKana: "せんせいとがっこうにいきます。",
        exampleGerman: "Ich gehe mit dem Lehrer zur Schule.",
      },
      {
        step: "mistake",
        type: "mistake-choice",
        instruction: "Achtung, Verwechslungsgefahr: Wähle den richtigen Satz.",
        prompt: "„Ich lerne mit dem Lehrer Japanisch.“ – mit = と",
        choices: [
          "先生と日本語を勉強します。",
          "先生は日本語を勉強します。",
          "先生を日本語と勉強します。",
          "先生に日本語を食べます。",
        ],
        answer: "先生と日本語を勉強します。",
        exampleJapanese: "先生と日本語を勉強します。",
        exampleKana: "せんせいとにほんごをべんきょうします。",
        exampleGerman: "Ich lerne mit dem Lehrer Japanisch.",
      },
      {
        step: "combo",
        type: "sentence-meaning-choice",
        instruction: "Was bedeutet dieser Satz?",
        prompt: "今日、先生と勉強します。",
        choices: [
          "Heute lerne ich mit dem Lehrer.",
          "Heute gehe ich mit dem Lehrer zur Schule.",
          "Ich lerne mit dem Lehrer.",
          "Heute lernt der Lehrer.",
        ],
        answer: "Heute lerne ich mit dem Lehrer.",
        exampleJapanese: "今日、先生と勉強します。",
        exampleKana: "きょう、せんせいとべんきょうします。",
        exampleGerman: "Heute lerne ich mit dem Lehrer.",
      },
      {
        step: "mini",
        type: "phrase-choice",
        instruction: "Mini Challenge: Wähle den vollständigen, höflichen Satz.",
        prompt: "Entschuldigung, wo ist der Lehrer?",
        choices: [
          "すみません、先生はどこですか。",
          "すみません、学校はどこですか。",
          "先生はどこですか。",
          "先生と学校に行きます。",
        ],
        answer: "すみません、先生はどこですか。",
        answerKana: "すみません、せんせいはどこですか。",
        answerRomaji: "sumimasen, sensei wa doko desu ka",
        answerGerman: "Entschuldigung, wo ist der Lehrer?",
        exampleJapanese: "すみません、先生はどこですか。",
        exampleKana: "すみません、せんせいはどこですか。",
        exampleGerman: "Entschuldigung, wo ist der Lehrer?",
      },
    ],
    {
      speechText: "先生と日本語を勉強します。",
      speechKana: "せんせいとにほんごをべんきょうします。",
      speechRomaji: "sensei to nihongo o benkyou shimasu",
      speechGerman: "Ich lerne mit dem Lehrer Japanisch.",
      acceptedTranscripts: ["先生と日本語を勉強します", "せんせいとにほんごをべんきょうします"],
    }
  ),

  japaneseLanguage: defineSubQuest(
    "japaneseLanguage",
    "schule",
    [
      {
        step: "meaning",
        type: "meaning-choice",
        instruction: "Wähle die richtige Bedeutung.",
        prompt: "日本語",
        choices: ["Japanisch", "Deutsch", "Schule", "Lehrer/Lehrerin"],
        answer: "Japanisch",
      },
      {
        step: "word",
        type: "japanese-choice",
        instruction: "Wähle das passende japanische Wort.",
        prompt: "Japanisch",
        choices: ["日本語", "学校", "先生", "今日"],
        answer: "日本語",
      },
      {
        step: "particle",
        type: "particle-choice",
        instruction: "Wähle die passende Partikel.",
        prompt: "„Ich lerne Japanisch.“\n日本語____勉強します。",
        choices: ["を", "に", "と", "は"],
        answer: "を",
        exampleJapanese: "日本語を勉強します。",
        exampleKana: "にほんごをべんきょうします。",
        exampleGerman: "Ich lerne Japanisch.",
      },
      {
        step: "word-blank",
        type: "fill-blank",
        instruction: "Ergänze den Satz.",
        prompt: "„Heute lerne ich Japanisch.“\n今日、____を勉強します。",
        choices: ["日本語", "学校", "先生", "今日"],
        answer: "日本語",
        exampleJapanese: "今日、日本語を勉強します。",
        exampleKana: "きょう、にほんごをべんきょうします。",
        exampleGerman: "Heute lerne ich Japanisch.",
      },
      {
        step: "sentence-meaning",
        type: "sentence-meaning-choice",
        instruction: "Was bedeutet dieser Satz?",
        prompt: "日本語を勉強します。",
        choices: [
          "Ich lerne Japanisch.",
          "Ich spreche Japanisch.",
          "Heute lerne ich Japanisch.",
          "Ich mag Japanisch.",
        ],
        answer: "Ich lerne Japanisch.",
        exampleJapanese: "日本語を勉強します。",
        exampleKana: "にほんごをべんきょうします。",
        exampleGerman: "Ich lerne Japanisch.",
      },
      {
        step: "phrase",
        type: "phrase-choice",
        instruction: "Wähle den natürlichen japanischen Satz.",
        prompt: "Heute lerne ich Japanisch.",
        choices: [
          "今日、日本語を勉強します。",
          "日本語を勉強します。",
          "今日、学校に行きます。",
          "学校で日本語を勉強します。",
        ],
        answer: "今日、日本語を勉強します。",
        answerKana: "きょう、にほんごをべんきょうします。",
        answerRomaji: "kyou, nihongo o benkyou shimasu",
        answerGerman: "Heute lerne ich Japanisch.",
        exampleJapanese: "今日、日本語を勉強します。",
        exampleKana: "きょう、にほんごをべんきょうします。",
        exampleGerman: "Heute lerne ich Japanisch.",
      },
      {
        step: "mistake",
        type: "mistake-choice",
        instruction: "Achtung, Verwechslungsgefahr: Wähle den richtigen Satz.",
        prompt: "Objekt mit を: „Ich lerne Japanisch.“",
        choices: [
          "日本語を勉強します。",
          "日本語に勉強します。",
          "日本語で勉強します。",
          "日本語と勉強します。",
        ],
        answer: "日本語を勉強します。",
        exampleJapanese: "日本語を勉強します。",
        exampleKana: "にほんごをべんきょうします。",
        exampleGerman: "Ich lerne Japanisch.",
      },
      {
        step: "combo",
        type: "sentence-meaning-choice",
        instruction: "Was bedeutet dieser Satz?",
        prompt: "学校で日本語を勉強します。",
        choices: [
          "Ich lerne in der Schule Japanisch.",
          "Heute lerne ich in der Schule Japanisch.",
          "Ich lerne in der Schule.",
          "Ich lerne Japanisch.",
        ],
        answer: "Ich lerne in der Schule Japanisch.",
        exampleJapanese: "学校で日本語を勉強します。",
        exampleKana: "がっこうでにほんごをべんきょうします。",
        exampleGerman: "Ich lerne in der Schule Japanisch.",
      },
      {
        step: "mini",
        type: "phrase-choice",
        instruction: "Mini Challenge: Wähle den natürlichen japanischen Satz.",
        prompt: "Ich lerne mit dem Lehrer Japanisch.",
        choices: [
          "先生と日本語を勉強します。",
          "学校で日本語を勉強します。",
          "先生と学校に行きます。",
          "日本語を勉強します。",
        ],
        answer: "先生と日本語を勉強します。",
        answerKana: "せんせいとにほんごをべんきょうします。",
        answerRomaji: "sensei to nihongo o benkyou shimasu",
        answerGerman: "Ich lerne mit dem Lehrer Japanisch.",
        exampleJapanese: "先生と日本語を勉強します。",
        exampleKana: "せんせいとにほんごをべんきょうします。",
        exampleGerman: "Ich lerne mit dem Lehrer Japanisch.",
      },
    ],
    {
      speechText: "日本語を勉強します。",
      speechKana: "にほんごをべんきょうします。",
      speechRomaji: "nihongo o benkyou shimasu",
      speechGerman: "Ich lerne Japanisch.",
      acceptedTranscripts: ["日本語を勉強します", "にほんごをべんきょうします"],
    }
  ),

  study: defineSubQuest(
    "study",
    "schule",
    [
      {
        step: "meaning",
        type: "meaning-choice",
        instruction: "Wähle die richtige Bedeutung.",
        prompt: "勉強する",
        choices: ["lernen", "sprechen", "essen", "gehen"],
        answer: "lernen",
      },
      {
        step: "word",
        type: "japanese-choice",
        instruction: "Wähle das passende japanische Wort.",
        prompt: "lernen",
        choices: ["勉強する", "食べる", "行く", "飲む"],
        answer: "勉強する",
      },
      {
        step: "particle",
        type: "particle-choice",
        instruction: "Wähle die passende Partikel.",
        prompt: "„Ich lerne Japanisch.“\n日本語____勉強します。",
        choices: ["を", "が", "に", "と"],
        answer: "を",
        exampleJapanese: "日本語を勉強します。",
        exampleKana: "にほんごをべんきょうします。",
        exampleGerman: "Ich lerne Japanisch.",
      },
      {
        step: "verb",
        type: "fill-blank",
        instruction: "Ergänze den Satz.",
        prompt: "„Heute lerne ich Japanisch.“\n今日、日本語を____。",
        choices: ["勉強します", "食べます", "行きます", "飲みます"],
        answer: "勉強します",
        exampleJapanese: "今日、日本語を勉強します。",
        exampleKana: "きょう、にほんごをべんきょうします。",
        exampleGerman: "Heute lerne ich Japanisch.",
      },
      {
        step: "sentence-meaning",
        type: "sentence-meaning-choice",
        instruction: "Was bedeutet dieser Satz?",
        prompt: "学校で勉強します。",
        choices: [
          "Ich lerne in der Schule.",
          "Ich gehe zur Schule.",
          "Ich lerne Japanisch.",
          "Ich lerne in der Schule Japanisch.",
        ],
        answer: "Ich lerne in der Schule.",
        exampleJapanese: "学校で勉強します。",
        exampleKana: "がっこうでべんきょうします。",
        exampleGerman: "Ich lerne in der Schule.",
      },
      {
        step: "phrase",
        type: "phrase-choice",
        instruction: "Wähle den natürlichen japanischen Satz.",
        prompt: "Ich lerne Japanisch.",
        choices: ["日本語を勉強します。", "日本語を食べます。", "学校に行きます。", "日本語をください。"],
        answer: "日本語を勉強します。",
        answerKana: "にほんごをべんきょうします。",
        answerRomaji: "nihongo o benkyou shimasu",
        answerGerman: "Ich lerne Japanisch.",
        exampleJapanese: "日本語を勉強します。",
        exampleKana: "にほんごをべんきょうします。",
        exampleGerman: "Ich lerne Japanisch.",
      },
      {
        step: "mistake",
        type: "mistake-choice",
        instruction: "Achtung, Verwechslungsgefahr: Wähle den richtigen Satz.",
        prompt: "Ort der Handlung mit で: „Ich lerne in der Schule.“",
        choices: ["学校で勉強します。", "学校に勉強します。", "学校を勉強します。", "学校と勉強します。"],
        answer: "学校で勉強します。",
        exampleJapanese: "学校で勉強します。",
        exampleKana: "がっこうでべんきょうします。",
        exampleGerman: "Ich lerne in der Schule.",
      },
      {
        step: "combo",
        type: "sentence-meaning-choice",
        instruction: "Was bedeutet dieser Satz?",
        prompt: "今日、日本語を勉強します。",
        choices: [
          "Heute lerne ich Japanisch.",
          "Ich lerne Japanisch.",
          "Heute gehe ich zur Schule.",
          "Heute lerne ich in der Schule.",
        ],
        answer: "Heute lerne ich Japanisch.",
        exampleJapanese: "今日、日本語を勉強します。",
        exampleKana: "きょう、にほんごをべんきょうします。",
        exampleGerman: "Heute lerne ich Japanisch.",
      },
      {
        step: "mini",
        type: "phrase-choice",
        instruction: "Mini Challenge: Wähle den natürlichen japanischen Satz.",
        prompt: "Heute lerne ich in der Schule Japanisch.",
        choices: [
          "今日、学校で日本語を勉強します。",
          "今日、学校に日本語を勉強します。",
          "学校で日本語を勉強します。",
          "今日、学校に行きます。",
        ],
        answer: "今日、学校で日本語を勉強します。",
        answerKana: "きょう、がっこうでにほんごをべんきょうします。",
        answerRomaji: "kyou, gakkou de nihongo o benkyou shimasu",
        answerGerman: "Heute lerne ich in der Schule Japanisch.",
        exampleJapanese: "今日、学校で日本語を勉強します。",
        exampleKana: "きょう、がっこうでにほんごをべんきょうします。",
        exampleGerman: "Heute lerne ich in der Schule Japanisch.",
      },
    ],
    {
      speechText: "今日、日本語を勉強します。",
      speechKana: "きょう、にほんごをべんきょうします。",
      speechRomaji: "kyou, nihongo o benkyou shimasu",
      speechGerman: "Heute lerne ich Japanisch.",
      acceptedTranscripts: ["今日日本語を勉強します", "きょうにほんごをべんきょうします"],
    }
  ),

  today: defineSubQuest(
    "today",
    "schule",
    [
      {
        step: "meaning",
        type: "meaning-choice",
        instruction: "Wähle die richtige Bedeutung.",
        prompt: "今日",
        choices: ["heute", "morgen", "Schule", "Japanisch"],
        answer: "heute",
      },
      {
        step: "word",
        type: "japanese-choice",
        instruction: "Wähle das passende japanische Wort.",
        prompt: "heute",
        choices: ["今日", "学校", "先生", "日本語"],
        answer: "今日",
      },
      {
        step: "particle",
        type: "particle-choice",
        instruction: "Wähle die passende Partikel.",
        prompt: "„Heute gehe ich zur Schule.“\n今日、学校____行きます。",
        choices: ["に", "を", "で", "と"],
        answer: "に",
        exampleJapanese: "今日、学校に行きます。",
        exampleKana: "きょう、がっこうにいきます。",
        exampleGerman: "Heute gehe ich zur Schule.",
      },
      {
        step: "word-blank",
        type: "fill-blank",
        instruction: "Ergänze den Satz.",
        prompt: "„Heute lerne ich Japanisch.“\n____、日本語を勉強します。",
        choices: ["今日", "学校", "先生", "日本語"],
        answer: "今日",
        exampleJapanese: "今日、日本語を勉強します。",
        exampleKana: "きょう、にほんごをべんきょうします。",
        exampleGerman: "Heute lerne ich Japanisch.",
      },
      {
        step: "sentence-meaning",
        type: "sentence-meaning-choice",
        instruction: "Was bedeutet dieser Satz?",
        prompt: "今日、学校に行きます。",
        choices: [
          "Heute gehe ich zur Schule.",
          "Morgen gehe ich zur Schule.",
          "Ich gehe zur Schule.",
          "Heute lerne ich Japanisch.",
        ],
        answer: "Heute gehe ich zur Schule.",
        exampleJapanese: "今日、学校に行きます。",
        exampleKana: "きょう、がっこうにいきます。",
        exampleGerman: "Heute gehe ich zur Schule.",
      },
      {
        step: "phrase",
        type: "phrase-choice",
        instruction: "Wähle den natürlichen japanischen Satz.",
        prompt: "Heute lerne ich Japanisch.",
        choices: [
          "今日、日本語を勉強します。",
          "日本語を勉強します。",
          "今日、学校に行きます。",
          "学校で日本語を勉強します。",
        ],
        answer: "今日、日本語を勉強します。",
        answerKana: "きょう、にほんごをべんきょうします。",
        answerRomaji: "kyou, nihongo o benkyou shimasu",
        answerGerman: "Heute lerne ich Japanisch.",
        exampleJapanese: "今日、日本語を勉強します。",
        exampleKana: "きょう、にほんごをべんきょうします。",
        exampleGerman: "Heute lerne ich Japanisch.",
      },
      {
        step: "mistake",
        type: "mistake-choice",
        instruction: "Achtung, Verwechslungsgefahr: Wähle den richtigen Satz.",
        prompt: "Ziel mit に: „Heute gehe ich zur Schule.“",
        choices: [
          "今日、学校に行きます。",
          "今日、学校で行きます。",
          "今日、学校を行きます。",
          "今日、学校と行きます。",
        ],
        answer: "今日、学校に行きます。",
        exampleJapanese: "今日、学校に行きます。",
        exampleKana: "きょう、がっこうにいきます。",
        exampleGerman: "Heute gehe ich zur Schule.",
      },
      {
        step: "combo",
        type: "sentence-meaning-choice",
        instruction: "Was bedeutet dieser Satz?",
        prompt: "今日、先生と勉強します。",
        choices: [
          "Heute lerne ich mit dem Lehrer.",
          "Heute spreche ich mit dem Lehrer.",
          "Heute gehe ich zur Schule.",
          "Ich lerne mit dem Lehrer.",
        ],
        answer: "Heute lerne ich mit dem Lehrer.",
        exampleJapanese: "今日、先生と勉強します。",
        exampleKana: "きょう、せんせいとべんきょうします。",
        exampleGerman: "Heute lerne ich mit dem Lehrer.",
      },
      {
        step: "mini",
        type: "sentence-meaning-choice",
        instruction: "Mini Challenge: Was bedeutet dieser Satz?",
        prompt: "今日、学校で日本語を勉強します。",
        choices: [
          "Heute lerne ich in der Schule Japanisch.",
          "Heute gehe ich zur Schule.",
          "Ich lerne in der Schule Japanisch.",
          "Heute spreche ich in der Schule Japanisch.",
        ],
        answer: "Heute lerne ich in der Schule Japanisch.",
        exampleJapanese: "今日、学校で日本語を勉強します。",
        exampleKana: "きょう、がっこうでにほんごをべんきょうします。",
        exampleGerman: "Heute lerne ich in der Schule Japanisch.",
      },
    ],
    {
      speechText: "今日、日本語を勉強します。",
      speechKana: "きょう、にほんごをべんきょうします。",
      speechRomaji: "kyou, nihongo o benkyou shimasu",
      speechGerman: "Heute lerne ich Japanisch.",
      acceptedTranscripts: ["今日日本語を勉強します", "きょうにほんごをべんきょうします"],
    }
  ),
};
